### ISSUE TITLE
Sql Dependency error message

### ISSUE THREAD

**Issue by vladimirlapacek** [Microsoft/ApplicationInsights-dotnet-server#101]
The Sql Dependency details are currently limited to a couple fields:

- success
- result code

Although the result code can help with troubleshooting issues, the full error message returned by the SQL server would be more useful, eg.

result code: 2601
vs.
error message: Cannot insert duplicate key row in object 'dbo.Products' with unique index 'UX_ProductSKU'. The duplicate key value is (Selenium SKU Min). The statement has been terminated.

Can the error message be added to the SQL dependency detail?

**Comment by abaranch** [comment]
Message will be added when you have StatusMonitor on the box with the application. Feature will b released with 2.2-beta2

**Comment by vladimirlapacek** [comment]
Hi Anastasia,

I really appreciate your (team) flexibility. It's really amazing :)

Thanks,
Vlad

**Comment by abaranch** [comment]
Welcome :)
