### ISSUE TITLE
Dependency telemetry target is replaced by hostname

### ISSUE THREAD

**Issue by Chewbizz** [Microsoft/ApplicationInsights-dotnet-server#1011]
I'm using Java SDK to send custom telemetry to AppInsights.
When sending HTTP Dependency telemetry (for REST calls) with a specific "target" value, this value is replaced on the server side by the REST server's hostname.
Whereas when sending other Dependency telemetry such as database calls, the "target" value is correctly used on the server side.

For instance, if I send a (HTTP) Dependency telemetry with the following values:
* name: "GET /api/search"
* type: "HTTP"
* data: "http://10.20.30.40:8680/api/search?q=foo"
* target: "catalog"

Whatever the value I set on the "target" attribute, it seems to be ignored, and it is replaced by the hostname ("10.20.30.40" in this example) when I browse telemetry on my AI instance.
I tried to set the target attribute with "roleName:catalog" instead of "catalog". This had no effect.

For a non-HTTP dependency:
* name: "SQL: SELECT query"
* type: "SQL"
* data: _{A JSON String containing request information}_
* target: "Database"

In this case, the target is still "Database" when I browse telemetry on my AI instance.

My goal is to make the application map and the end-to-end transaction display human readable names such as "catalog" instead of hostname ("10.20.30.40" is not very interesting) as it does for "Database".
Note that I could have multiple instances of "catalog" on different hosts. I then expect the application map to show only one "catalog" circle with multiple instances, but that is probably a huge feature request.

I cannot get consistent behaviour in both cases because the server seems to be doing some magic by parsing my "data" attribute to find a "target" although I explicitly set this "target" attribute. This is probably expected by design, but it appears like an issue to me.

In the mean time, I'll try to workaround this problem by setting the data attribute to a JSON string containing the target URL instead of the URL directly. I hope it'll do the trick.

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/898 Duplicate? 
We can track it in the other issue.

**Comment by Chewbizz** [comment]
Yes, this is a duplicate. I searched before posting, but I missed to search on ApplicationInsights-dotnet
repo. Thanks a lot for the fast reply.
