### ISSUE TITLE
CommandName for tracking custom dependencies is not shown in the Metrics Explorer

### ISSUE THREAD

**Issue by tsunami-kevin** [Microsoft/ApplicationInsights-dotnet-server#102]
When I use [TelemetryClient.TrackDependency Method (String, String, DateTimeOffset, TimeSpan, Boolean)](https://msdn.microsoft.com/en-us/library/mt403046.aspx) the CommandName parameter value is not shown in the Metrics Explorer in the Azure Portal.

A suggested workaround is to specify the [DependencyTelemetry.DependencyTypeName](https://msdn.microsoft.com/en-us/library/microsoft.applicationinsights.datacontracts.dependencytelemetry.dependencytypename.aspx) property to be "SQL". This will get the CommandName value to be shown in the Dependency Property blade in the Azure Portal however it clutters the analytics if the type is not SQL.

Repro Steps:

1. `telemetryClient.Track("MyCustomDependency", "MyCommandName", startTime, duration, success);`

Expected Result:
- In the Dependency Property blade in the Azure Portal the Command value should be "MyCommandName"

Actual Result:
- Command value is "MyCustomDependency".
![image](https://cloud.githubusercontent.com/assets/2914974/16674145/1aa07c8c-446a-11e6-994b-3e44ff5d5ed5.png)
![image](https://cloud.githubusercontent.com/assets/2914974/16674140/15d90200-446a-11e6-8ccb-f3aa98daa547.png)

More info here:
https://social.msdn.microsoft.com/Forums/en-US/ApplicationInsights/thread/f8e069c1-d72e-4c89-ba28-9cebf8571aff/

**Comment by AlexBulankou** [comment]
Thanks for reporting, this is a known issue that we are tracking.

**Comment by AlexBulankou** [comment]
This was fixed a week ago, sorry for slow response.
