### ISSUE TITLE
Allow users to ignore specific UnobservedTaskExceptions

### ISSUE THREAD

**Issue by i3arnon** [microsoft/ApplicationInsights-dotnet-server#1026]
Sometimes you encounter `UnobservedTaskException`s that are outside of your control (e.g. in third-party libraries or in the framework itself).
Currently you can either have them mixed in with the fixable `UnobservedTaskException`s which lowers signal-to-noise ratio, or you must remove the entire `UnobservedExceptionTelemetryModule`.

It would be useful to have some way to ignore specific `UnobservedTaskException`s without throwing the baby with the bathwater.

**Comment by SergeyKanzhelev** [comment]
Can you please also provide a code example on how you propose to ignore some of them.

**Comment by i3arnon** [comment]
You can ignore them by subscribing to `TaskScheduler.UnobservedTaskException` and marking them as observed.

For example this ignores all `ObjectDisposedException` and exceptions coming from `UdpClient.EndReceive`:

```csharp
void UnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs eventArgs)
{
    var exception = eventArgs.Exception.InnerException;
    if (exception is ObjectDisposedException ||
        exception?.TargetSite == typeof(UdpClient).GetMethod(nameof(UdpClient.EndReceive)))
    {
        eventArgs.SetObserved();
    }
}
```
