### ISSUE TITLE
AZURE SERVICEBUS - Current Activity is prematurely stopped. Should be stopped once all observers have been notified!

### ISSUE THREAD

**Issue by Hyjaz** [Microsoft/ApplicationInsights-dotnet-server#1038]
## Repro Steps
1. Subscribe a new Observer on `"Microsoft.Azure.ServiceBus"`
2. On streams of incoming events use Activity.Current to get the current activity and log some properties for the current activity, such as the Root_Id for example.

##  Actual Behavior

Activity.Current is null, because it is stopped on [ServiceBusDiagnosticsEventHandler line 67](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/EventHandlers/ServiceBusDiagnosticsEventHandler.cs#L67)
## Expected Behavior

Activity.Current to not be null, until all observers have been notified.

## Version Info 
SDK Version : 2.7.2
.NET Version : netstandard2.0					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : visual studio
OS : Windows
Hosting Info (IIS/Azure WebApps/ etc) : Console application

**Comment by lmolkova** [comment]
thanks for submitting it! you are right. Here is the code responsible for it:

https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/EventHandlers/ServiceBusDiagnosticsEventHandler.cs#L40

**Comment by Hyjaz** [comment]
For now until this is resolved, one way to get around this, is to subscribe the custom observers that listen on `Microsoft.Azure.ServiceBus` before ServiceBus's observer is subscribed.

One of the problem with this workaround is that, the current activity will not have the duration. The duration will need to be calculated manually by the client.

**Comment by lmolkova** [comment]
We'll fix it in 2.9. Could you please share your scenario where you need an additional subscriber?

**Comment by Hyjaz** [comment]
We are making use of TrackEvent so that we can pass it properties other than the ones passed by default with Microsoft.Azure.ServiceBus which makes use of the Trace api. Just a different way of tracking I guess...

**Comment by lmolkova** [comment]
can you call TrackEvent during message processing, not after it or you rely on some payloads that ServiceBus sends in Stop events?

**Comment by Hyjaz** [comment]
I rely on some payloads that ServiceBus sends in Stop events
