### ISSUE TITLE
Enable Azure Search Parser 

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Microsoft/ApplicationInsights-dotnet-server#1048]
Hello, This is not an issue. 

We'd like to add Azure Search Parser. If you guys are OK, we'd like to contribute with @k-miyake and @shibayan .
 
https://github.com/Microsoft/ApplicationInsights-dotnet-server/tree/develop/Src/DependencyCollector/Shared/Implementation/HttpParsers

Do you know if someone is working on this?

**Comment by lmolkova** [comment]
@TsuyoshiUshio nobody should be working on this. 

@SergeyKanzhelev, @Dmitry-Matveev  I remember we have additional logic on Breeze to parse dependency kinds. Do you think it makes sense to enable Azure Search dependency type parser in .NET SDK or we'd rather change Breeze to support all SDKs?

**Comment by SergeyKanzhelev** [comment]
@lmolkova it is important to implement this logic in the layer that does pre-aggregation. Application Insights endpoint is a last resort in that case for SDKs that doesn't have any pre-aggregations. Ideally do it in SDK and than in local forwarder

**Comment by SergeyKanzhelev** [comment]
@TsuyoshiUshio we welcome contributions! Azure Search support would be great!

**Comment by TsuyoshiUshio** [comment]
Thank you, @lmolkova and @SergeyKanzhelev ! We’ll work on that with @k-miyake and @shibayan

**Comment by SergeyKanzhelev** [comment]
@TsuyoshiUshio let us know if you need some help

**Comment by shibayan** [comment]
I just implemented Azure Search parser. Please review my PR.

**Comment by lmolkova** [comment]
Thanks for the contribution!
