### ISSUE TITLE
Change verbosity of message about counters not being collected under iisexpress

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-dotnet-server#105]
Currently this message is verbose: Performance counters are unavailable when the application is running under IIS Express. Use EnableIISExpressPerformanceCounters element with a value of 'true' within the Performance Collector Module element to override this behavior.
So this message will never be sent to the portal.
Proposal is to change it to error (so it is sent to the portal) with diagnostics keyword (for it is not sampled out)

**Comment by dnduffy** [comment]
Good idea.
