### ISSUE TITLE
Missing SQL dependency information

### ISSUE THREAD

**Issue by leppie** [Microsoft/ApplicationInsights-dotnet-server#106]
Not sure what the logic is, or if `async` has anything to do with it, but (recently, I think) SQL dependencies have gone missing. They are indeed recorded as shown in the screenshot, but not linked to the request.

The ones marked with red arrows are missing.
![image](https://cloud.githubusercontent.com/assets/127666/16913794/5fae325c-4ced-11e6-887c-3b7544176fc1.png)
I can't seem to find anything that correlates this data in the UI. Let me know if I can check somewhere else.

Edit: It seems in the 3 items marked, there is a bunch of missing info, eg Operation Id, USer Id, Session Id, etc.

**Comment by abaranch** [comment]
Correlation of async dependencies is not supported. You can use operations API.
Some details here: https://azure.microsoft.com/en-us/blog/save-money-with-application-insights-web-sdk-2-0/

**Comment by leppie** [comment]
WAT!? So this extremely valuable feature is just dismissed out of hand with no explanation? 

BTW using your own dependencies is horribly inaccurate and will screw up the timeline.
