### ISSUE TITLE
SQL Dependency duration recorded incorrectly

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet-server#108]
Customer claims SQL dependency calls are taking 70 seconds and yet AI is showing them as <100ms. More details in internal email.

![image](https://cloud.githubusercontent.com/assets/11968377/16972827/6de8a6f8-4de3-11e6-9370-1fbe5529f544.png)

**Comment by abaranch** [comment]
Most likely it is related to #62 
Do you have a simple repro app?

**Comment by martinnormark** [comment]
I'm sure we're seeing this issue too.

I don't have a sample app that can repro - but I can try something in our project.

Could it be that it discards wait time and only logs the time taken in SQL to complete the query?

Anyway, we're digging deeper to verify if duration is indeed incorrect and circle back with any findings.

**Comment by SergeyKanzhelev** [comment]
@martinnormark thanks! In the collected dependencies - what sdk version do you see? `rddf` or `rddp`? Inside the dependency click on more properties button: "..."

![image](https://cloud.githubusercontent.com/assets/9950081/19813357/3983ebf2-9cee-11e6-928c-1bd3bc1c3a01.png)

And search for *SDK Version*:

![image](https://cloud.githubusercontent.com/assets/9950081/19813378/5c05b354-9cee-11e6-8d63-1fe54515044f.png)

**Comment by AlexBulankou** [comment]
OpenConnection/OpenConnectionAsync issue was the only collection gap that we closed with [this change](https://github.com/Microsoft/ApplicationInsights-dotnet-server/commit/394462d470cc5c16383c1a11cfcd112686fa9b62). The linked issue #62 is related to HTTP chunked request processing so is a separate issue.
@SergeyKanzhelev , @cijothomas, @iusafaro, @dmitry-matveev
