### ISSUE TITLE
Correlation doesn't work for localhost => breaks Azure Service Fabric's built-in reverse proxy

### ISSUE THREAD

**Issue by zakimaksyutov** [Microsoft/ApplicationInsights-dotnet-server#1120]
Built-in Azure Service Fabric's reverse proxy is access through localhost. Due to this logic (line about localhost) AI SDK doesn't do correlation:

		<Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">
			<ExcludeComponentCorrelationHttpHeadersOnDomains>
				
				<Add>core.windows.net</Add>
				<Add>core.chinacloudapi.cn</Add>
				<Add>core.cloudapi.de</Add>
				<Add>core.usgovcloudapi.net</Add>
				<Add>localhost</Add>
				<Add>127.0.0.1</Add>
			</ExcludeComponentCorrelationHttpHeadersOnDomains>
			<IncludeDiagnosticSourceActivities>
				<Add>Microsoft.Azure.EventHubs</Add>
				<Add>Microsoft.Azure.ServiceBus</Add>
			</IncludeDiagnosticSourceActivities>
		</Add>

According to @lmolkova this logic isn't required anymore. Let's remove it?

**Comment by lmolkova** [comment]
## Warning! 

Do NOT do this workaround if you have Microsoft.ApplicationInsights.DependencyCollector 2.6.0 or previous versions and run Azure Storage Emulator on localhost! It results in issue sending requests to storage.

## Workaround

ASP.NET (classic) - ApplicationInsights.Web SDK from 2.7.0-beta1 to <= 2.9.0-beta2

Users can enable correlation on localhost by removing 
```
<Add>localhost</Add>
<Add>127.0.0.1</Add>
```

AspNetCore (ApplicaitonInsights.AspNetCore <= 2.6-beta2) users can do 

```csharp
public void ConfigureServices(IServiceCollection services)
{
    ...

    services.AddApplicationInsightsTelemetry();
    services.ConfigureTelemetryModule<DependencyTrackingTelemetryModule>((m, _) =>
    {
        m.ExcludeComponentCorrelationHttpHeadersOnDomains.Remove("localhost");
        m.ExcludeComponentCorrelationHttpHeadersOnDomains.Remove("127.0.0.1");
    });
}
```

**Comment by MS-TimothyMothra** [comment]
@lmolkova can we close this?
