### ISSUE TITLE
Stripping port from target breaks Application Map for reverse proxy scenarios

### ISSUE THREAD

**Issue by zakimaksyutov** [Microsoft/ApplicationInsights-dotnet-server#1121]
AI SDK strips port from target field. This breaks reverse proxy scenarios which differentiate which app to forward to by using a port.

Should we consider keeping a port in target?

**Comment by SergeyKanzhelev** [comment]
Is it a reoccurance of https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/285?

**Comment by zakimaksyutov** [comment]
It says that it is fixed in 2.3. Looks like it regressed at some point. Or maybe this logic doesn't work only for localhost targets.

**Comment by lmolkova** [comment]
this logic does not work for .net core only.
