### ISSUE TITLE
How to prevent losing telemetry pageView with Application Insight's Persistence Channel?

### ISSUE THREAD

**Issue by sahithi77** [Microsoft/ApplicationInsights-dotnet-server#1129]
when internet connection is available application insights for wpf application works fine and I am able to track page and events in azure portal but I want to know is it possible to store telemetry data somewhere in system when their is no internet connection and retrieve it when system is online and track those actions which I performed when their was no internet connection.

**Comment by cijothomas** [comment]
Are you using ServerTelemetryChannel? If yes, it has mechanisms to store telemetry into local disk when network is lost and retry when back online.
