### ISSUE TITLE
PerformanceCollectorModule should not try to collect ASP.NET performance counters for non-web applications

### ISSUE THREAD

**Issue by fschmied** [Microsoft/ApplicationInsights-dotnet-server#1139]
## Repro Steps/Actual Behavior
When I install the `Microsoft.ApplicationInsights.WindowsServer` NuGet package in a console application or Windows service, Application Insights will automatically log this error message:

> AI: Error collecting 3 of the configured performance counters. Please check the configuration. Counter \ASP.NET Applications(??APP_W3SVC_PROC??)\Requests/Sec: Failed to perform the first read for performance counter. Please make sure it exists. Category: ASP.NET Applications, counter: Requests/Sec, instance SignPath.Application.Applications.Deletion.ProcessorService.exe Counter \ASP.NET Applications(??APP_W3SVC_PROC??)\Request Execution Time: Failed to perform the first read for performance counter. Please make sure it exists. Category: ASP.NET Applications, counter: Request Execution Time, instance SignPath.Application.Applications.Deletion.ProcessorService.exe Counter \ASP.NET Applications(??APP_W3SVC_PROC??)\Requests In Application Queue: Failed to perform the first read for performance counter. Please make sure it exists. Category: ASP.NET Applications, counter: Requests In Application Queue, instance XXX.exe

This is because the `PerformanceCollectorModule` automatically installs these performance counters, which are not available in non-web applications. The error message makes it look like I'm doing something wrong and need to take action.

This is aggravated by the fact that it seems one can't influence these defaults via configuration (see also #7).

## Expected Behavior
I'd expect that installing the `Microsoft.ApplicationInsights.WindowsServer` in a console application or Windows Service does not lead to an error message being logged.

## Version Info 
SDK Version : `Microsoft.ApplicationInsights.WindowsServer 2.8.1`
.NET Version : .NET Framework 4.7.2
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Added NuGet package, copied over default ApplicationInsights.config from another project (because this is an SDK-style projekt, where ApplicationInsights.config isn't added by installing the NuGet package)
OS : Windows 10 1803
Hosting Info (IIS/Azure WebApps/ etc) : Console application ran locally

**Comment by cijothomas** [comment]
With https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/7, there wont be any default counters, so you'll no longer see this issue. Will use existing #7 to tracking purposes. Closing this.
