### ISSUE TITLE
StartOperation<DependencyTelemetry>("OperationName")   operation_Name is not always set correctly and is assigned to the wrong operation.

### ISSUE THREAD

**Issue by colindooley11** [Microsoft/ApplicationInsights-dotnet-server#1155]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
Hi,

I have a block of code I want to execute which I want all of the related dependency telemetry to be logged with the same operation_Name.

This "_kind of works_" **BUT** I am getting interleaved results with **operation_Name** remaining the same for the next execution of the following code path (which is, in effect, the next handling of a message)

For example I have the following code, which handles a message (An NServiceBus message in this instance)

When it is first handled the operation_Name (recorded in App Insights against all related dependency telemetry) should be
PROCESSED: 1

and the next time
PROCESSED: 2
and so on

It takes a message, does some work and calls off to various external dependencies (Cosmos and Http (via HttpClient))

External dependencies are registered on a container (SimpleInjector).

A logger ( a thin pass thru abstraction for TelemetryClient calls (for unit testing))  is registered as a singleton
(I have expanded out the actual call in the example below to use an instance of telemetryClient instead of the singleton which is injected in) 

The DocumentClient for the Cosmos Http call is registered as a singleton too.

2 different HttpClients are registered as singletons. One is used for _Call 2_ and _3_, and the other for _4_
The HttpClients point to different resources and the first is registered with a delegating handler to add some authentication headers (this isn't needed for call 4 as this is a different external resource not requiring authentication)

```
public async Task Handle(MyMessageType message, IMessageHandlerContext context)
{
          var telemetryClient = new TelemetryClient(TelemetryConfiguration.Active);
          using (telemetryClient.StartOperation($" PROCESSED: {message.Reference} ))
           {
              // DO SOME WORK 
              // await Cosmos call (http call 1).ConfigureAwait(false) 
              // await Http Call 2.ConfigureAwait(false) 
              // await Http Call 3.ConfigureAwait(false) 
              // await Http Call 4.ConfigureAwait(false) 

           }
     }
```
I have tried different flavours above, a new logger (TelemetryClient) each time, calling stop operation,  calling flush etc.    

I get the log lines I expect, plus some log lines which should have a different operation_Name. Querying the application insights dependencies collection via:

`dependencies | where operation_Name = "PROCESSED: 1"`

Produces something like:

2019-02-21 | |jy2Qy6/gJpg=.f0b42cd6_1. | [https://cosmos|](https://cosmos%7C) HTTP | POST | PROCESSED :1
2019-02-21 | |jy2Qy6/gJpg=.f0b42cd6_2. | https://httpCall2 | HTTP | POST | PROCESSED :1
2019-02-21 | |jy2Qy6/gJpg=.f0b42cd6_3. | [https://httpCall3|](https://httpCall3%7C) HTTP | POST | PROCESSED :1
2019-02-21 | |jy2Qy6/gJpg=.f0b42cd6_4. | [https://httpCall4|](https://httpCall4%7C) HTTP | POST | PROCESSED :1
**2019-02-21 | |DIFFERENT_OperationId_1. | [https://cosmos|](https://cosmos%7C) HTTP | POST | _PROCESSED :1_**

**NOTE**: The last line should NOT be included here its operation name **should be PROCESSED: 2**

The operation Ids and parent operation Ids seem to be have reconciled properly, the operation name is being retained somewhere.

I'd hazard a guess the underlying `Activity` (used in Start operation and taken from a thread local variable?) is not having its operation_Name correctly set and reset?

Can someone help, this is driving me to insanity.
##  Actual Behavior
I get the log lines I expect, plus some log lines which should have a different operation_Name. Querying the application insights dependencies collection via:

`dependencies | where operation_Name = "PROCESSED: 1"`

Produces something like:

2019-02-21 | |jy2Qy6/gJpg=.f0b42cd6_1. | [https://cosmos|](https://cosmos%7C) HTTP | POST | PROCESSED :1
2019-02-21 | |jy2Qy6/gJpg=.f0b42cd6_2. | https://httpCall2 | HTTP | POST | PROCESSED :1
2019-02-21 | |jy2Qy6/gJpg=.f0b42cd6_3. | [https://httpCall3|](https://httpCall3%7C) HTTP | POST | PROCESSED :1
2019-02-21 | |jy2Qy6/gJpg=.f0b42cd6_4. | [https://httpCall4|](https://httpCall4%7C) HTTP | POST | PROCESSED :1
**2019-02-21 | |DIFFERENT_OperationId_1. | [https://cosmos|](https://cosmos%7C) HTTP | POST | _PROCESSED :1_**

## Expected Behavior
2019-02-21 | |jy2Qy6/gJpg=.f0b42cd6_1. | [https://cosmos|](https://cosmos%7C) HTTP | POST | PROCESSED :1
2019-02-21 | |jy2Qy6/gJpg=.f0b42cd6_2. | https://httpCall2 | HTTP | POST | PROCESSED :1
2019-02-21 | |jy2Qy6/gJpg=.f0b42cd6_3. | [https://httpCall3|](https://httpCall3%7C) HTTP | POST | PROCESSED :1
2019-02-21 | |jy2Qy6/gJpg=.f0b42cd6_4. | [https://httpCall4|](https://httpCall4%7C) HTTP | POST | PROCESSED :1
LINE OMITTED FROM QUERY - operation_Name correctly stamped.

As a  brucey bonus I'd love to know how HttpClient is used by the SDK to to emit/send out its telemetry.  I don't know if I've read correctly the byte code emitted with HttpClient is used. 

## Version Info 
SDK Version :
System.Net HTTP 4.2.0.0 (HttpClient) 
Microsoft.ApplicationInsights 2.8.1 
Microsoft.ApplicationInsights.DependencyCollector 2.8.1
.NET Version :	
.Net Framework 4.6.1 		
NServiceBus 7			
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio/Nuget Packages
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Console Application and then inside an NServiceBus Virtual Endpoint and Handler therein.

**Comment by colindooley11** [comment]
The http call to Cosmos appears to throw everything out. Now that is baffling...

**Comment by colindooley11** [comment]
Ok, so yet further testing involving newing up a document client for each message handling invocation (instead of using one registered on the container) resolves this issue.

**Comment by colindooley11** [comment]
Yet further testing with 2 types of container (SimpleInjector and CastleWindsor) show the same inconsistent results (ruling out lifecycle management of dependencies being an issue specific related to a container implementation - doesn't rule out issue with registration but at least they are consistently wrong)

Having 1 HttpClient for both calls (ignoring the need to authenticate for some of the calls and not others for the moment)   yields even more wild results (the recommendation is to share HttpClient across an application  - https://github.com/Azure/azure-functions-host/wiki/Managing-Connections)   this clearly does not always work at the moment.  

So this doesn't work either

**Comment by colindooley11** [comment]
Ok, so the last bit of testing on this.  I'm out..... 
Basically it appears as though ALL of the external dependencies you want to use StartOperation on HAVE to  be created WITHIN the scope of it.  

You can not (it appears) use objects which are already instantiated (even if only as singletons) which are then used through the StartOperation method.     

As the post suggests in my last comment, its not ideal to have to new up a HttpClient each time (or DocumentClient - which likely uses Http client under the hood)

Given this apparent limitation the only viable alternative is to use "TrackDependency"  which now litters code (unless using some kind of aspect) with logging.....

It all started so well......

**Comment by lmolkova** [comment]
Startoperation is not related in any way to the client lifetime. Something else is going on in your case. 
Could you please provide repro app so we can help you on this case?

**Comment by lmolkova** [comment]
Also, operation name is in fact name of the parent operation. 
In case of dependency, it is likely the name of parent request.

I suggest you to set Dependency.Name explicitly and it should fix the issue.

**Comment by colindooley11** [comment]
@lmolkova. I'll try and get a repro application to you. In the meantime what do you mean set the Dependency.Name explicitly?  I only ever attempt to group all telemetry under the operation_Name.

Thanks.   


I agree something else is definitely going on in my case and I can't fathom it.

**Comment by colindooley11** [comment]
Also I was reading some of your other posts, how is the telemetry emitted for HttpClient? Is it by using HttpHandlerDiagnosticListener?  Or by other means (I'd read the SDK uses byte code somewhere, or some other instructions) to help with instrumentation.  Would like to know a bit more.

As an aside we do make changes to Service PointManager to allow us to be unaffected by DNS changes, I'm hazarding a guess this should have no impact too?

**Comment by colindooley11** [comment]
Updated title.  To extend this further.  The operation and parent operation ids are ALWAYS present and correct and instead setting these like so for example

`StartOperation<DependencyTelemetry>("General Name", guid, guid)`

Works a treat as we cant rely on a value in the name argument to be assigned correctly (see log lines in earlier comments)

**Comment by lmolkova** [comment]
operation_Name (kusto) corresponds to dependencyTelemtery.Context.Operation.Name Porperty - this is the name of high-level operation. 

name (kusto) corresponds to depednencyTelemtery.Name property - this is the name of this specific telemtery.

StartOperation allows you to set name property.

What happens (this is an assumption) that you set name property, but somehow validate operation_name. And they are not the same. I'd suggest you don't use oepration_name in your queries as it is not very reliable.

As an improvement you might want to consider: please use RequestTelemetry to track message processing. Dependencies should be used for outbound calls tracking.

Http instrumentation is different for
- .NET framework apps:
  - diagnostics source instrumentation: https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/HttpDesktopDiagnosticSourceListener.cs
  - if you run WebApp extension or status monitor, it is achieved with profiler:  https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/ProfilerHttpProcessing.cs

- .NET Core apps:
  - another diagnostics source https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/HttpCoreDiagnosticSourceListener.cs

**Comment by colindooley11** [comment]
Thanks for the reply.  out of interest why is operation_Name unreliable?  

I can try request telemetry instead of course.  
The nested dependencies will emit their telemetry like before.  

I'm not sure how it will fix things tbh.   That guidance seems to contradict some of the docs I have read where it says that the sender should use request telemetry and the receiver should use dependency telemetry.   

But, regardless I appreciate your time here.

**Comment by lmolkova** [comment]
operation_name might not be known at the time when dependency is tracked. Or operation (transaction) may have started on other service.

> That guidance seems to contradict some of the docs I have read where it says that the sender should use request telemetry and the receiver should use dependency telemetry.

Request is service-side telemetry that describes server response time and result. Dependency is client side telemtery that describes outgoing call. All outbound http calls are tracked as dependencies, all inbound calls are tracked as requests. If there is a guidance that says otherwise, please post it here and we'll fix it.

**Comment by colindooley11** [comment]
My bad, I've got them the wrong way around !

https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-operations-tracking

If this works I'll be a happy man.

**Comment by lmolkova** [comment]
@colindooley11 changing dependency to request solves other problems you didn't mention. let's try to make sure request.name is what you expect and correlation works correctly. 
You also mentioned StartOperation<DependencyTelemetry>("General Name", guid, guid) solves the issue for you, di I get that correctly?

**Comment by colindooley11** [comment]
Yes the last does work if I ignore (kusto) operation_Name and instead query on Id.

I'm sorry I have become absolutely fixated on operation_Name in the absence of all else around it.

**Comment by colindooley11** [comment]
Out of interest when I use Request Telemetry what should I query on.  Will it be an id, or the name.  what is the recommendation?

**Comment by colindooley11** [comment]
The request telemetry type does not resolve this issue, unfortunately.   I suspect it is something to do with NServiceBus and how it is managing concurrency and where the types used to house the current Activity are being stored (are these thread safe in NServiceBus) there seems to be cross talk if the storage of the current activity is being update from what seems 2 different operations.

**Comment by colindooley11** [comment]
I guess the last thing I was interested in was why operation_Name was unreliable, you said that in an earlier post.  What makes this unreliable?

**Comment by lmolkova** [comment]
It seems that StartOperation<DependencyTelemetry>("General Name", guid, guid) solved whatever problem you had, but I'm not sure.

I think I already explained the operation name is not useful and should not be used and also explained why.

I'm sorry, I'm completely lost at this point. 

Could you please start from scratch and describe what is the problem and provide the repro app.

**Comment by colindooley11** [comment]
I'm sorry, I think my energy has wained on this too.

I guess I didn't understand this

"operation_name might not be known at the time when dependency is tracked. Or operation (transaction) may have started on other service"

If the dependencies are called after calling start  operation the tracked dependencies should always have a name. 

I've got a workaround anyway.  

Thanks for all your help.

**Comment by lmolkova** [comment]
Thanks, I'm closing this for now. Feel free to reopen as needed.
