### ISSUE TITLE
Microsoft.AI.Agent.Intercept 2.0.1.0 not compatible dependency collector

### ISSUE THREAD

**Issue by virtualcca** [Microsoft/ApplicationInsights-dotnet-server#119]
if I update Microsoft.AI.Agent.Intercept 2.0.1.0
I always can not be collect dependency data
I debug in a ITelemetryInitializer I receive a exception

  [msg=RemoteDependencyModule failed];[msg=System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AI.Agent.Intercept, Version=1.2.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

**Comment by virtualcca** [comment]
my update package didn't update web.config
so it didn't had
 <dependentAssembly>
        <assemblyIdentity name="Microsoft.AI.Agent.Intercept" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.1.0" newVersion="2.0.1.0" />
      </dependentAssembly>

if I add it ,it will work

**Comment by virtualcca** [comment]
<dependentAssembly>
        <assemblyIdentity name="Microsoft.AI.Agent.Intercept" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.1.0" newVersion="2.0.1.0" />
      </dependentAssembly>

**Comment by abaranch** [comment]
You definitely need binding redirect, nuget was supposed to add it when you installed the package.

**Comment by davideicardi** [comment]
Same problem here, I have manually added:

			<dependentAssembly>
				<assemblyIdentity name="Microsoft.AI.Agent.Intercept" publicKeyToken="31bf3856ad364e35" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.0.6.0" newVersion="2.0.6.0" />
			</dependentAssembly>
