### ISSUE TITLE
Add netstandard 2.0 target on WindowsServer and DependencyCollector

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet-server#1212]
All .net core libs should target 2.0

**Comment by lmolkova** [comment]
netstandard 2.0 target does not require additional dependencies on

WindowsServer
NETStandard.Library (>= 1.6.1)
System.Runtime.Serialization.Json (>= 4.3.0)
System.Runtime.Serialization.Primitives (>= 4.3.0)

DependecnyCollector:
NETStandard.Library (>= 1.6.1)
System.Data.SqlClient (>= 4.3.1)
System.Diagnostics.StackTrace (>= 4.3.0)

**Comment by cijothomas** [comment]
Thanks for opening this. We can try to do this in next release.
