### ISSUE TITLE
Support EventCounter Collection

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet-server#1222]
Starting with .NET Core 3.0 there will a bunch of system-wide counters published using EventCounters. ApplicationInsights SDK need to support collecting of event counters as its replacing PerformanceCounters.

We will support EvenCounter collection NETSTANDARD20 onwards, but nobody is publishing any counters by default, until .net core 3.0. So this will only help collect which user is publishing. Starting with .NET Core 3.0, AspNetCore SDK enables a set of built-in counters.

This module should allow collecting EventCounter from any source/counternames. A pre-defined set of counters will be auto-collected if using Asp.Net Core SDK.

Read more:
Initial List of available counters:
https://github.com/dotnet/diagnostics/blob/master/src/Tools/dotnet-counters/KnownData.cs

EventCounter Tutorial: 
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/documentation/EventCounterTutorial.md

Part of this: https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/1188

**Comment by cijothomas** [comment]
Originally posted: https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/601

**Comment by alejagapatrick** [comment]
https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/1222
