### ISSUE TITLE
Deadlock/hang in RequestTrackingTelemetryModule.IsHandlerToFilter

### ISSUE THREAD

**Issue by LeMaciek** [microsoft/ApplicationInsights-dotnet-server#1227]
Deadlock/hang in  RequestTrackingTelemetryModule.IsHandlerToFilter

## Repro Steps
We've just upgraded to ai 2.10 from 2.8 and...
On one of the webapplications - a webapi controller (Classic Asp.Mvc) was timing out,after looking into it, i saw this:
![image](https://user-images.githubusercontent.com/1091052/60601683-cf598200-9db2-11e9-91a9-8dc6920be437.png)
and in dumps this:
![image](https://user-images.githubusercontent.com/1091052/60601735-e26c5200-9db2-11e9-94fa-ac71e03f76eb.png)

This led me to #1211, which might be helpful :)
It would be nice of You to release a 2.10.1 with this fix...

## Version Info 
SDK Version : 2.10
.NET Version : 4.7.2	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS : Windows server 2012
Hosting Info (IIS/Azure WebApps/ etc) : IIS

**Comment by cijothomas** [comment]
This does not appear to be a regression in 2.10 to release 2.10.1 to address this. From what I can see, this existed for older versions as well. The fix is coming in 2.11.0-beta1 to be released this week.
