### ISSUE TITLE
Update/Re-install does not bring applicationinsights.config

### ISSUE THREAD

**Issue by kartang** [Microsoft/ApplicationInsights-dotnet-server#124]
Repros:

Scenario1:  Create a new application, add 2.0.0 application insights, delete "AI.config" file, go to nuget manager and select "Update" that updates the ai version to 2.1.0, and the config file that is created is completely empty.
Scenario2: Create a new application, add 2.0.0 appilcatoin insights, uninstall the sdk and as a result the config file gets deleted, now install 2.1.0 and the same issue can be seen.

**Comment by cijothomas** [comment]
Scenario2 is invalid. Uninstalling sdk does not delete AI.config, it simply remove those modules from the Ai.config,.
