### ISSUE TITLE
Recognize DocumentDB out of the box

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#125]
Document DB has a REST API: https://msdn.microsoft.com/en-us/library/azure/mt622086.aspx that should be recognized and not sent as a regular HTTP

**Comment by SergeyKanzhelev** [comment]
Today we recognize Azure Storage resources by parsing url:

```
    protected static TYPE_AZUREBLOB: string = "Azure blob";
    protected static TYPE_AZUREQUEUE: string = "Azure queue";
    protected static TYPE_AZURETABLE: string = "Azure table";
```

We should include document DB support in this list.

**Comment by cijothomas** [comment]
We should consider this for beta3. Should be relatively small work.

**Comment by cijothomas** [comment]
Moving this out of beta3 as this will part of new features about adding more Dependency sources.

**Comment by SergeyKanzhelev** [comment]
@TomMilos  is working on it: https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/414
