### ISSUE TITLE
System.Data.SqlClient replaced with Microsoft.Data.SqlClient in .NET CORE 3.0 and sql calls are not tracked in 3.0

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet-server#1263]
EF for .NET Core 3.0 replaces System.Data.SqlClient with Microsoft.Data.SqlClient.
https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/

The new Microsoft.Data.SqlClient publishes the same diagnosticsource events as System.Data.SqlClient, but with the prefix of the individual events replaced with "Microsoft.Data.SqlClient" (https://github.com/dotnet/SqlClient/blob/654933a0811ab30b843a20aff051b8d585238505/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlClientDiagnosticListenerExtensions.cs), as opposed to "System.Data.SqlClient" (https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlClientDiagnosticListenerExtensions.cs)

ApplicationInsights dependency collector needs to listen to new events to monitor SQL Calls using the Microsoft.Data.SqlClient,

**Comment by stebet** [comment]
Hi @cijothomas 

I'm having similar issues with a .NET Framework 4.7.2 application (ASP.NET MVC 5) with 2.11. I have created a new issue here: https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/1282
