### ISSUE TITLE
How to set the value of Context.User.Id in PerformanceCollector 

### ISSUE THREAD

**Issue by Fisher-Joe** [microsoft/ApplicationInsights-dotnet-server#1270]
## Expected Behavior
I want set a value for Azure's AI Log(Analytics) performanceCounters.user_Id.
How the write the code to implement this goal.

![image](https://user-images.githubusercontent.com/12068896/65294319-d5305980-db90-11e9-9104-55cb942c0dbd.png)

## Version Info 
SDK Version :  Microsoft.AI.PerfCounterCollector  2.10.0.0
.NET Version :	 4.5						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Win10 + Console

**Comment by cijothomas** [comment]
Have you tried using telemetryinitializer to add user info?
https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#add-properties-itelemetryinitializer

**Comment by Fisher-Joe** [comment]
Thank you ,Thank you very much.
It's helpful.
