### ISSUE TITLE
Dependency Parent IDs not set correctly in 2.8.0

### ISSUE THREAD

**Issue by aarondandy** [microsoft/ApplicationInsights-dotnet-server#1277]
Dependency Parent IDs not set correctly in 2.8.0. Reverting from 2.8.0 back to 2.7.1 is a workaround for me.

## Repro Steps
1. Upgrade from 2.7.1 to 2.8.0 in either 2.2 project or a 3.0 project
2. Run application, sending telemetry to AI

##  Actual Behavior

A request with a Request Id of `|af71200102f65e46b9c58cd203474526.f0f605963ec9474d.` will have a dependency (SQL for example) with a Parent Id of `00-af71200102f65e46b9c58cd203474526-f0f605963ec9474d-00`

## Expected Behavior

The Parent Id matches the Request Id of the parent.

## Version Info 
SDK Version (version of https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore) : 2.8.0
.NET Core Version (TargetFramework in your .csproj file) : 3.0 or 2.2 	 						
How Application was onboarded with SDK(Installed Nugets/VisualStudio/Azure WebAppExtension) : nuget
OS : Windows
Hosting Info (IIS/Azure Web Apps/Running From Visual Studio etc) : Yes.

**Comment by cijothomas** [comment]
This will be fixed and released as a ".1" release.

**Comment by aarondandy** [comment]
Microsoft.ApplicationInsights.AspNetCore 2.8.1 seems to fix this issue.
