### ISSUE TITLE
Support reading metadata when collecting EventCounter data

### ISSUE THREAD

**Issue by Expecho** [microsoft/ApplicationInsights-dotnet-server#1287]
Regarding the (new) Microsoft.ApplicationInsights.EventCounterCollector:

When I define a custom `EventCounter` I can add metadata to it:

```csharp
methodDurationCounter = new EventCounter(nameof(methodDurationCounter), this);
methodDurationCounter.AddMetadata("Environment", "Production");
methodDurationCounter.AddMetadata("Customer", "Ibis");
```

This metadata is added to the payload. I would be very happy when this data is included as custom properties of the MetricTelemetry that is send. See the [source](https://github.com/microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/EventCounterCollector/EventCounterCollector/EventCounterListener.cs#L225).

I would be more than willing to provide a PR for this.

**Comment by cijothomas** [comment]
AddMetadata is available only in .NET Core 3.0 right? But it shouldn't affect listener.

Yes we are happy to accept a PR to make this enhancement.

**Comment by Expecho** [comment]
> AddMetadata is available only in .NET Core 3.0 right? But it shouldn't affect listener.
> Yes we are happy to accept a PR to make this enhancement.

Yes, .Net Core 3 only. But we can check for payload availability so we can make it backwards compatible.

I'll probably start working on it in the next few days.
