### ISSUE TITLE
Exceptions thrown when debugging

### ISSUE THREAD

**Issue by danpetitt** [microsoft/ApplicationInsights-dotnet-server#129]
We are having issues with the Microsoft.ApplicationInsights.PerfCounterCollector package causing exceptions on our dev boxes. The first one is:

```
System.InvalidOperationException occurred
Message: Exception thrown: 'System.InvalidOperationException' in System.dll
Additional information: Category does not exist.
```

Then if we click continue in the debugger we get:

```
System.InvalidOperationException occurred
Message: Exception thrown: 'System.InvalidOperationException' in System.dll
Additional information: Category does not exist. 
```

Both of these exceptions are very annoying as they are the type of exception we don't want to have to disable for obvious reasons.

I have reproduced the problem very easily:

**System Info:**

OS Name Microsoft Windows 10 Pro
Version 10.0.10586 Build 10586
Visual Studio:
Microsoft Visual Studio Professional 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01038
Installed Version: Professional

**Repro Steps:**
1. Create a Web MVC (including Web Api) project
2. Via nuget install "Microsoft.ApplicationInsights.Web v2.1.0"
3. Start debugging (F5)
4. Wait for a minute or two.
5. Results -> The two exceptions mentioned earlier

**Comment by abaranch** [comment]
It is a first chance exceptions, correct? Module throws that exceptions and than catches it.
I will mark it as enhancement to see whether we can improve experience by checking if category exists.

**Comment by lmolkova** [comment]
Note that FirstChangeExceptionModule is disabled by default now. 
Does not reproduce with ApplicationInsights Web SDK 2.10.0 even with FirstChanceException module on.
Please reopen if reproduces again.
