### ISSUE TITLE
Make PerformanceCounterUtility class as Public instead of Internal

### ISSUE THREAD

**Issue by AnithaL** [Microsoft/ApplicationInsights-dotnet-server#139]
Hi,
Can you please modify PerformanceCounterUtility class as Public so that we can use that class in my project and also all the methods inside that class also private and can you make all the methods as public.

Thanks you

**Comment by abaranch** [comment]
Sorry, but that is an internal implementation details that is not part of public API and which we cannot not commit to maintain in the future.
