### ISSUE TITLE
Can we configure EnableIISExpressPerformanceCounters using ApplicationInsights.Config 

### ISSUE THREAD

**Issue by AnithaL** [Microsoft/ApplicationInsights-dotnet-server#143]
Hi Team,
I need to set EnableIISExpressPerformanceCounters to true in my project, is there a way to set this in ApplicationInsights.Config  file.

**Comment by SergeyKanzhelev** [comment]
Error messagee explaining how to do it: https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/d69bd0e5f08766a9f045fbbe4bd42d984ed847d0/Src/PerformanceCollector/Shared/Implementation/PerformanceCollectorEventSource.cs#L88

``` xml
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule, Microsoft.AI.PerfCounterCollector">
      <EnableIISExpressPerformanceCounters >true</EnableIISExpressPerformanceCounters>
    </Add>
```

**Comment by user1568891** [comment]
I know this is old, but can you clarify where to put that Add element in the ApplicationInsights.Config file?

**Comment by SergeyKanzhelev** [comment]
Config file will be like this https://github.com/Glimpse/Glimpse.ApplicationInsights/blob/master/Glimpse.ApplicationInsights.Sample/ApplicationInsights.config#L38-L56 

Just put an extra node `<EnableIISExpressPerformanceCounters >true</EnableIISExpressPerformanceCounters>` inside the `<Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule, Microsoft.AI.PerfCounterCollector"></Add>`

**Comment by user1568891** [comment]
It worked - thankyou!
