### ISSUE TITLE
CPU counter should account for the number of processors

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#145]
When CPU counter reports 70% it may be that it only consumes 25% of all cores:

![untitled](https://cloud.githubusercontent.com/assets/9950081/18762884/b72a4eca-80bf-11e6-9673-c17566d5f090.png)
1.       Not normalized by a number of cores (=> perception that service is running hot)
2.       Showing CPU for w3wp only and not Total CPU (=> for non-w3wp issues like TLS reconnect issue this chart will show that everything is fine when in fact all instances will be running @ 100%)

![untitled](https://cloud.githubusercontent.com/assets/9950081/18762904/d429ed28-80bf-11e6-91e8-6d7e4048ea57.png)

So for the processoR counters we can report number of processors as metrics “weight” (denominator). Questions/work:
1.       Should we report value as a divided number or as a total number. It is the same answer as should have for any aggregated metric that VitalyF is working on.
2.       Should we allow reporting to report on either (total and devided) or only on devided metric
3.       We need to rename CPU counter to something like “machineCPU” instead of “\Processor(_Total)\% Processor Time” as it will not be a performance counter anymore – it will be something we calculated based on performance counter value

For the process CPU counter – I don’t know how counter works and we may need to devide it to the number affinite’s processors like explained here: http://stackoverflow.com/questions/188503/detecting-the-number-of-processors/189371#189371 Otherwise – all the above questions applies.

**Comment by SergeyKanzhelev** [comment]
This also should be handled for Live stream metrics.

For Azure Web Apps - the number of processors can be obtained using environment variable [NUMBER_OF_PROCESSORS](https://gist.github.com/sayedihashimi/831d8883cdf1d23823f3#file-_webjob-env-vars-txt-L33):

**Comment by cijothomas** [comment]
There may not be any need of SDK changes, as App Insights UI is going to be modified to:
1. Show Process CPU and Total Processor CPU by default on  Servers blade
2. Better describe the counters to make it explicit that Process CPU is not normalized.

However, it maybe a good value addition to send an additional metric indicating # of cores. UI can later show Process CPU adjusted for # of cores as a derived metric.

**Comment by cijothomas** [comment]
Closing this item.
Will open a new item for "Send additional metric ProcessCPUAdjusted".
