### ISSUE TITLE
Not able to inherit the PerformanceCollectorModule

### ISSUE THREAD

**Issue by AnithaL** [Microsoft/ApplicationInsights-dotnet-server#148]
In my project i need to inherit from PerformanceCollectorModule and need to override CollectionPeriod but i see PerformanceCollectorModule is sealed class, is there any way to change the CollectionPeriod .

**Comment by dnduffy** [comment]
This is essentially the same question thread as #142.
Please respond to Sergey there.
This is intended not to be configurable due to the load it would place on the system but we are open to hearing your business case.
