### ISSUE TITLE
Powershells not signed

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#150]
Powershells are not signed which causes problems with NuGets installation. See http://disq.us/p/1bytozt

>Just installed the AI tool. Going to watch it and see how it works. But in the meantime, wanted to share some info on the install experience. It did not go smoothly. Seems the Nuget packages are executing some scripts, etc., that are not being recognized as safe (Signed) and being rejected. This is on a fully patched Win10Pro desktop.
Quick search showed I could get around it by executing a few Powershell commands to downgrade the permissions to allow unsigned scripts to run. But there's another obstacle. "Set-ExecutionPolicy -Scope MachinePolicy Unrestricted" failed. I was told by a status message that it had to be done in the GP editor. So I opened the GP editor and saw no sections or properties that seemed to be related to PS. Searched some more and eventually found that I needed to install a Powershell Addon to get access to these properties. Installed the Addon from the msft website, found the new properties in the menu, changed to allow unsigned, rebooted, and AI finally installed.
This took a couple hours to understand the problem. identify the solution, and resolve it. The AI team needs to add this in the instructions. Also, why are your nugget packages being treated as dangerous by Windows10???

**Comment by abaranch** [comment]
WindowsServer nuget ps1 will be signed in the next version which will be out in the next couple of days. 
We can keep bug open till we Intercept nuget is fixed and updated.

**Comment by abaranch** [comment]
Fixed in 2.2.0-beta2 which is published today
