### ISSUE TITLE
Servers View shows aggregate across PROD and STAGE role instances

### ISSUE THREAD

**Issue by zakimaksyutov** [Microsoft/ApplicationInsights-dotnet-server#167]
RoleInstance is populated with "<RoleName>_IN_<#instance>" and it is the same in PROD/STAGE/other deployments. As a result Servers View shows aggregate across PROD RoleName_IN_0 and STAGE RoleName_IN_0. Which does not make much sense :)

**Comment by AlexBulankou** [comment]
Supporting SLOTs would be an enhancement and I don't think there's an easy way to identify slots programmatically. [Here's the only way I could find](http://gauravmantri.com/2012/03/16/programmatically-finding-deployment-slot-from-code-running-in-windows-azure/). Based on this customer can write a telemetry initializer that would set the slot correctly.

**Comment by SergeyKanzhelev** [comment]
The best way to distinguish slots for Cloud Services is to group telemetry by IP. This query works:
```
let interval = 1d;
performanceCounters
| where timestamp >= ago(interval)
| where name == "Requests/Sec" 
| extend instance = strcat(cloud_RoleInstance, " ", client_IP)
| summarize instanceAvg=avg(value) by bin(timestamp, 5m), instance
| summarize instanceAvg=avg(value) by bin(timestamp, 5m)
| render areachart
```

Applying [reverse DNS lookup](https://azure.microsoft.com/en-us/blog/announcing-reverse-dns-for-azure-cloud-services/) can make data human-friendly.

So the best solution would be to let SDK specify roleInstance name which will be updated with the incoming IP address (or reverse looked-up IP address). Something like `ROLE_IN_0 {location.ip}` that will be replaced by actual ip on Application Insights Endpoint

**Comment by Dmitry-Matveev** [comment]
Cloud Services V1 are not the main focus at the moment, closing the issue for now. We can open a follow up for stamps differentiation discussion.
