### ISSUE TITLE
Add Request and Response Data

### ISSUE THREAD

**Issue by itsyashpal** [Microsoft/ApplicationInsights-dotnet-server#174]
As of now it logs request duration , method name and result code.  If it can give option to log the request and response it will be easier to track specially in case excetions

**Comment by SergeyKanzhelev** [comment]
You can always report exception information using `TrackException` call. It will be correlated with the corresponding request - you'll see it in related items alongside dependency calls (http, sql, etc.), traces and events. 

If you need to collect response information can always write telemetry initializer that will send it as a custom property of the request. 

Let me know if you need help and more pointers on how to implement it.

**Comment by dnduffy** [comment]
If you have more data than will fit in a custom property it is my understanding that you can make a TrackTrace call of up to 32K.
