### ISSUE TITLE
Improve InvalidOperationException messages in XXXTelemetryModule classes

### ISSUE THREAD

**Issue by WernerMairl** [Microsoft/ApplicationInsights-dotnet-server#188]
There are a lot of methdos in xxxTelemetryModule classes where the first code block looks like thw following

if (this.telemetryClient == null)
            {
                throw new InvalidOperationException();
            }

Basically this exception is thrown if the Initialize() Method was not called.

I run into this case and it takes hours to find the real reason (the exception message does NOT helps)
In the exception logs/Diagnostics outputs i see only the following wording:

"System.InvalidOperationException: Operation is not valid due to the current state of the object"

please improve the exception message!
suggestions:

- at leaste the state name should be part of the message (Telemetry client)
- in this usecase a hint to the Inintialize call can also be helpful......

regards
Werner

PS.: sorry for my language difficults...

**Comment by SergeyKanzhelev** [comment]
@WernerMairl, this is a great suggestion!

**Comment by dnduffy** [comment]
I'll improve it for beta-4.

**Comment by dnduffy** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/192
