### ISSUE TITLE
Improvement Suggestion for WebTelemetryInitializerBase

### ISSUE THREAD

**Issue by WernerMairl** [Microsoft/ApplicationInsights-dotnet-server#191]
The class Microsoft.ApplicationInsights.Web.Implementation.WebTelemetryInitializerBase can be really helpful for writing my own Initializers.

The class is public and abstract => perfect for using inheritance
The Constructor (no arguments) is INTERNAL => this PREVENTS any inheritance!!!

Requirement: provide a way where anyone can implement the method "protected abstract void OnInitializeTelemetry(...)" and use the provided method-arguments

suggest:
solution #1: declare the constructor as public
solution #2: implement a new class (that inherits from WebTelemetryInitializerBase) with a event/delegate that allows to inject code into OnInitializeTelemetry 

regards
Werner

**Comment by SergeyKanzhelev** [comment]
what features of `WebTelemetryInitializerBase` are you interested in the most? Tracing of error or getting the current context?

If you just need to take the request telemetry from the current context - use [this](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/f26fef6e05027a09d259fa560d372b902f9b7219/Src/Web/Web.Shared.Net/HttpContextExtension.cs#L17) extension method: 

``` csharp
var requestTelemetry = HttpContext.Current.GetRequestTelemetry();
```

**Comment by WernerMairl** [comment]
Hi Sergey

>what features of WebTelemetryInitializerBase are you interested in the most? Tracing of error or getting the current context?

Good question!

1. the considerd extension allows me to (re) implement everything i need without inheritance => thank you => issue can be closed!

2. re-using the exception logging implemented inside the WebTelemetryInitializerBase CAN be very helpful but it is not my current task/requirement

thanks
Werner

**Comment by SergeyKanzhelev** [comment]
Thanks for asking and reporting this anyway! We appreciate your feedback
