### ISSUE TITLE
Application crash in PerformanceCollectorModule with high CPU utilization.

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-dotnet-server#203]
Under high CPU utilization the w3wp.exe worker process gets restarted and during that time gets 502 bad gateway errors.  The web app crashes with Access Violation error code: C0000005

Per investigation by the Azure App Service team there was a GC heap corruption caused by AI.

.NET Call Stack

`Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCollector.RegisterPerformanceCounter(System.String, System.String, System.String, System.String, System.String, Boolean, Boolean)+e9 
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCollector.RefreshPerformanceCounter(Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCounterData, System.Diagnostics.PerformanceCounter)+62 
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule.RefreshCounter(Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCounterData, System.Collections.Generic.IEnumerable`1, System.Collections.Generic.IEnumerable`1)+45 
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule+<>c__DisplayClass29_0.b__1(Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCounterData)+16 
System.Collections.Generic.List`1[[System.__Canon, mscorlib]].ForEach(System.Action`1)+c2 
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule.RefreshCounters(System.Collections.Generic.IEnumerable`1, System.Collections.Generic.IEnumerable`1)+d2 
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule.EnsurePerformanceCountersRegistered()+332 
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule.TimerCallback(System.Object)+7b 
System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)+31 
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+108 
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+17 
System.Threading.TimerQueueTimer.CallCallback()+10e 
System.Threading.TimerQueueTimer.Fire()+cc 
System.Threading.TimerQueue.FireNextTimers()+133 
System.Threading.TimerQueue.AppDomainTimerCallback()+22 
[[DebuggerU2MCatchHandlerFrame]] 
[[ContextTransitionFrame]] 
[[DebuggerU2MCatchHandlerFrame]] 
`

Full Call Stack

`Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCollector.RegisterPerformanceCounter(System.String, System.String, System.String, System.String, System.String, Boolean, Boolean)+e9     0000000     0000001     0000000     4cbbc94    
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCollector.RefreshPerformanceCounter(Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCounterData, System.Diagnostics.PerformanceCounter)+62     4cbb9bc     4cbb9bc     0000001     0000000    
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCollector.RefreshPerformanceCounter(Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCounterData, System.Diagnostics.PerformanceCounter)+62     0000000     0000000     0000000     0000000    
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule.RefreshCounter(Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCounterData, System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<System.String>)+45     4cbb7e8     4cab2b8     4cbb854     362e9d2    
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule.RefreshCounter(Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCounterData, System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<System.String>)+45     0000000     0000000     0000000     0000000    
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule+<>c__DisplayClass29_0.<RefreshCounters>b__1(Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCounterData)+16     6749fc8     0000000     89556e2     8d40318    
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule+<>c__DisplayClass29_0.<RefreshCounters>b__1(Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCounterData)+16     0000000     0000000     0000000     0000000    
System.Collections.Generic.List`1[[System.__Canon, mscorlib]].ForEach(System.Action`1<System.__Canon>)+c2     0000000     0000000     0000000     0000000    
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule.RefreshCounters(System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<System.String>)+d2     4cbb7e8     e76935c     00005f1     4a0ecdc    
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule.EnsurePerformanceCountersRegistered()+332     0000000     e70b7b8     0000000     0000000    
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule.EnsurePerformanceCountersRegistered()+332     0000000     0000000     0000000     0000000    
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule.TimerCallback(System.Object)+7b     11abe50     6837b74     a6e633c     0000000    
System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)+31     0393080     4a0eee8     3a3944f     4a0ef28    
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+108     0000000     0000000     0000000     0000000    
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+17     0000000     0000000     0000000     0000000    
System.Threading.TimerQueueTimer.CallCallback()+10e     0000000     0000000     0000000     0000000    
System.Threading.TimerQueueTimer.Fire()+cc     0000000     0000000     0000000     0000000    
System.Threading.TimerQueue.FireNextTimers()+133     0000000     0000000     0000000     0000000    
System.Threading.TimerQueue.AppDomainTimerCallback()+22     0000000     0000000     0000000     0000000    
clr!CallDescrWorkerInternal+34     4a0ef28     4a0eed8     3bc2510     4a0f0a8    
clr!CallDescrWorkerWithHandler+6b     0000004     4a0ef10     3a39399     4a0ef0c    
clr!MethodDescCallSite::CallTargetWorker+16a     0000000     bf1f748     1ce41d0     1eb4010    
clr!AppDomainTimerCallback_Worker+21     0000000     0393080     4a0f2e8     4a0f08c    
clr!ManagedThreadBase_DispatchInner+71     d5cbb8d     4a0f2e8     0000000     0000000    
clr!ManagedThreadBase_DispatchMiddle+7e     d5cbbe9     0393080     4a0f2e8     0000000    
clr!ManagedThreadBase_DispatchOuter+5b     0393080     4a0f1c0     3b15c31     4a0f2e8    
[[DebuggerU2MCatchHandlerFrame]]     0000000     0000000     0000000     0000000    
clr!ManagedThreadBase_DispatchInCorrectAD+15     4a0f2e8     d5cbac1     4a0f2a0     4a0f2e8    
clr!Thread::DoADCallBack+328     0000002     3b15c80     4a0f2e8     0000000    
[[ContextTransitionFrame]]     0000000     0000000     0000000     0000000    
clr!ManagedThreadBase_DispatchInner+4e     d5cb985     4a0f2e8     0000000     0476f48    
clr!ManagedThreadBase_DispatchMiddle+7e     d5cb9e1     0000001     0393080     0476f48    
clr!ManagedThreadBase_DispatchOuter+5b     0000002     0000000     0000001     3b15640    
[[DebuggerU2MCatchHandlerFrame]]     0000000     0000000     0000000     0000000    
clr!ManagedThreadBase_FullTransitionWithAD+2f     0000002     0000004     d5cb819     d51bb80    
clr!AppDomainTimerCallback+93     d55ae30     0000001     d5cb859     4088390    
clr!ThreadpoolMgr::AsyncTimerCallbackCompletion+9e     d51bb80     d5cb889     4088390     3b151c0    
clr!UnManagedPerAppDomainTPCount::DispatchWorkItem+1cf     4a0f3f5     4a0f3f7     0393080     02a002a    
clr!ThreadpoolMgr::ExecuteWorkRequest+4f     0000000     0000000     0f36c88     4a0f5d8    
clr!Thread::intermediateThreadProc+55     414a2a0     4a0fb2c     70e9e89     414a2a0    
kernel32!BaseThreadInitThunk+e     414a2a0     d43df4d     0000000     0000000    
ntdll!__RtlUserThreadStart+72     3b14920     414a2a0     fffffff     7161dd2    
ntdll!_RtlUserThreadStart+1b     3b14920     414a2a0     0000000     0000000    
`

**Comment by cijothomas** [comment]
This was before the new way of reading perf counters right? Do we need to fix this for older SDK versions?

**Comment by dnduffy** [comment]
You can't fix older SDK versions, they've already been released.

**Comment by SergeyKanzhelev** [comment]
Is there a stable SDK with the new way of reading counters yet?

**Comment by dnduffy** [comment]
The performance counter changes that were released in 2.2.0 make this irrelevant now.
