### ISSUE TITLE
Missing Service Bus dependency telemetry

### ISSUE THREAD

**Issue by RickKra** [Microsoft/ApplicationInsights-dotnet-server#208]
I have a WebAPI app that uses Table Storage and Service Bus. For most of the REST calls I see AI dependency data for it. For example, when I use `Microsoft.ServiceBus.Messaging.TopicClient.Send()`, I can see it in telemetry. But when I use `Microsoft.ServiceBus.Messaging.SubscriptionClient.Receive()`, I see only the calls to Table Storage.

I removed the sampling processor from my `ApplicationInsights.config` so I don’t expect it’s that.

I’m using version 3.4.0 of WindowsAzure.ServiceBus and version 2.1.0 of most of the AI packages:

``` xml
<package id="Microsoft.ApplicationInsights" version="2.1.0" targetFramework="net46" />
<package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.0.1" targetFramework="net46" />
<package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.1.0" targetFramework="net46" />
<package id="Microsoft.ApplicationInsights.JavaScript" version="0.22.19-build00125" targetFramework="net46" />
<package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.1.0" targetFramework="net46" />
<package id="Microsoft.ApplicationInsights.TraceListener" version="2.1.0" targetFramework="net46" />
<package id="Microsoft.ApplicationInsights.Web" version="2.1.0" targetFramework="net46" />
<package id="Microsoft.ApplicationInsights.WindowsServer" version="2.1.0" targetFramework="net46" />
<package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.1.0" targetFramework="net46" />
```

**Comment by SergeyKanzhelev** [comment]
Do you see http calls in fiddler on `Receive` call?

**Comment by RickKra** [comment]
I don’t know how to set up fiddler on an Azure WebAPI sight. Can you provide instructions?

Thanks,
Rick

**Comment by SergeyKanzhelev** [comment]
Does it only report in Azure Web API environment? Does it work as expected locally?

Second question, when you look at dependency event - can you please expand all properties and tell what is the sdkVersion being reported? We need to know whether it has `rddf` or `rddp` prefix.

**Comment by RickKra** [comment]
Inline below…

Thanks,
Rick

**Comment by SergeyKanzhelev** [comment]
If it repro's locally - can you check with fiddler that you in fact see some http call that Application Insights didn't track?

**Comment by RickKra** [comment]
I did not see the call in fiddler. I can see the call for Microsoft.ServiceBus.Messaging.TopicClient.Send(), but not for Microsoft.ServiceBus.Messaging.SubscriptionClient.Peek() or Microsoft.ServiceBus.Messaging.SubscriptionClient.Receive().

Thanks,
Rick

**Comment by SergeyKanzhelev** [comment]
So there are no call and Application Insights didn't collect it. What behavior would you expect? Does `Receive` call takes much time typically? If so - do you know where the time got spent?

**Comment by RickKra** [comment]
Sorry, I didn’t realize that Service Bus isn’t using https for these calls, since it does use it for other calls.

I would expect it to get tracked somehow, but maybe that’s on the Service Bus team to switch to https for those calls?

Thanks,
Rick

**Comment by SergeyKanzhelev** [comment]
Do you know what transport Service Bus is using for `Receive`?

**Comment by RickKra** [comment]
I do not.

Thanks,
Rick

**Comment by snboisen** [comment]
According to [the docs](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements), Service Bus can use three kinds of transport:

1. AMQP
2. SBMP
3. HTTP

I believe SBMP is default for the .NET SDK. AMQP can be enabled by appending "TransportType=Amqp" to the connection string. Both SBMP and AMQP transports are persistent in the sense that they maintain the connection to Azure Service Bus as long as the factory and client objects are used correctly.

So it is not clear how Application Insights could track these dependencies automatically.

**Comment by SergeyKanzhelev** [comment]
@snboisen - dependency collector package collects http and sql dependencies out of the box. For http dependencies we have a logic to bucket those into Azure Storage vs. regular http. 

For other protocols we will likely need a separate dependency collection NuGet package that will hook into Azure SDK extensibility points. We do not have it yet.

**Comment by pharring** [comment]
I wouldn't do this at the protocol level. I would do this in the Service Bus SDK. The recommendation from the Service Bus team is to shuttle request/operation context in the ```Properties``` dictionary of a ```BrokeredMessage```. I don't think we want the Service Bus SDK to take a dependency on Application Insights, but I do think we could create a bridging component (think of it as Microsoft.ApplicationInsights.ServiceBusExtensions) by adding initializer-style callbacks to the Service Bus SDK.

**Comment by TomMilos** [comment]
ServiceBus telemetry collection is supported starting from [ServiceBus SDK 3.0.0-preview-01](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/3.0.0-preview-01) and [ApplicationInsights SDK 2.5.0-beta2](https://www.nuget.org/packages/Microsoft.ApplicationInsights.DependencyCollector/2.5.0-beta2). Both SDKs need to be present in these versions or newer
