### ISSUE TITLE
Proper correlation with availability results

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#218]
Today we are storing correlation information from the Application Insights Availability tests into `User.Id` and `Session.Id` context fields. Those fields were used due to some internal reasons at the moment of implementation. This needs to be changed to align with all other correlation techniques.

``` csharp
// User id will be Pop location name and RunId (We cannot use just location because of sampling)
telemetry.Context.User.Id = locationHeader + "_" + runIdHeader;
telemetry.Context.Session.Id = runIdHeader;
```

There are two options - keep using custom headers and change the logic how those headers are used. Alternatively - talk to Availability Tests team to change headers to `x-ms-request-id` and `x-ms-request-root-id` as well as `x-ms-request-source-ikey` to allow components correlation.

Proper correlation should do:
1. Use `telemetry.Context.Operaiton.Id` to store test run id instead of session ID
2. Use custom property to store POP location instead of user ID.

Need coordination with Availability Tests team:
1. Components correlation when/if possible. Populate Request.Source field from the headers passed by Availability Tests
2. Use test step ID (for multi-step tests) with `telemetry.Context.Operation.ParentId`

**Comment by MS-TimothyMothra** [comment]
@iusafaro any update?

**Comment by iusafaro** [comment]
GSM pop agents send now Request-Id and Request-Context headers with operation Id and app Id correspondingly. Request-Id has its own value for each web step and that allows correctly map server request to web step from the web test result. 

Old headers are preserved for backward compatibility and can be safely removed later when we'll decide that we don't support them anymore.
