### ISSUE TITLE
Diagnostics telemetry module lost after the update

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#220]
After updating the SDK to `2.2.0-beta4` configuration file `ApplicationInsights.config` missing the diagnostics telemetry module:

``` xml
<Add Type="Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule, Microsoft.ApplicationInsights"/>
```

From the first glance it may be due to the missing `xdt:Transform="InsertIfMissing"` on it in [transformation file](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/75373e57dcf8d646c54ee188461c373f2cc98939/Src/WindowsServer/WindowsServer.Nuget/ApplicationInsights.config.install.xdt#L15).

**Comment by kartang** [comment]
From the related comments, I understood that we have decided not to add DiagnosticsTelemetryModule by default with the installation, which is why we removed it (if exists) from the list of the modules. Please let me know if this is not an expected behavior.

**Comment by SergeyKanzhelev** [comment]
Which comments do you refer to?

**Comment by kartang** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/WindowsServer/WindowsServer.Nuget.Tests/TelemetryModulesTests.cs#L14

**Comment by SergeyKanzhelev** [comment]
Do you know why? Do we keep sending diagnostics messages without the module?

**Comment by kartang** [comment]
I am not sure why we made that change. I don't have enough context around that. Events are sent irrespective of the module being registered. DiagnosticsModule registers a listener and captures the events, and sends them to multiple outputs. May be we have decided to leave the option to customers, to use their custom diagnostic listeners?

**Comment by SergeyKanzhelev** [comment]
@AlexBulankou do you know the history here?

**Comment by cijothomas** [comment]
The basesdk adds diagnostictelemetrymodule by default.
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Core/Managed/Net40/Extensibility/Implementation/TelemetryConfigurationFactory.cs#L56


Also, if AI.config also specifies the same module, then it takes preference as it overrides the defautly added module. (So if one want to change the diagnostic module to listen Verbose event, simply configure so in Ai.config and it'll be respected)

To avoid the confusion, will remove the mention of diagnosticsmodules at all from transaformation file.

**Comment by cijothomas** [comment]
Closing this issue, as there is no issue about diagnostic telemetry missing - its added by default in basesdk.
The pr is for some cleanup only.
