### ISSUE TITLE
SDK Perfruns show heavy memory usage

### ISSUE THREAD

**Issue by cijothomas** [Microsoft/ApplicationInsights-dotnet-server#227]
Recent perf run using an Empty App (instrumented with sdk, no sdk) indicates some memory leak. Without instrumentation, the total memory was ~5MB, which shot up to ~450MB after adding application insights web sdk.
Similar tests done over an AverageAI Customer app shows only ~34% increase in memory. (138MB to 186MB)

This need to be investigated.

**Comment by SergeyKanzhelev** [comment]
Please note, that latest CLR GC algorithms may pre-allocate a lot of memory and only use a small portion of it. From windows perspective it will look like a memory leak. But from CLR counters perspective the grows will not be significant.

I agree that it needs investigation

**Comment by cijothomas** [comment]
Verified that after the remove sanitize() memory use was substantially lowered, and also modify the perf run to force a GC once a min, which reclaimed all unused memory.
THis issue is now considered closed.
