### ISSUE TITLE
Feature discovery incredibly hard.

### ISSUE THREAD

**Issue by nizarq** [Microsoft/ApplicationInsights-dotnet-server#230]
It came up while talking to someone who is an active user of application insights that they had a lot of custom logic to add custom fields to telemetry they send. It turns out that TelemetryProcessors is a supported way of doing the same (making custom additions). This is a frustration that I myself share. It is incredibly hard to know what you could put in the configuration file and what might the purpose of that be. 

I adding a schema to visual studio for application insights config, that would power intelliscense, will go a long way here. That would not only help with users find new features by playing with the config, but would also help with not having to search for examples of doing something simple like specifying an instrumentation key, figure out errors in the config etc.

**Comment by drwill-ms** [comment]
Ideally for me, I'd be able to set some custom properties at initialization time that any instance of the logger automatically included. This is especially important for when AI logs on my application's behalf (catch an exception, dependencies, requests). It isn't obvious from the API how to do this, and the current solution seems more complicated than I think it needs to be to do what I want to do.

**Comment by SergeyKanzhelev** [comment]
Just to be clear this is what it takes to initialize global properties:


``` csharp
class StubTelemetryInitializer : ITelemetryInitializer
{
  public Action<ITelemetry> OnInitialize = item => { };
  public void Initialize(ITelemetry telemetry)
  {
    this.OnInitialize(telemetry);
  }
}

TelemetryConfiguraiton.Active.TelemetryInitializers.Add(new StubTelemetryInitializer() { OnInitialize = (item) => {item.Context.Properties["a"] = "b"}; );

TelemetryConfiguraiton.Active.TelemetryInitializers.Add(new StubTelemetryInitializer() { OnInitialize = (item) => {item.Context.Component.Version = "3.14"}; );
```

Which part do you think needs simplification? Will it help to have `Context` on `TelemetryConfiguration.Active`?
