### ISSUE TITLE
PerformanceCollectorModule error message about InitialCounter read is incorrect

### ISSUE THREAD

**Issue by cijothomas** [Microsoft/ApplicationInsights-dotnet-server#238]
eg: Error collecting 2 out of 0 configured performance counters.  Thi

The total counter is always zero in default config, as its obtained from this.Counters.Count. 
(I think it should be sum of this.Counters.Count+this.DefaultCounters.Count ?

Since this error message is considered a UserActionable, the message should not print any incorrect information.

**Comment by dnduffy** [comment]
For 2.2.0 stable I propose that we simplify the message to remove the second variable rather than spend time trying to make sure we're always getting an expected total count.  We can do the more detailed message again for 2.3.0 if still desired.

**Comment by dnduffy** [comment]
PR for 2.2.0 simple fix: https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/239

**Comment by dnduffy** [comment]
Show counter names for easier investigation.

**Comment by cijothomas** [comment]
David has fixed this via: https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/292
closing.
