### ISSUE TITLE
Profiler stops collecting dependencies in multi-app domain same apppool apps.

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#247]
This is from master:
http://ai-glimpse-web-play-staging.azurewebsites.net/

This is from develop:
http://ai-glimpse-web-play-develop.azurewebsites.net/

PR: https://github.com/Glimpse/Glimpse.ApplicationInsights/pull/45 

After upgrade to beta6 SQL dependencies are not being collected

**Comment by SergeyKanzhelev** [comment]
Looked at it with @cijothomas - it seems only be not collected when using profiler (Azure Web App extension)

**Comment by cijothomas** [comment]
In the test app i used, adding profile via Azure web app extension stopped both SQL and HTTP Dependencies.

**Comment by cijothomas** [comment]
Not reproed for local apps. So far this is reproed only in Azure WebApp.

**Comment by cijothomas** [comment]
From the azure webapp, this AI (Internal): [msg=RemoteDependencyModule information.];[msg=AgentVersion is 0.13.0]

**Comment by SergeyKanzhelev** [comment]
@cijothomas so profiler was loaded. Did it load Intercept extension successfully?

**Comment by dnduffy** [comment]
I created a new application, published it to Azure for the first time, added the extension, and started making requests.
All dependencies were always correctly captured and reported.

**Comment by dnduffy** [comment]
From in office conversations it seems that all repro's disappear once the app pool has been recycled once.
So if anyone does run into this the fix is simply to restart the web app one time.

**Comment by SergeyKanzhelev** [comment]
It reproed on three separate environments. What's the plan to investigate it further?

**Comment by cijothomas** [comment]
Changed title to reflect the issue:
Profiler stops collecting dependencies in multi-app domain same apppool apps.

**Comment by SergeyKanzhelev** [comment]
@cijothomas [these tests](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Test/DependencyCollector/FunctionalTests/FuncTest/HttpTests.cs) are working with the full IIS. It will be great if you can add a test there that validates multiple the multiple domains case
