### ISSUE TITLE
Test azure storage and correlation

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#265]
We need to add a test to ensure that correlation headers works fine with azure storage requests signing. It is failing for [node.js](https://github.com/Microsoft/ApplicationInsights-node.js/issues/143)

From a look at the code [here](https://github.com/Azure/azure-storage-net/blob/68c3ee55a3a6f62a0159cea58005d3fe027312a8/Lib/ClassLibraryCommon/Core/Auth/SharedKeyCanonicalizer.cs#L73) and [here](https://github.com/Azure/azure-storage-net/blob/68c3ee55a3a6f62a0159cea58005d3fe027312a8/Lib/Common/Core/Util/AuthenticationUtility.cs#L212) it seems that injection should fail such requests:

The only possibility when it will not break is if .NET SDK is using `SharedKeyLite` [authentication](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/Authentication-for-the-Azure-Storage-Services?redirectedfrom=MSDN#a-namesubheading2a-specifying-the-authorization-header)

**Comment by SergeyKanzhelev** [comment]
Need to validate whether it will break full authentication and make sure our injection logic works nicely with it

**Comment by cijothomas** [comment]
Haven't tested this, and to play safe, all azure storage calls are automatically excluded.

**Comment by SergeyKanzhelev** [comment]
I think this is fixed. Closing
