### ISSUE TITLE
Error trace generated for invalid performance counters in the config needs to be improved

### ISSUE THREAD

**Issue by nizarq** [Microsoft/ApplicationInsights-dotnet-server#275]
1. Add the following lines to the applicationinsights.config
![attachfilehandler](https://cloud.githubusercontent.com/assets/9325338/21275886/b374ad32-c383-11e6-8e29-f8ca1a895b02.png)
2. Run the application under local IIS.
3. Go to the portal and notice the following trace event. The message should be more informative, at the very least, notifying the user which counters / configurations are invalid.
![attachfilehandler2](https://cloud.githubusercontent.com/assets/9325338/21275885/b36c840e-c383-11e6-9aec-1e4b2dba441d.png)

**Comment by cijothomas** [comment]
Fixed via https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/292
closing.
