### ISSUE TITLE
[Cross Component Correlation] When multiple service write the same AI resources dependencies should not be logged as cross component dependencies

### ISSUE THREAD

**Issue by nizarq** [Microsoft/ApplicationInsights-dotnet-server#276]
Since source / target ikey hashes are added through headers between http calls, currently the logic for recording dependencies / requests along with cross component information, does not distinguish whether or not the calls are make across AI component boundaries. 

We should only add cross component information, if the calls are made / received from an external component (AI resources).

**Comment by SergeyKanzhelev** [comment]
I think it will be great to show self reference. Even better if http header will also include `roleName` and `roleinstance` so application map can show cross-roles correlation.

I agree that we need to put some thoughts how to handle this case

**Comment by nizarq** [comment]
Yes, I was talking to Dan on how we might go about extending this to correlation for services within a single IKey. We had the same idea as to eventually extend the headers and possibly source / target fields to contain role and instance identities as well. For now though, in the absence of that information, given how we show dependencies on the map, best is to not treat them as special AI dependencies.

**Comment by nizarq** [comment]
Pull request submitted for the issue.
https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/278

**Comment by SergeyKanzhelev** [comment]
Let's not make any special casing for this. If service calls to itself - let's report it and make UI worry about understanding this.
