### ISSUE TITLE
RDD path is stripped by backend

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet-server#284]
SDK is logging the following RDD

Application Insights Telemetry: {
"name":"Microsoft.ApplicationInsights.***.RemoteDependency",
"time":"2016-12-29T19:07:31.0574247Z",
"iKey":"***",
"tags":{
"ai.operation.parentId":"d93zwpr6ENI=",
"ai.session.id":"Zgt5C",
"ai.operation.id":"d93zwpr6ENI=",
"ai.operation.name":"GET Home/Stock",
"ai.location.ip":"::1",
"ai.internal.agentVersion":"0.13.0",
"ai.cloud.roleInstance":"albulank-lptp31",
"ai.user.id":"l24BC",
"ai.internal.nodeName":"albulank-lptp31",
"ai.internal.sdkVersion":"rddp:2.3.0-791"},
"data":{"baseType":"RemoteDependencyData",
"baseData":{"ver":2,"name":"GET /",
"id":"jNWYO0d3tzg=",
"data":"http://localhost:24001/?stock=amzn",
"duration":"00:00:00.6180000","resultCode":"200","success":true,"type":"Http","target":"localhost"}}}

Note that data.baseData.data is http://localhost:24001/?stock=amzn

However in Analytics and Ibiza I see data becoming just GET /
Expected: Path is GET http://localhost:24001/?stock=amzn

(originally logged https://github.com/AlexBulankou/ai-talk1/issues/25)

**Comment by SergeyKanzhelev** [comment]
I assume Ibiza and analytics shows the name of the resource. You can access URL by opening this dependency call or querying `data` field in analytics.

Is it a dup for https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/202 and you want a better name than `/`? Suggestions?

**Comment by AlexBulankou** [comment]
This was fixed in ingestion service.
