### ISSUE TITLE
Need to respect settings to not set request headers when setting requests correlation headers

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#287]
This [line](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/bf913ac57b981faa38a6b74dd3461b4cda2dc4d1/Src/DependencyCollector/Shared/Implementation/ProfilerHttpProcessing.cs#L291) should be further down. Seems like a bad merge of two PRs.

**Comment by SergeyKanzhelev** [comment]
This issue was discovered after report of a problem from the customer. Specifically for queue service. Since we've tested and didn't repo it with the standard Azure Storage SDK - I wonder what SDK was used to hit the issue.

**Comment by beufordy3k** [comment]
@SergeyKanzhelev, it was with Application Insights 2.1.3 site extension on one instance and 2.2.0 on another.

In both cases, the latest preview version was used by the site 2.3.0-beta1. It looks like the introduction of 2.3.0-beta1 caused the Site Extension (2.1.3 and 2.2.0 versions) to suddenly start sending the correlation header?

**Comment by SergeyKanzhelev** [comment]
Yes, that's correct. A combination of 2.3.0-beta1 and site extensions enables correlation headers injection. 

I wonder - how do you query azure queue REST API? Do you construct http requests manually or use Azure Storage SDK?

**Comment by beufordy3k** [comment]
Correct, we are using the SDK to drop a message in a queue, not manually generating the message.

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/288 This PR should have fixed this, closing.
