### ISSUE TITLE
Also target HttpContextBase in HttpContextExtension extension methods

### ISSUE THREAD

**Issue by snboisen** [Microsoft/ApplicationInsights-dotnet-server#294]
A long time ago, there was only HttpContext, which was not mockable and so developers cried in anguish. Then came .NET 3.5 and with it HttpContextBase and HttpContextWrapper which opened the context up to mocking and there was much rejoicing.

Anyway, AFAIK using HttpContext.Current is not recommended under ASP.NET MVC and WebApi. If we absolutely need to access it, it should be done using `request.Properties["MS_HttpContext"]`. The issue here is that this place holds an instance of HttpContextWrapper and HttpContextWrapper does not allow access to the wrapped HttpContext. Therefore the provided extension method `GetRequestTelemetry` in [HttpContextExtension](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/Web/Web.Shared.Net/HttpContextExtension.cs) is useless when accessing the context in this way.

It would be nice to have the current and future methods here available for HttpContextBase.

**Comment by dnduffy** [comment]
The extension method will take whatever HttpContext you pass it, where you get the HttpContext instance from is not relevant to the extension method.
As for getting it in MVC 5 and older, you can still get HttpContext.Current in a controller action but you need to be aware that if you don't qualify it with System.Web.HttpContext.Current it will instead resolve to a local property on the controller with the same name but of type HttpContextBase.
In MVC 6 I have read that Current was removed but I believe you can get it from HttpContextAccessor.HttpContext or with "ContextBase.Current as HttpContext".
Please feel free to reactive and provide more information if this doesn't work for you.

**Comment by snboisen** [comment]
I am writing a pure ASP.NET WebAPI 2 webservice (no MVC). I don't seem to have access to `HttpContextAccessor` or `ContextBase`? `HttpContextBase` does not have a `Current` property.

So as I understand it, the only way I can to `HttpContext` in WebAPI is through `HttpContext.Current`?

**Comment by SergeyKanzhelev** [comment]
I think it make sense to create another extension for `HttpContextBase`. We can/should also use it internally to simplify the way we create http context for tests [here](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/75373e57dcf8d646c54ee188461c373f2cc98939/Src/Web/Web.Shared.Net.Tests/Helpers/HttpModuleHelper.cs#L80). The only consideration if we will decide to use it internally is how performant it will be to create wrapper every time we want to access properties of `HttpContext.Current`

I found nice short article explaining the differences [here](http://www.splinter.com.au/httpcontext-vs-httpcontextbase-vs-httpcontext/).

**Comment by SergeyKanzhelev** [comment]
@snboisen feel free to send a PR if you'd like to contribute

**Comment by iusafaro** [comment]
GetRequestTelemetry extension method for HttpContextBase is implemented and will be a part of 2.4.0-beta1 SDK release.
