### ISSUE TITLE
Request Set as Failed when using RedirectToAction in Controller

### ISSUE THREAD

**Issue by mesuttalebi** [Microsoft/ApplicationInsights-dotnet-server#301]
When ever I use RedirectToAction App Insights says request is failed.

![image](https://cloud.githubusercontent.com/assets/3634757/22407292/794ba4f6-e66c-11e6-9442-6a86bf5df4c2.png)

the below is detail for request:

```
{
  "name": "Microsoft.ApplicationInsights.Dev.Request",
  "time": "2017-01-29T19:42:22.4587546Z",
  "tags": {
    "ai.internal.sdkVersion": "web:2.2.0-738",
    "ai.operation.id": "aKLiKC/s7Wg=",
    "ai.location.ip": "::1",
    "ai.cloud.roleInstance": "Mesut-PC",
    "ai.operation.name": "POST Home/Create"
  },
  "data": {
    "baseType": "RequestData",
    "baseData": {
      "ver": 2,
      "id": "aKLiKC/s7Wg=",
      "name": "POST Home/Create",
      "duration": "00:00:00.0140000",
      "success": true,
      "responseCode": "302",
      "url": "http://localhost:48313/Home/Create",
      "properties": {
        "DeveloperMode": "true"
      }
    }
  }
}
```

**Comment by SergeyKanzhelev** [comment]
@gardnerjr can you take a look? Request is marked as `"success": true` and seems to be shown as failed. VS should respect `success` field. See [this](http://apmtips.com/blog/2016/12/03/request-success-and-response-code/) on how one can override the notion of success.

**Comment by gardnerjr** [comment]
Found what it is.  is very specific to local debug CodeLens, in one place it has a hardcoded check for "200" instead of looking for success field.

Bug 890173: [codelens] all local requests that are not 200 are considered failed by codelens

in our repo.

**Comment by SergeyKanzhelev** [comment]
@mesuttalebi thanks for reporting. I'm closing this bug here - it will be tracked internally for Visual Studio extension. Feel free to comment/re-open if you need more information on the issue or has other comments.
