### ISSUE TITLE
RemoteDependencyConstants.AI should be "HTTP (Application Insights)", not "ApplicationInsights"

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet-server#323]
Calling these dependencies type "Application Insights" is confusing to customers because immediate assumption is that these are calls made from their application to AI endpoint. Instead my suggestion is "HTTP (Application Insights)". We still need to differentiate these from HTTP for multi-tier correlation on Application Map to work.

![image](https://cloud.githubusercontent.com/assets/11968377/22803735/02930572-eecb-11e6-87c7-ee421962ff45.png)

**Comment by nizarq** [comment]
Actually what do you think about calling it HTTP (Internal component) or HTTP (tracked component) or something on those lines? The reason why we originally called it Application Insights was because we wanted to signify that this dependency represents calls to another component that is represented by another application insights resource. With the work to support multiple components in a single IKey – these dependencies may not represent a component in an external AI resource but may represent another component / service within the same resource. May be we should start calling it something more generic that doesn’t have the string Application Insights in it.

**Comment by AlexBulankou** [comment]
```HTTP (tracked component)``` sounds good to me. @nizarq would you be able to make this change on [SDK](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/RemoteDependencyConstants.cs#L7) on AppMap?

**Comment by SergeyKanzhelev** [comment]
Why do we need to point that it is another AI component? Imagine it is component you do not know about - like third party service that also using AI. Why would I want to know that and see those dependencies differently from other HTTP dependencies?

**Comment by AlexBulankou** [comment]
We discussed it offline with @SergeyKanzhelev. It comes down the the requirement that tracked components need to have a different type name so that their metrics  are aggregated separately in order to be displayed separately by AppMap, otherwise we end up double counting them. Unfortunately we also cannot move renaming to Breeze because of upcoming client side aggregation.

**Comment by SergeyKanzhelev** [comment]
@qubitron what do you think about this? Customers may/will see components that they have no visibility into as `HTTP (tracked component)`. Would it be confusing if you took dependency on `someWebApi.com` which is also monitored by AI and you suddenly see this site as "tracked component"?

Also @AlexBulankou pointed that Application Map is designed such that you cannot pick Azure Storage as your "central component" to see all other components writing into it. I believe it limits the use of Application Map. Enabling of this feature will potentially change the approach and will not require to differentiate between `HTTP` and `HTTP tracked`.

**Comment by nizarq** [comment]
@AlexBulankou - yes I can make the fix. But will wait for this thread to reach a resolution before starting.

**Comment by nizarq** [comment]
@SergeyKanzhelev  /  @qubitron - Is it very common for customers to take dependency on external components that are also tracked by application insights? Even if it is - I don't think "HTTP (tracked component)" type will be more confusing than the current "Application Insights". 

How can a facilitate closure on this thread?

**Comment by nizarq** [comment]
@AlexBulankou - on the UI side, moving from "Application Insight" dependency bucket to "HTTP (tracked component)" bucket for aggregate data, would mean if a customer is still using the beta sdk - they will stop seeing cross component dependency details. 

We have the following options: 
1. **Preferred** - The current customers are against a beta sdk, it is fine - just ignore the "Application Insights" bucket. They can still browse old data on their own but it won't be available through app map.
2. Merge the two buckets - That is - Add up the request / failures counts from both buckets, re-evaluate avg. response time etc. based on data from both buckets. This will be fairly involved and would need changes to launch in error pane experiences etc. as well.

**Comment by AlexBulankou** [comment]
@nizarq  Hey Nizar, sorry for slow responding to this! Yes, I agree with the preferred option. Specifically I think we can make this transition as part of migrating cross-component correlation feature to AppMapV2.
