### ISSUE TITLE
[Exception statistics]: News dimensions "operation" and "method" are not consistent with existing dimensions

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet-server#327]
Regarding ``operation``: suggestion is to use our standard operation.name dimension for consistency
Regarding ``method``: suggestion is to use ``Failed method`` dimensions present for exceptions

![image](https://cloud.githubusercontent.com/assets/11968377/23035021/ac39241e-f432-11e6-890f-78db5559943e.png)

**Comment by SergeyKanzhelev** [comment]
Great suggestion. Change the `method` is easy. Operation is not that easy - `MetricsManager` doesn't allow to set the operation name, only regular dimensions. I can work around it by creating a custom telemetry initializer that will move property to the `Context.Operation.Name`. I'll think of other options..

**Comment by SergeyKanzhelev** [comment]
Reopening as I reverted the change. This issue needs to be tracked

**Comment by SergeyKanzhelev** [comment]
Will be addressed as a part of https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/348
