### ISSUE TITLE
Detect and flag crash/process exit of the worker process on Azure Appservices

### ISSUE THREAD

**Issue by ashishsinghbhu** [Microsoft/ApplicationInsights-dotnet-server#340]
It would be good for Application Insights to detect when the worker process (w3wp.exe) is crashing on Azure webapps. Currently exceptions are detected, but the ones that are fatal and lead to process crash would be good to be detected and flagged. Customers can probably relate the exceptions around same time as the crash and take corrective actions. Also, any process exits would be good to be flagged (including safe exits/normal recycles) since they help customers understand the behavior of their application better.

**Comment by cijothomas** [comment]
Ability to collect process id is likely to be supported in near future. Once that is collected, analytics queries can be written to see how often process id changes (i.e crash or recycle).
Sending something to application insights when process dies is not feasible, as application insights is part of the process itself.
Closing this issue. @ashishsinghbhu please let us know if you have more question on this.

**Comment by cijothomas** [comment]
Ability to collect process id is likely to be supported in near future. Once that is collected, analytics queries can be written to see how often process id changes (i.e crash or recycle).
Sending something to application insights when process dies is not feasible, as application insights is part of the process itself.
Closing this issue. @ashishsinghbhu please let us know if you have more question on this.
