### ISSUE TITLE
[Exceptions Statistics] Live Metrics threads should be marked as Internal operation

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#356]
I see a few exceptions in exceptions statistics from the live stream feature. Please mark live stream threads as SDK Internal so they would be marked as "Internal" for statistics

https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/PerformanceCollector/Shared/PerformanceCollectorModule.cs#L235

**Comment by SergeyKanzhelev** [comment]
Marking for 2.3 unless it is a big risk for the stable SDK

**Comment by Dmitry-Matveev** [comment]
@tokaplan , were you planning to implement this for 2.3? What would be your risk assessment?
Note: There is a bigger discussion on enabling/disabling exception statistics for 2.3. If the answer is to disable it, this issue might be postponed as well into 2.4.
