### ISSUE TITLE
Updating Dependency Telemetry Operation and Session ID with the Request Header value

### ISSUE THREAD

**Issue by hnigam-git** [Microsoft/ApplicationInsights-dotnet-server#364]
I have an API which is consumed by Power Apps application. Power Apps is sending session id and request id in request header. With Telemetry initializer extension code we are able to associate the session id and request id to AI request telemetry. These Apis are also making calls to datapoint and Graph api internally to fetch the data. These dependent api calls are getting logged under dependency telemetry. 

How can I update the operation id and session id of these dependency telemetry while using the default dependency collection module? I tried it with the below code, but it doesn’t seems to work. 

    public class TelemetryDependencyFilter : ITelemetryProcessor
    {
        private const string HeaderSessionId = "x-ms-client-session-id";
        private const string HeaderRequestId = "x-ms-client-request-id";

        private ITelemetryProcessor Next { get; }

        public TelemetryDependencyFilter(ITelemetryProcessor next)
        {
            Next = next;
        }

        public void Process(ITelemetry item)
        {
            var request = item as DependencyTelemetry;

            if (request != null)
            {
                var sessionId = HttpContext.Current.Request.Headers.Get(HeaderSessionId);
                var requestId = HttpContext.Current.Request.Headers.Get(HeaderRequestId);

                if (!string.IsNullOrEmpty(sessionId))
                    request.Context.Session.Id = sessionId;

                if (!string.IsNullOrEmpty(requestId))
                    request.Context.Operation.Id = requestId;
            }
            Next.Process(item);

        }
    }
}

**Comment by SergeyKanzhelev** [comment]
I think you need to use TelemetryInitializer, not a telemetry processor. And make sure it is configured to run first.

Telemetry Initializers runs before the chain of telemetry processors. Semantically - processors filter data assuming that it was fully initialized by telemetry initializers.

**Comment by SergeyKanzhelev** [comment]
did it help?

**Comment by hnigam-git** [comment]
I tried the Telemetry processor and was able to get hold of the DependencyTelemetry object, but for some reason HttpContext.Current is null, so unable to get the request header values. I'm stuck this way.

I have a question here. When the request telemetry object is created, is there any way session id or the operation id of the request telemetry can be associated with all the dependency calls telemetry in that same request context. This way I can join the request and dependencies tables with that common id to get the holistic view.

**Comment by SergeyKanzhelev** [comment]
By default we are doing `HttpContext.Current` - based correlation. You can apply this workaround: http://apmtips.com/blog/2017/01/05/manual-correlation-in-asp-dot-net-mvc-apps/ and http://apmtips.com/blog/2017/01/12/update-to-the-last-post-set-the-name-in-mvc-web-api/ in case of Web API app.

We are working on improvements in this area

**Comment by SergeyKanzhelev** [comment]
@hnigam-git let me know if you need more information. Closing now
