### ISSUE TITLE
Report exception statistics metric as regular Exception metrics with Operation Name and Failed Method dimension

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet-server#372]
I spent some time reviewing new exception metrics and comparing them with existing exception metrics side by side and I wanted to provide some overall feedback as well as immediate steps to rectify current experience. 
	1. I can see more exceptions. This is great.
	2. New exception metrics are not well correlated with existing exception metrics and it is unclear what to make out of it. Should I still be investigating based on old exception metrics or based on new exception metrics?
	3. New "method" and "operation" dimensions are really the same as existing "Failed Method" and "Operation Name" dimension, but hidden and lower-cased, so they look like a hack.
	4. New "Exceptions thrown" metric is in custom section. Why?
	5. When trying to navigate to samples by clicking on grid row, I get to empty search page. This is very frustrating, especially given that same click on old exception metrics gives me valid samples. (See screenshot 2)

I'm including two screenshots for reference below. 

### Proposal for 2.4
Here's the proposal of what we can do for SDK 2.4 to address the problem:
	1. Start reporting handled exception as regular Exceptions metric
	2. Populate "Failed method" dimension
	3. Populate "Operation name" dimension
	4. Problem ID dimension can be populated as "Handled", so all handled exceptions end up to be grouped together when grouping as problem ID. This is of course not ideal, however this is acceptable initial experience.
	5. Add "Handled" dimension to exceptions, so that all handled exceptions can be filtered out if needed.

If we implement these steps, then all default exception screens continue to work as expected, and the users will start seeing more data that will be immediately visible to them. This will ensure we get feedback from users. Also we won't confuse users with new custom metric and dimensions that look like duplicate of existing dimensions.

@SergeyKanzhelev, others, thoughts?

### Screenshot 1

![image](https://cloud.githubusercontent.com/assets/11968377/24124946/4cc8427a-0d83-11e7-8948-e95f2ce4e474.png)

### Screenshot 2     
![image](https://cloud.githubusercontent.com/assets/11968377/24124976/67add8fc-0d83-11e7-88f3-4f0d7691429b.png)

**Comment by AlexBulankou** [comment]
We decided that for 2.3 stable we'll be disabling exception statistics default collection. As next step @Dmitry-Matveev will validate if it is technically possible to do de-duping to ensure that unhandled exceptions are not counted twice (through exception statistics and through regular exception collection). Next week when @SergeyKanzhelev is back we'll review proposed experience for 2.4.

**Comment by Dmitry-Matveev** [comment]
I would suggest to wait for @SergeyKanzhelev to decide on disabling this for 2.3.

**Comment by SergeyKanzhelev** [comment]
I'm fine removing it from 2.3 if needed. We have some actionable feedback to address before exposing performance counters in UI and can ship it as part of 2.4. Note, it will take some work to move deleted files from here: https://github.com/Microsoft/ApplicationInsights-dotnet/pull/481/files if we want to allow customers to still try this functionality.

**Comment by kstevenham** [comment]
I would still leave it there for 2.3 even though we make some changes for 2.4. It would still be good to get more feedback.

**Comment by SergeyKanzhelev** [comment]
@kstevenham - Greg removed MetricManager from base SDK. if we want to keep exc statistics for 2.3 stable we need to move the code into this repo and make internal. 

At this point I'd say let's remove the feature for `2.3` and keep working on improvements for it in `2.4-beta1`.

Can you please remove it in `develop` branch and keep working on it in `2.4.0-beta1`?

**Comment by kstevenham** [comment]
I forgot about Greg's code. I'll work in 2.4.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by SergeyKanzhelev** [comment]
Closing this issue. Proposed changes for 2.4 will be tracked as the separate issues
