### ISSUE TITLE
After upgrading to 2.3 Beta3 started seeing many calls to https://dc.services.visualstudio.com/api/profile

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet-server#378]
After I deployed InsightsPortal upgraded to 2.3 Beta3 I started seeing many calls to  https://dc.services.visualstudio.com/api/profiles/[ikey]/appId

All the calls result to 404 because InsightsPortal is PPE resource, so the call should be made to PPE endpoint, not to PROD endpoint. Also the result is not cached, so the calls continue (3.3M in last 30 min).

So we should:
1. Cache the result
2. Use DC endpoint, not hardcode to DC PROD.

@Dmitry-Matveev, @nizarq

![image](https://cloud.githubusercontent.com/assets/11968377/24276056/323135b4-0ff1-11e7-9e74-917490ffb577.png)

**Comment by nizarq** [comment]
Here's what's happening today. 
1. We are caching the result. But in case of failure we will retry every 5 seconds (throttle). 
2. The way endpoint is determined is: 
  a. If overridden endpoint is provided. Use that to query appId. Here is how to specify the endpoint.
``` 
<Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">
      <ProfileQueryEndpoint>endpoint_here</ProfileQueryEndpoint>
</Add>
```
  b. Otherwise, use the telemetry endpoint baseurl and append /api/profiles/[Ikey]/appId. So if your config has a different telemetry endpoint (PPE) specified in the channel - It **should** already query against the PPE endpoint.

What you ought to do is either provide the override in the config for both dependency and request tracking modules or make sure that the telemetry endpoint is overridden in the telemetry channel.

**Comment by AlexBulankou** [comment]
@nizarq, I think it is good idea to retry in case of 5xx (server errors), but not in case of 4xx (client errors). For 400, for example, there's no point in retrying. I don't think it necessarily meets the bar for 2.3 stable, since it will only impact those with custom endpoint (@Dmitry-Matveev, thoughts?), but I think we should add improve the retry logic to differentiate between codes for 2.4. For reference, you can see extra dependency traffic on the portal that was generated:

![image](https://cloud.githubusercontent.com/assets/11968377/24313282/73e6de34-1099-11e7-9822-f27e4a389cd2.png)

**Comment by OsvaldoRosado** [comment]
This isn't an issue that will only impact those with custom endpoint. Receiving 404 in particular is not an error, it is a definitive statement that the profile does not exist, and this should not be retried.

**Comment by AlexBulankou** [comment]
Yes, but in case invalid ikey is sent and invalid ikey is also configured in SDK, then that user has misconfigured SDK and there will be no impact on their bill. However if they use custom endpoint AND have not specified the new ``ProfileQueryEndpoint`` then they will be flooded with new telemetry, while having otherwise correctly configured their SDK, so there will be impact on their bill. The latter case is much less common.

**Comment by Dmitry-Matveev** [comment]
@AlexBulankou, my concern regarding 2.3 vs 2.4 here would be that you saw 3.3M calls within 30 minutes while SDK was trying to get application ID. With the latest @nizarq changes, it should've been only retrying every 5 seconds, so we'd need to check that logic and avoid 3.3M calls per half an hour in 2.3 if possible.

**Comment by nizarq** [comment]
Fixed with https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/386
