### ISSUE TITLE
After upgrading to 2.3 Beta3 started seeing decorated dependencies QP endpoint

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet-server#379]
Immediately after deploying the service (InsightsPortal) that was upgraded to 2.3 Beta3 I started seeing the following dependencies from the following QP endpoint appearing in our telemetry:

quickpulse-ppe.aisvc.visualstudio.com | I5UqryrMvK+2zqbkrtAaUyMtQB0wPvhKJjcXYr7b7ic=

![image](https://cloud.githubusercontent.com/assets/11968377/24275884/18a32fd6-0ff0-11e7-8e7a-725968f9ae85.png)

I think what it means is that it is unfiltered dependency from QP service that is onboarded to 2.3 Beta1/2 and the reason it is not filtered because it checks against "quickpulse-ppe.aisvc.visualstudio.com" but not against "quickpulse-ppe.aisvc.visualstudio.com | I5UqryrMvK+2zqbkrtAaUyMtQB0wPvhKJjcXYr7b7ic="
The fix would be to modify the check to consider that target will be modified with postfix.

@Dmitry-Matveev, @nizarq

**Comment by iusafaro** [comment]
Fixed by using dependency target instead of name.
