### ISSUE TITLE
[Exception Statistics] Report Operation Name as a standard context property, not a dimension

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#394]
@AlexBulankou is this important for 2.4 release?

**Comment by AlexBulankou** [comment]
I believe we implemented this for 2.4 Beta1. @SergeyKanzhelev  can you please confirm that close?

**Comment by SergeyKanzhelev** [comment]
Nope, we just renamed the property to `operationName`.

**Comment by SergeyKanzhelev** [comment]
fixed in #475
