### ISSUE TITLE
Remove obsolete folder

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#41]
this folder is obsolete: https://github.com/Microsoft/ApplicationInsights-server-dotnet/tree/aac44ef4cf526143d71683464e1c5a956cdeb5df/Src/PerformanceCollector/Net45/PerformanceCollector/Telemetry

**Comment by abaranch** [comment]
@tokaplan I thought that comes from contracts nuget that is used

**Comment by tokaplan** [comment]
I remember initially those files were installed as part of the contract NuGet. I don't remember what has changed, but it doesn't look like they are used anymore... I'll take a look.

**Comment by tokaplan** [comment]
#70
