### ISSUE TITLE
InvalidOperationException on Track* API Calls

### ISSUE THREAD

**Issue by nscaife** [Microsoft/ApplicationInsights-dotnet-server#435]
I'm trying to add ApplicationInsights (Microsoft.AI.WindowsServer 2.3.0.0) to a project, and I'm getting an InvalidOperationException on every Track call I make:

```
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=Sequence contains no elements
  Source=System.Core
  StackTrace:
       at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
       at Microsoft.ApplicationInsights.Extensibility.Implementation.SdkVersionUtils.GetSdkVersion(String versionPrefix)
       at Microsoft.ApplicationInsights.TelemetryClient.<>c.<Initialize>b__32_0()
       at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Func`1 valueFactory)
       at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)
       at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
       at Microsoft.ApplicationInsights.TelemetryClient.TrackTrace(TraceTelemetry telemetry)
       at Microsoft.ApplicationInsights.TelemetryClient.TrackTrace(String message)
  InnerException: 
```

Here's the code I'm using to reproduce:

```
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.ApplicationInsights.Extensibility;

namespace test
{
    internal class testing
    {
        internal TelemetryClient tc = new TelemetryClient();

        private void Test()
        {
#if DEBUG
                TelemetryConfiguration.Active.TelemetryChannel.DeveloperMode = true;
#else
                TelemetryConfiguration.Active.TelemetryChannel.DeveloperMode = false;
#endif
                tc.InstrumentationKey = "<my key>";
                tc.Context.User.Id = Environment.UserName;
                tc.Context.Session.Id = Guid.NewGuid().ToString();
                tc.Context.Device.OperatingSystem = Environment.OSVersion.ToString();

                tc.TrackTrace("Test"); // exception thrown here
        }
    }
}
```

**Comment by SergeyKanzhelev** [comment]
Hm, I do not see file version in the file:

![image](https://cloud.githubusercontent.com/assets/9950081/24919211/c7db7930-1e97-11e7-8bd6-6556bc3aa580.png)

Even though the file version attribute is set:

![image](https://cloud.githubusercontent.com/assets/9950081/24919232/da990ff6-1e97-11e7-86c5-6c7267118a3c.png)

@dnduffy, @cithomas can you please look at it ASAP.

**Comment by SergeyKanzhelev** [comment]
@nscaife what framework version are you compiling your application against?

**Comment by nscaife** [comment]
@SergeyKanzhelev  I'm targeting 4.5.

**Comment by cijothomas** [comment]
@SergeyKanzhelev where did you get the dll from? I just downloaded from nuget now and i can see the fileversion correctly set.

![image](https://cloud.githubusercontent.com/assets/5232798/24921350/5a2005de-1e9f-11e7-9a01-1f77beabee6c.png)

**Comment by cijothomas** [comment]
I am not able to repro. As mentioned in my earlier reply, my .dll files have the file version correctly populated.

**Comment by nscaife** [comment]
I think I figured it out.  I'm using ILMerge, and it was merging these in since they're set Copy Local=true after the nuget install.   I stopped merging them and it has stopped throwing the exception.

Is this module incompatible with ILMerge?

**Comment by SergeyKanzhelev** [comment]
@nscaife you need to set an AssemblyFileVersion attribute for the resulting assembly. 

@cijothomas - we need to wrap SDK version helper into `try{}catch` in 2.4 to prevent those failures to ever happen again and throw outside the initializer

**Comment by SergeyKanzhelev** [comment]
@cijothomas we need to do it in all sdks including logging adaptors.

**Comment by SergeyKanzhelev** [comment]
Closing the issue. @nscaife we will handle this error in the future version of SDK. For now - please make sure that `AssemblyFileVersionAttribute` is set on resulting merged assembly
