### ISSUE TITLE
Move QuickPulse in a separate repo and ship it as separate Nuget package

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet-server#450]
I would like to propose that we create a separate GitHub repository for .NET QuickPulse functionality and move QuickPulseTelemetryModule and QuickPulseTelemetryProcessor and associated tests there. We will then ship QuickPulse as separate Nuget package. The advantages would be:
* Independent, more streamlined, release schedule and higher agility. The proposal is that we have our WindowsServer package is referencing a range for QP versions, up to next major, which will ensure that QP Nuget can be released on a more frequent cadence if necessary.
* Distinct place for QuickPulse SDK as it exists today as a distinct APM feature. Subsequently we can consider whether we can use the same repo for QuickPulse functionality for other languages - this will help reduce common issues in multiple technologies (for example QuickPulse for .NET and QuickPulse for Java) that have the same underlying cause
 
Potential drawbacks for this change would be refactoring work involved in making the split and also risk of performance test regressions if our nightly performance tests depend on a released package drop from QP. However this can be avoided if nighly performance tests use the nighly drops from QP.

@tokaplan @AlexKlimovMS  @zakimaksyutov @SergeyKanzhelev @Dmitry-Matveev @cijothomas

**Comment by zakimaksyutov** [comment]
I think we need to split QuickPulse from PerfCounters to support .NET Core. Does the proposal support .NET Core?

**Comment by AlexBulankou** [comment]
Yes, the ideas is that we split QuickPulse module and telemetry processor from PerformanceCounter module and PerformanceCounter module will remain in dotnet-server repo. Then we can start building QuickPulse with .NETStandard. This by itself can be done by merely splitting in a different project, my proposal goes further and assumes different repo and release schedule for QuickPulse.

**Comment by SergeyKanzhelev** [comment]
@AlexBulankou is it a problem we need to solve? I see the same problem for all other features like exceptions statistics and metrics so perhaps we need a better story of shipping features "under the feature flag".


Quick pulse is using the same implementation for collecting performance counters as standard collection logic. It will also subscribe to the MetricsManager to show the custom metrics in the "live" UI and `QuickPulseTelemetryModule` should go away in favor of @macrogreg's standard counters pre-aggregation module and Operationalized metrics support. The right place for those will be in base library once we will work on design and implementation.

So from the layering perspective
- an interface between QP backend and SDK should be documented and implemented in Base library
- QP should be able to set up standard data collection modules to produce data more frequently specifically for the needs of QP.

@zakimaksyutov PerfCounters NuGet should start targeting .NET Core so it works on that framework in Azure Web Apps and we've been discussing supporting Linux counters eventually in this NuGet. So no, it's not a prerequisite and in fact it's less work to keep it than to split it.

**Comment by SergeyKanzhelev** [comment]
let's reopen if we will decide it's worth the effort
