### ISSUE TITLE
Feature proposal: enable listening to HttpClient DiagnosticSource on net45

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet-server#467]
**Problem:**

In the DependencyCollector 4.5 we have following instrumentation for outgoing Http requests:
- Profiler
- EventSource
- HttpClient on net46 with specific DiagnosticListener

DependenycCollector 4,5 is used in AspNetCore SDK for NET451 target.

Applications that run on AspNetCore are also likely to run on .net core (and AspNetCore 2.0 always brings .net core), even if they target NET Desktop framework. 
So the actual System.Net.Http dll and other .NET packages are in fact .NET core implementation.

Net core HttpClient  could neither be instrumented with profiler nor with event source. 
The only instrumentation it has is [DiagnosticSource](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs)

Listener to this instrumentation is implemented in DependencyCollector.NetCore (that targets netstandard 1.6).

**Solution**:
Let's compile listener for DiagnosticSource into DependencyCollector NET45, so regardless of HttpClient dll used in runtime, DependecyCollector would work.

**Comment by dnduffy** [comment]
Agreed.

**Comment by lmolkova** [comment]
Thanks for the feedback,  I'll submit PR later today
