### ISSUE TITLE
Fix DependenyCollector rdd version tests

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet-server#468]
Probably everyone has seen this failure before:
`Assert.AreEqual failed. Expected:<rddp:2.4.0-10966-fw4>. Actual:<rddp:2.4.0-10971-fw4>`

Several test classes in DependencyCollector NET40 and NET45 (e.g `ProfilerHttpProcessingTest`) verify SDK version set in telemetry.

```
    string expectedVersion = SdkVersionHelper.GetExpectedSdkVersion(typeof(DependencyTrackingTelemetryModuleTest), prefix: "rddp:");
    Assert.AreEqual(expectedVersion, remoteDependencyTelemetryActual.Context.GetInternalContext().SdkVersion);
```

Note that `expectedVersion` is taken from the test assembly.
The actual version is set by DependencyCollector assembly.

Now how versions are calculated: it's done in `GlobalStaticVersion.props`
```
    <PreReleaseVersion Condition="'$(PreReleaseVersion)'==''">$([MSBuild]::Divide($([System.DateTime]::Now.Subtract($([System.DateTime]::Parse($(SemanticVersionDate)))).TotalMinutes), 5).ToString('F0'))</PreReleaseVersion>
```

So, the version is basically build time of the assembly.

------------------

Tests compare build time of the DependencyCollector **test** assembly with build time of DependencyCollector itself.

Of course, they do not always match especially during development, when tests are updated and compiled more frequently than DependencyCollector.

-------------------

**If this check makes sense, it should compare SdkVersion on telemetry with DependencyCollector SdkVersion**

**Comment by SergeyKanzhelev** [comment]
I think the fix it simple. In other places we are using it correctly:

```
string expectedVersion = SdkVersionHelper.GetExpectedSdkVersion(typeof(UnobservedExceptionTelemetryModule), prefix: "unobs:");
```

See - we are using type `UnobservedExceptionTelemetryModule` to get the version, not the `UnobservedExceptionTelemetryModuleTest`
