### ISSUE TITLE
Dependency telemetry for Azure Table calls no longer contains the Partition Key and Row Key in the data column

### ISSUE THREAD

**Issue by david-jarman** [Microsoft/ApplicationInsights-dotnet-server#476]
When our project upgraded Application Insights from 2.0.0 to 2.2.0, the dependency telemetry that is generated from calls to Azure Table storage no longer contains information about the query, like the partition key and row key.

Is there a way we can get the PK and RK for queries to Azure Table storage in our dependency telemetry now that we have upgraded to 2.3.0? This would be helpful for us to profile our application to see if we ever make redundant queries from a single request to our service.

Update:
I created a query to prove that the update was the source of this regression:

![image](https://cloud.githubusercontent.com/assets/1639399/25289076/0d1134ee-267d-11e7-9630-dfe1a8f5dd69.png)

Here is what some of our dependency telemetry looked like before the update:
![image](https://cloud.githubusercontent.com/assets/1639399/25289335/061bb974-267e-11e7-8afd-fbadab7a71be.png)

Here is what some of our dependency telemetry looked like after the update:
![image](https://cloud.githubusercontent.com/assets/1639399/25289359/21d828a0-267e-11e7-9c5d-1d9d66fa47b9.png)

**Comment by SergeyKanzhelev** [comment]
Seems to be the problem with our backend. Workaround you can use right away is to create a telemetry initializer that will set `type` of dependency to `Custom Azure Table` or something else that is not `Azure Table`.

```
    using System;
    using Microsoft.ApplicationInsights.Channel;
    using Microsoft.ApplicationInsights.DataContracts;
    using Microsoft.ApplicationInsights.Extensibility;    namespace Telemetry
    {
      public class ClearUserIdTelemetryInitializer : ITelemetryInitializer
      {
        public void Initialize(ITelemetry telemetry)
        {
            var dependencyTelemetry = telemetry as DependencyTelemetry;
            if (dependencyTelemetry == null) return;
            if (dependency.Type == "Azure Table") dependencyTelemetry.Type = "Custom Azure Table";
        }
      }
    }
```

**Comment by david-jarman** [comment]
@SergeyKanzhelev, I did find one gotcha with your workaround. When you add the initializer to ApplicationInsights.config, you must place the custom intializer AFTER the DependencyCollector initializer.

This works:
`<Add Type="AINamespace.HttpDependenciesParsingTelemetryInitializer, AIAssembly"/>`
`<Add Type="MyNamespace.AzureTableDependencyInitializer, MyAssembly"/>`

This doesn't work:
`<Add Type="MyNamespace.AzureTableDependencyInitializer, MyAssembly"/>`
`<Add Type="AINamespace.HttpDependenciesParsingTelemetryInitializer, AIAssembly"/>`

**Comment by SergeyKanzhelev** [comment]
@david-jarman but it did work after the change of a sequence, correct?

**Comment by david-jarman** [comment]
@SergeyKanzhelev, yes, I confirmed that it worked after I changed the sequence.
