### ISSUE TITLE
Getting the Operation Id from within a Web API call

### ISSUE THREAD

**Issue by mmaitre314** [Microsoft/ApplicationInsights-dotnet-server#48]
When my Web API hits an exception and is about to return an HTTP 500, I'd like the response content to include the Session ID and Operation ID so users can report more actionable bugs. I read that AppInsights was setting that info in the OWIN environment, but I can't find it. Would you recommendations about how to retrieve those IDs?

**Comment by abaranch** [comment]
For IIS hosted WebAPI projects RequestTelemetry that has all context information is accessible through HttpContext extension method: System.Web.HttpContextExtension.GetRequestTelemetry (starting from 2.0.0-beta3). Session would available if you also use JS SDK.

**Comment by mmaitre314** [comment]
Thanks for the info!
