### ISSUE TITLE
Use local endpoint in unit tests

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet-server#494]
Some unit tests make outgoing http call to external endpoints
* DependencyCollector.NetCore.Tests DependencyTrackingTelemetryModuleTestNetCore
* DependencyCollector.Net46.Tests DependencyTrackingTelemetryModuleTestNet46

To avoid test failures on http issues, or external service unavailability, they should call local endpoint.
* On Net46, it's easy to start local server with [Anna](https://github.com/Anna-Rx/Anna)
* On NetCore, Kestrel should be used (there are examples in AspNetCore repo).

There is a value in keeping those as unit tests, since they are small, fast and easy to run.

With mocked localhost server tests must also verify cross-component correlation feature by mocking Request-Context

**Comment by lmolkova** [comment]
both [Anna](https://github.com/Anna-Rx/Anna) and [Nancy](https://github.com/NancyFx/Nancy) do not have signed dlls and all DependencyCollector unit test dlls are signed (because they use internal classes from the SDk).

That means such tests should go to functional tests and dlls do not need to be signed.

**Comment by SergeyKanzhelev** [comment]
We can just use the `HttpListener` like we do to fake the telemetry [channel](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/75373e57dcf8d646c54ee188461c373f2cc98939/Test/PerformanceCollector/FunctionalTests/Helpers/HttpListenerObservable.cs#L24) No need to run a framework for this.
