### ISSUE TITLE
Incorrect x-component correlation headers being sent in some cases

### ISSUE THREAD

**Issue by nizarq** [Microsoft/ApplicationInsights-dotnet-server#503]
Generally cross-component correlation headers are in the format `Request-Context=cid-v1:<app_id>`. It turns out we are sometimes seeing values where app_id is missing but the `cid-v1:` part is present.

Doing code inspection, I narrowed this down to being a regression caused when the Bcl.Async nuget was removed and a different version of an existing method was written for .net 40. The new implementation diverged from the contract in the original method, where the exception would flow out if app_id could not be retrieved. As you can see https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/Common/CorrelationIdLookupHelper.cs#L231-L235, the new implementation started catching the exception, eating it and returning null. This gave the impression to the caller that a value was retrieved for app_id and it created the string `cid-v1:<null>`.

We should fix this by restoring the original contract.

**Comment by nizarq** [comment]
@SergeyKanzhelev @cijothomas @Dmitry-Matveev

**Comment by Dmitry-Matveev** [comment]
@nizarq, is this issue critical for 2.4 stable release?

**Comment by nizarq** [comment]
Actually, because of issue https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/504, we now explicitly want to send `cid-v1:`, when we are not able to retrieve appId. So this thread can be closed as it is now irrelevant.

Although we should take the above mentioned issue for 2.4 stable release, so that we can draw an app map that is appealing to the customers and does not show multiple nodes for the same dependency.
