### ISSUE TITLE
Indicating "tracked component" for first few dependency calls for which app id is not yet available.

### ISSUE THREAD

**Issue by nizarq** [Microsoft/ApplicationInsights-dotnet-server#504]
For cross component correlation, we add headers containing app id. This indicates the receiving component, that the component that generated the headers is a tracked component. 

When retrieving the app id for any given ikey, the first bunch of dependency calls to a given component, may not have the app ids available just yet (we retrieve app ID in the background but do not block the program execution while we do so). Hence outgoing headers for such dependencies do not contain the Request-Context header. This results in such dependencies being logged simply as HTTP dependencies rather than HTTP **tracked** dependencies. 

We feel there is value in indicating, that a dependency is tracked dependency event when app ID could not be fetched and added in time. This will among other things, make it easy for us to ignore showing dependencies in two places - one with the other server nodes and one under the HTTP node group, where both blocks really represent the same kind of url request and should be aggregated once. As per @soubhagyaDash, showing every dependency in two places, just kills the user confidence in us and gives the impression that our cross component correlation is broken. We intend to ignore the first few dependencies for which app_id could not be retrieved if there is a node in app map that aggregates the data from subsequent calls where app id is known.

Hence, the proposal here is to have a special value in the header, which indicates, that the current dependency call is to a tracked component but appId could not be retrieved yet. 

Here are a couple of proposals: `Request-Context=cid-v1:00000000-0000-0000-0000-000000000000` or `Request-Context=cid-retrieval_in_progress` (or something like that). I prefer the 2nd one. We can then just look for this header and still mark the dependency of type (track dependency).

**Comment by nizarq** [comment]
@SergeyKanzhelev @cijothomas @Dmitry-Matveev

**Comment by zhencui** [comment]
`Request-Context=cid-v1:` is also an option(leave an empty string as App Id). From the caller perspective, using string.IsNullOrEmpty to check the exceptional case is more natural than Guid.TryParse or comparing with a magic string.

**Comment by nizarq** [comment]
I am warming up to this option as well. My only concern being - from a contract perspective it doesn't appear to be very clean. But it is no worse than Note that `Request-Context=cid-v1:00000000-0000-0000-0000-000000000000`.

To me, `cid-v1` stands for correlation id, version 1 and I expect it always have a value of a certain format as designated by `v1`.

Having said that, if others agree to having a null value, I don't think it's a bad option.

**Comment by xiaomi7732** [comment]
I vote for `Request-Context=cid-v1:` since that's relatively simple but also a way to express that we tried to get the appId and we didn't could fetch it in time with.

**Comment by SergeyKanzhelev** [comment]
If my app has two http dependency with the same DNS name, one of them returns appid header and another doesn't - what UI will show? The way I'm reading this issue description - UI will not merge those two. Is it intended to split a single dependency from the application standpoint into two separate nodes? Is it what customer will expect to see?

Can those be merged in UI? Once merged - the issue of a first few dependency calls will be eliminated.

**Comment by xiaomi7732** [comment]
@SergeyKanzhelev, I think you are calling out a valid point. If I understand right, the UI will have only one node for that case. It doesn't really matter from UI's perspective which approach we take here, but we need to make a contract on one and then UI can handle the rest of it.
For example, if we decide to take Guid.Empty approach here, UI will deal with appId=Guid.Empty. And if we decide to take empty string approach, UI will deal with appId=<empty string> case. So on so forth.

**Comment by SergeyKanzhelev** [comment]
@xiaomi7732 if it's a single node - why do we need any indication that the component we communicate to is monitored by AI? I do not understand the issue this proposal is trying to address

**Comment by xiaomi7732** [comment]
@SergeyKanzhelev Sorry for the confusion.
It is multiple-nodes now. We are trying to make it single node. To reach that point, we need to decide how to record the data where appId is not fetched in time. That's the point where we have 3 proposals here:
* Request-Context=cid-v1:00000000-0000-0000-0000-000000000000
* Request-Context=cid-retrieval_in_progress
* Request-Context=cid-v1:
Once we take one of the format, the UI can take action on that special case.
Please let me know if I still am not state it clear.

**Comment by SergeyKanzhelev** [comment]
getting back to my question - is it what customer will expect to see? 

>If my app has two http dependency with the same DNS name, one of them returns appid header and another doesn't - what UI will show? The way I'm reading this issue description - UI will not merge those two. Is it intended to split a single dependency from the application standpoint into two separate nodes? Is it what customer will expect to see?

Can UI just merge those based on DNS name? 

It feels like solving an artificial problem. I look at AppId as on the extra information that helps correlate components, not as an separate dependency.

We are already solving the UI problems of circular dependencies by not injecting "self" appId. And I believe we need to get rid of this logic, not making it even more UI-dependant.

**Comment by nizarq** [comment]
@SergeyKanzhelev - I think what you are saying makes sense. Merging with fix the situation. In fact, when we initially discussed this, merging was something that was brought up as a solution. At that point we were concerned about the first few calls the don't have the appId in particular, so it felt like getting rid of the node that represents that call is probably simpler and benign. Only a few calls are sampled out and we don't have to make sure the drill through experience shows data from both nodes etc. 

That meant we also, didn't have to explicitly deals with sdk updates. For example a customer, who was previously using an sdk version that did not give cross component correlation, would be used to seeing http dependency. After upgrading to the new sdk, they see dependency nodes attached to the server node. It may or may not be desirable to merge at this point.

Finally, if the user tried the new sdk for a little bit, and didn't like correlation and either turned it off or went back to the old sdk - if we go with merge - even if user had appID in a very few calls, merge will put all calls in the x-component dependency buckets (although, for the time being only). 

My intent was to not try and be smart about this complexity. Rather show the data how it is. If it's http dependency - show as http dependency. If it is x-component dependency, show it as x-component (and fix the sdk to make sure a x-component dependency is generated when intended even if appId is not found for the time being). 

I am ok with merging everything if you feel merging is the way to go and we don't really care about trying to keep things as they are for the situations above. Let me know you opinion and we will go down that path.

**Comment by SergeyKanzhelev** [comment]
Can you remind me why do we need a separate type for those dependencies at all? They are just HTTP dependency with the different target

**Comment by nizarq** [comment]
Because we need to show some of them under the http group node and others as and embedded node on the server nodes based on the selection model.

**Comment by SergeyKanzhelev** [comment]
You just repeated what I said. Why do we need to show http which is component separately from http that is not a component?

**Comment by nizarq** [comment]
Identification and aggregation.

We use "tracked component" type to identify whether a dependency is to be shown with the server component (as opposed to under the http group node).  One can argue presence of app Id might be enough, but we decided to make it more explicit when we started implementing.

**More Importantly**: It helps at the group node aggregations level. The aggregate data that's shown for the http group node, should not count x-component dependency numbers, otherwise they will get double counted.

**Comment by SergeyKanzhelev** [comment]
I got the technical part of what is implemented. Now  - why do customer need to distinguish `HTTP` from `tracked HTTP`? Why it's ok to merge numbers for two separate appid and not ok to merge numbers for HTTP of different flavors: when that component's monitoring was enabled from HTTP when that component monitoring wasn't?

**Comment by nizarq** [comment]
In principal, there's nothing wrong with merging HTTP numbers with HTTP tracked numbers. It just goes against the proposed app map design.

**Comment by nizarq** [comment]
Discussed this with @SergeyKanzhelev in person and explained the constraints we are working in. We are going with sending `Request-Context=cid-v1:`. If this header is detected the telemetry will be sent as http tracked dependency but without anything appended to target field.

**Comment by Dmitry-Matveev** [comment]
Closing the issue as per the current app map design.

**Comment by lmolkova** [comment]
@DeepakIoT 
Please refer to my [comment](https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/739#issuecomment-367391528) in another thread.

If you have more comments, questions, please create a new issue.
