### ISSUE TITLE
DependencyTelemetry Name property is not normalized

### ISSUE THREAD

**Issue by yantang-msft** [microsoft/ApplicationInsights-dotnet-server#506]
In NET451, the dependency telemetry name is like “api/value” in NETCore, it’s “GET api/value”.

**Comment by SergeyKanzhelev** [comment]
in NET451 it is this way only when EventSource is used. When Profiler is used it is also starts with verb like `GET`.

Potentially we can improve NET451 collection using @Brahmnes's injection using reflection

**Comment by cijothomas** [comment]
Now the default dep collection is using diag source and we always get the verb. closing this.
