### ISSUE TITLE
"Extreme App" monitoring noise significantly

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#510]
Extreme App is the app with sampling turned off with 5 traces in every request. Monitoring noise increased in the latest SDK (2.4.0-beta1) comparing to what it was in 2.3.

We have new features that might have contributed:
- new TelemetryCorrelation http module that subscribes to the new callback `PreRequestHandlerExecute`
- Pre-aggregated metrics - new locks on sync path
- exceptions statistics - additional data collection

@cijothomas and @kstevenham investigating

**Comment by SergeyKanzhelev** [comment]
Possible improvements after running local perf analysis. Disclaimer here - I didn't configure endpoints correctly so some numbers are skewed. 

Degradation:
1. Cache the method we take with reflection: `MethodInfo addOnSendingHeadersMethod = httpApplication.Response.GetType().GetMethod("AddOnSendingHeaders");`. Also no need to instantiate the parameters array all the time - can only do it once. 
2. Why do we need to call `if (this.IsFirstRequest(httpApplication))` in OnEndRequest for non `NET40`? Why to subscribe on event at all?
3. `ClientIpHeaderTelemetryInitializer` takes the most on my test. It may be even worse as on local box verbose tracing got enabled when I turn on sampling profiling. It looks like most of this time is IP validation that can/should be moved down to the sanitize method and run asynchronously. Also no need to allocate `var requestWrapper = new HttpRequestWrapper(platformContext.Request);`
4. Second most expensive initializer - `SyntheticUserAgentTelemetryInitializer`. This initializer for some reason do not cache the value of SyntheticSource in RequestTelemetry. So parsing happening all the time - for every telemetry separately. It will be extremely visible in the app with a lot of request-related telemetry.  Also `foreach` is less efficient than `for` and dictionary do not contain empty elements - no need to check every time. One more - taking `request.UserAgent` on every iteration is super expensive:

  ```
  public string UserAgent
  {
	get
	{
		if (this._wr != null)
		{
			return this._wr.GetKnownRequestHeader(39);
		}
		return null;
	}
  }
  ```
5. User cookie - can replace `Split` to `Substring`. `var cookieParts = userCookie.Value.Split('|');` Same with session
6. Operation name initializer makes way too many concatenations. Maybe use `StringBuilder`. In the next version we can just take the routeTemplate instead of constructing manually

**Comment by SergeyKanzhelev** [comment]
@lmolkova - was it intentional to call `IsFirstRequest` for non `NET40`?

CC: @cijothpmas, @Dmitry-Matveev

**Comment by SergeyKanzhelev** [comment]
@cijothomas please post your findings here or in `-dotnet` repo. Let's discuss tomorrow how many fixes we want to take to balance minimum changes and maximum benefits. Let's get performance back

**Comment by lmolkova** [comment]
> was it intentional to call IsFirstRequest for non NET40?
It was always there, and it is protection from the case when customer has added module twice, it was added in #43 and there is even a functional test for it.

**Comment by SergeyKanzhelev** [comment]
@lmolkova there is the similarly called function `IsFirstRequest` in `AspNetDiagnosticTelemetryModule`. Will it suffice?

**Comment by lmolkova** [comment]
Oh, you are right, the whole `ApplicationInsightsHttpModule.OnEndRequest` should go away with !NET40

**Comment by cijothomas** [comment]
We should continue perf improvements after 2.4 stable is out.

**Comment by MS-TimothyMothra** [comment]
@SergeyKanzhelev, @Dmitry-Matveev I'm going to close this task for now, because we are tracking this in standup. But feel free to re-open if you believe we should continue to track in github as well.
