### ISSUE TITLE
Add support for EntityFramework diagnostic source listener

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet-server#522]
This PR was never completed but it can be used as example: https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/297

**Comment by SergeyKanzhelev** [comment]
CC: @TomMilos who will be working on expanding the technologies coverage for dependency monitoring

**Comment by SergeyKanzhelev** [comment]
This will be handled by @anpete next week. 

Roadmap: https://github.com/aspnet/EntityFramework/wiki/Roadmap#ef-core-20-under-development
Issue: https://github.com/aspnet/EntityFramework/issues/8272

**Comment by Dmitry-Matveev** [comment]
Addressed with #607 .
