### ISSUE TITLE
Consistently log Http DependencyCollector callbacks in HttpProcessing

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet-server#537]
HttpProcessing callbacks are invoked for profiler and Http Desktop DiagnosticSource.
It logs callbacks, but it may be difficult to determine which instrumentation called it.

```
DependencyCollectorEventSource.Log.BeginCallbackCalled(thisObj.GetHashCode(), resourceName);
``` 

DiagSource logs it's events in `HttpDesktopDiagnosticSourceListener`.
Profiler should log them in `ProfilerHttpProcessing`

And they should be removed from the`HttpProcessing`.

All other logs except `BeginCallbackCalled` should remain where they are

**Comment by cijothomas** [comment]
Upgrading to P1, as without this it was really difficult to debug an issue in dependency module.

**Comment by lmolkova** [comment]
@cijothomas see #553
