### ISSUE TITLE
Lack of stop event on system.data.sqlclient.sqlconnection.open breaks EventSource activity tracking

### ISSUE THREAD

**Issue by northtyphoon** [Microsoft/ApplicationInsights-dotnet-server#540]
The following code in ProfileRuntimeInstrumenation.cs instrumented System.Data.SqlClient.SqlConnection.Open function. The instrumentation only emits Microsoft-ApplicationInsights-Data/Operation/Start event but not Stop event. It breaks the EventSource activity tracking used in Application Insights Profiler. It caused the subsequent sql activity be mis-correlated as child activity.

            // Decorates SqlConnection.Open, 0 params(+this)
            // Tracks dependency call only in case of failure
            Functions.Decorate(
                "System.Data",
                "System.Data.dll",
                "System.Data.SqlClient.SqlConnection.Open",
                sqlCallbacks.OnBeginForOneParameter,
                null,
                sqlCallbacks.OnExceptionForOneParameter,
                isStatic: false);

Microsoft-ApplicationInsights-Data/Operation/Start                                 	6,035.317		//2/1/3/  
Microsoft-ApplicationInsights-Data/Operation/Start                                 	6,035.713		//2/1/3/1/

**Comment by SergeyKanzhelev** [comment]
What milestone are we tracking this bug for? I had impression that it is important. @northtyphoon we discussed the possible fix with you. Do you plan to send a PR?

**Comment by northtyphoon** [comment]
We need the fix in 2.4. I will sync with @iusafaro .
