### ISSUE TITLE
Failed HTTP requests done with HttpClient are never collected by FrameworkEventSource

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet-server#548]
Reproducible with any 2.4 beta and **2.3 stable SDK**

Test:
```C#
    await new HttpClient().GetAsync(new Uri($"http://{Guid.NewGuid()}/"));
```

**Expected** result: failed dependency is collected.
**Actual**: not collected

Dependency is properly collected with WebRequest, sync response

``` C#
    HttpWebRequest request = WebRequest.CreateHttp(new Uri($"http://{Guid.NewGuid()}/"));
    var result = request.BeginGetResponse(null, null);
    using (request.EndGetResponse(result)) {}
```

It happens because with HttpClient End happens before Begin:

```
Event Name                                                                            	Time MSec	Process Name                      	Rest  
Microsoft-ApplicationInsights-Extensibility-DependencyCollector/EndCallbackCalled     	3,821.804	vstest.executionengine.x86 (29372)	ThreadID="5,336" FormattedMessage="End callback called for id = '9223372032586174927' " id="9223372032586174927" appDomainName="UnitTestAdapter: Running test" 
Microsoft-ApplicationInsights-Extensibility-DependencyCollector/EndCallbackWithNoBegin	3,822.229	vstest.executionengine.x86 (29372)	ThreadID="5,336" FormattedMessage="End callback - cannot find start of operation for id = '9223372032586174927' " id="9223372032586174927" appDomainName="UnitTestAdapter: Running test" 
Microsoft-ApplicationInsights-Extensibility-DependencyCollector/BeginCallbackCalled   	3,823.995	vstest.executionengine.x86 (29372)	ThreadID="5,336" FormattedMessage="Begin callback called for id = '9,223,372,032,586,174,927', name= 'http://f5cb0a72-dc17-4f0d-aa57-6e5d6fb75b31/' " id="9,223,372,032,586,174,927" name="http://f5cb0a72-dc17-4f0d-aa57-6e5d6fb75b31/" appDomainName="UnitTestAdapter: Running test" 
```

**There is no issue with HttpDesktopDiagnosticSource from the latest beta3 - all kinds on dependencies are properly collected: WebRequest and HttpClient, failed or not.
So I assume this is not critical for 2.4.0**

**Comment by cijothomas** [comment]
We have this test TestRddForHttpAspx451WithHttpClient(). 

This tracks failed dependency.But the failure here is by connecting to google.com/404 which is different from failure at DNS itself.

**Comment by lmolkova** [comment]
So we need to add test for DSN issue.
However let's first decide if we need to fix it for EventSource.
Solution: track dependency when there was no begin event. 

Another problem: there will be begin after that and dependency will never be cleaned from the memorycache (unless there is some logic there already).

**Comment by cijothomas** [comment]
I was wrong when i mentioned there is no clean up in memorycache - there is auto cleanup after NN seconds.

**Comment by lmolkova** [comment]
> This tracks failed dependency.But the failure here is by connecting to google.com/404 which is different from failure at DNS itself.

It seems this test now fails in the develop. Probably google optimized 404 page and now we get EndRequest before Begin was completed
```
Event Name                                                                                   	Time MSec	Process Name                      	Rest  
Microsoft-ApplicationInsights-Extensibility-DependencyCollector/BeginCallbackCalled          	8,262.365	vstest.executionengine.x86 (43248)	ThreadID="32,400" FormattedMessage="Begin callback called for id = '9,223,372,032,603,626,225', name= 'http://google.com/404'" id="9,223,372,032,603,626,225" name="http://google.com/404" appDomainName="UnitTestAdapter: Running test" 
Microsoft-ApplicationInsights-Extensibility-DependencyCollector/EndCallbackCalled            	8,266.109	vstest.executionengine.x86 (43248)	ThreadID="52,176" FormattedMessage="End callback called for id = '9223372032603626225'" id="9223372032603626225" appDomainName="UnitTestAdapter: Running test" 
Microsoft-ApplicationInsights-Extensibility-DependencyCollector/EndCallbackWithNoBegin       	8,266.244	vstest.executionengine.x86 (43248)	ThreadID="52,176" FormattedMessage="End callback - cannot find start of operation for id = '9223372032603626225'" id="9223372032603626225" appDomainName="UnitTestAdapter: Running test" 
Microsoft-ApplicationInsights-Extensibility-DependencyCollector/RemoteDependencyModuleVerbose	8,278.175	vstest.executionengine.x86 (43248)	ThreadID="32,400" FormattedMessage="[msg=RemoteDependencyModule verbose.];[msg=store 9223372032603626225]" msg="store 9223372032603626225" appDomainName="UnitTestAdapter: Running test" 
```

**Comment by lmolkova** [comment]
fixed with #557

**Comment by lmolkova** [comment]
I was too quick to close it. It is still the issue with faulted requests or quick non success response.

**Comment by Dmitry-Matveev** [comment]
@lmolkova , can it be related to empty body requests (may qualify as quick non success responses)? #739

**Comment by lmolkova** [comment]
@Dmitry-Matveev successful requests (those that resulted in a response of any kind) are collected even without body, so I don't think so.
 The problem here is order of the callbacks in the .NET HTTP  code as it sends request event after the response. 

Event Source is now used for http tracking only in 2.3 and earlier, and for customers who explicitly disabled diagnostic source. So I wonder if it makes sense to keep this issue open

**Comment by Dmitry-Matveev** [comment]
If that's the case, closing as obsolete.
