### ISSUE TITLE
Diagnostic Source Dependency Collector misses dependency calls triggered by WebRequest.CreateHttp and not disposed

### ISSUE THREAD

**Issue by cijothomas** [Microsoft/ApplicationInsights-dotnet-server#551]
This is the code used for making HTTP dependency. (intentionally **not** disposing)
private void CallHttp()
        {
            Uri perftext = new Uri("http://bing.com");
            HttpWebRequest request = WebRequest.CreateHttp(perftext);
            var respo = request.GetResponse();
        }

With FrameWorkEventSource, AI will collect this dependencies just fine.
With DiagnosticSource (enabled by default in 2.4-betas)m AI will not collect the dependencies where request is not disposed. This was already listed as a limitation of DiagnosticSource - but we need to find a way to make the behavior same as previous SDK versions.

Also, if the above dependency call was a failing one, then AI collects this dependency as 'failed' calls are not dealt with by DiagnosticSource but via Framework Event Source. However I find that in this case the version prefix is  'rddf' , but its 'rdddsd' instead which is also incorrect.
![image](https://cloud.githubusercontent.com/assets/5232798/25759716/7b6ccce4-3188-11e7-9e08-58e85ca18d77.png)

With profiler we would be collecting all the above and correct prefixes.

**Comment by lmolkova** [comment]
1. Not disposed requests.

 I might be wrong but the assumption is that for .NET45, 46 and 47 we will not be able to detect that request was not disposed in DiagnosticSource. For future releases we will have another solution where we can address it in .NET Framework

My assumption is that majority of customers should use HttpClient. Majority of others that use WebRequests, read the response and/or dispose them properly. Of course, it is VERY good to know that request was not disposed and track dependency for this request.

Possible mitigations: 
* We can disable HTTP Desktop hook for **.NET45** where number of people using WebRequests is probably still high. 

*  We can try to detect that there is a Dependency that was there for longer than timeout setup on WebRequest and never was tracked and report it. It will help customers to know that they have requests that are not disposed. It should be very well thought out

**Comment by lmolkova** [comment]
2, SDK version. 
I'd say it's a grey zone: Start was tracked by rdddsd, stop done by rddf. If success is false, we always know that it was a framework event source, otherwise it is always DiagnosticSource hook.
I'm fine with changing it to rddf, should be easy. However I do not think it is critical.

**Comment by cijothomas** [comment]
Yes - agree on SDK version that its a grey area- lets keep rddsd as it started the collection.

**Comment by MS-TimothyMothra** [comment]
@Dmitry-Matveev wants to discuss this issue as a team

**Comment by lmolkova** [comment]
For users who use (Http)WebRequests and do not dispose the responses, we recommend using StatusMonitor to track trier Http dependency calls. [Here is more info on it](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-monitor-performance-live-website-now).

I'm closing this issue, please reopen if needed or create another one
