### ISSUE TITLE
Dependency telemetry does not expose the HTTP request method used

### ISSUE THREAD

**Issue by david-jarman** [Microsoft/ApplicationInsights-dotnet-server#552]
Dependency telemetry shows the URL but does not contain information about which request method was used.

For instance, my application could make a call to a wikipedia article like this: 
`GET https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol HTTP/1.1`

The dependency telemetry would show `en.wikipedia.org` for the target column and `https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol` for the data column. But nowhere would I be able to see the request method, "GET".

Having the request method would allow me to slice apart requests to the same URL, but with different request methods. The scenario I am looking to target is calls to Azure Table storage. We make a request to the table with a partition key and row key. If we get a 404 in response, then we create the row. Without the request method, these calls look the same and it could lead us to believe that we have duplicate calls to storage, when in reality, each call is doing something different (get, create, update, delete).

Request telemetry does have this info in the `Name` column.

**Comment by cijothomas** [comment]
If you install StatusMonitor or enable Application Insights extension in Azure webapp, the verb (GET/POST etc), will be collected.
Also, starting with 2.4.0-beta3 - verb would be collected out of the box. This will be released today/tomorrow.
