### ISSUE TITLE
Support netcoreapp/netstandard

### ISSUE THREAD

**Issue by jamiewest** [Microsoft/ApplicationInsights-dotnet-server#565]
I have been trying to enable live metrics for my ASP.NET Core site running on linux. I am coding using VS Code, are there plans to support .NET Core or netstandard so we can run on other platforms that don't require full framework?

**Comment by SergeyKanzhelev** [comment]
Yes, there are plans. We tracking this feature request https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/216 The only commitment wrt timeframe is this calendar year.
