### ISSUE TITLE
Azure Storage SDK "chunking" affects AI context tracking

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#57]
If you e.g. upload a non-trivial blob in Azure (I think > 4mb), the Azure SDK chunks up the data into multiple requests of 4mb each.

In AI, the first "chunk" correctly shows as a dependency within the context of the request, but the remainder have no operation id (or parent operation id) so they appear as orphaned entries within AI. They should all have the correct operation id.

Copy of https://github.com/Microsoft/ApplicationInsights-Home/issues/38 from @isaacabraham

**Comment by Dmitry-Matveev** [comment]
Let's validate if this still the case or just close.

**Comment by MS-TimothyMothra** [comment]
everyone agrees this should be fixed, but two people couldn't repo. deferring to Future.

**Comment by SergeyKanzhelev** [comment]
I believe it was addressed with the AsyncLocal support. Closing
