### ISSUE TITLE
Testing .NET Core 2.0 DependencyCollector

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet-server#572]
We have code that is specific for .net core 2.0 runtime (in DependencyCollector.NetCore). 
Testing it requires dotnet core 2.0 runtime and tools in build infra.

Unit tests for [DependencytracingModule on core](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/NetCore.Tests/DependencyTrackingTelemetryModuleTestNetCore.cs) should also run on 2.0 with additional checks for [IsEnabled](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/60c03242a6df027f0acbacc5487bb0d8747e1c92/Src/DependencyCollector/Shared/Implementation/HttpCoreDiagnosticSourceListener.cs#L426)

**Comment by dnduffy** [comment]
Does that mean no support for 1.0.* anymore or is the 2.0 code #ifdef'ed?

**Comment by lmolkova** [comment]
it's the code that listens to events that fired on .NET Core 2.0 only. DepCollector still targets netstandard 1.6 and there are no ifdefs, but the logic for 2.0 just lights up when user has 2.0 runtime

**Comment by dnduffy** [comment]
Excellent. :)
