### ISSUE TITLE
Tracking async HTTP dependencies in ASP.NET

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#58]
All of our async HTTP requests are reporting as taking microseconds to execute when they are actually taking 1-30 seconds.

```csharp
var address = new Uri("http://foo.bar");
var content = new StringContent("{'foo': 'bar'");
content.Headers.ContentType = new MediaTypeWithQualityHeaderValue("application/json");
var response = await new HttpClient().PostAsync(address, content);
```

Non-async HTTP requests have accurate timings.  This is on a server running IIS with the status monitor configured.

Copy of https://github.com/Microsoft/ApplicationInsights-Home/issues/27 from @gregjhogan. See more comments there

**Comment by abaranch** [comment]
It is related to not collecting time of chunked content. I created an issue #62 to start supporting it.
Currently workaround would be to add operation manually that would have correct timing:

```
using (var op = this.telemetryClient.StartOperation<DependencyTelemetry>("dependency"))
            {
                new HttpClient().GetStringAsync("http://bing.com");
            }
```

Note that in this case there will be 2 dependencies: 1 tracked from operation with correct timing and one autocollected. Also if you think it is more convenient operation can be tracked as request like this:

```
using (var op = this.telemetryClient.StartOperation<RequestTelemetry>("request"))
            {
                new HttpClient().GetStringAsync("http://bing.com");
            }
```
