### ISSUE TITLE
”Available memory“ performance counter should be supported in Azure Web Apps. 

### ISSUE THREAD

**Issue by cocoyilu** [Microsoft/ApplicationInsights-dotnet-server#585]
Performance counter "available memory" is not available in ""servers" blade.
While this data is necessary for analysis to many users.
Therefore, it would be highly appreciated if this feature can be enabled.
![image](https://cloud.githubusercontent.com/assets/15134194/26210082/2f37b53e-3c21-11e7-881e-9ffcff2dc2c5.png)

**Comment by SergeyKanzhelev** [comment]
Available memory performance counter indicates how much disk space left. There is another counter for RAM used by application.

What is the scenarios when you need available disk space counter? Is your application running out of local storage?

**Comment by SergeyKanzhelev** [comment]
From Azure Web Apps team:

>I have added a new app counter called `availMemoryBytes` (it is part of the `app` counters).  The change is checked in and will deploy in about 3-4 weeks.  

We will need to adopt this change in our SDK to pick up this counter. One complication here is it's unclear how SDK will behave when trying to access JSON string that is not yet exists. Will it send value with zero value or report and error?

**Comment by SergeyKanzhelev** [comment]
I'll close this task once validation of it will complete. Need to wait a few weeks for the feature being deployed into production by Azure Web App team

**Comment by MS-TimothyMothra** [comment]
@cijothomas @SergeyKanzhelev I see that this was moved into the 2.6 milestone.
Do we have validation that Azure's fix has been deployed?

**Comment by SergeyKanzhelev** [comment]
Just checked - looks it wasn't enabled yet. Still waiting...

**Comment by SergeyKanzhelev** [comment]
Just validated - it works in Central US (at least).
