### ISSUE TITLE
Deadlock in TraceSource Initialization in Azure Web Site extension

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#591]
Copy of https://github.com/Microsoft/ApplicationInsights-dotnet/issues/428

**Comment by MS-TimothyMothra** [comment]
The bug 387336 is in .NetFramework version 4.7.0.
The fix was released with 4.7.1.
http://referencesource.microsoft.com/#System/compmod/system/diagnostics/Switch.cs

Also, ApplicationInsights no longer supports Net40 where this bug was discovered.
We believe it is safe to close this bug.
