### ISSUE TITLE
Microsoft-ApplicationInsights-Data/Request event is missing in 2.4 beta3 release

### ISSUE THREAD

**Issue by northtyphoon** [Microsoft/ApplicationInsights-dotnet-server#595]
I don't see the Microsoft-ApplicationInsights-Data/Request in the etl file. The profiler relies on the event to correlate the trace with the corresponding request telemetry event. It's a blocking issue.

**Comment by SergeyKanzhelev** [comment]
ever? Or under certain conditions?

**Comment by lmolkova** [comment]
Is there a corresponding RequestTelemetry? So is it only EventSource event missing or requests are not tracked at all?

**Comment by northtyphoon** [comment]
RequestTelemetry is emitted. Only the EventSource event is missing. I'm trying to create a simple repro.

**Comment by northtyphoon** [comment]
It turned out the issue is only reproed with a particular custom initialization of the Telemetry Pipeline.

The related the issue is tracked by 
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/549 

So I closed the bug.
