### ISSUE TITLE
Unwanted IIS restart on role environment changes in Azure Cloud Service

### ISSUE THREAD

**Issue by hermes-del-rondo** [Microsoft/ApplicationInsights-dotnet-server#605]
We're using Application Insights in our Azure Cloud Service (MVC + Web API). Every time a role environment change occurs (e. g. scale operation or configuration value change) IIS is restarted. After removing all AI references from the application IIS does no longer restart on role environment changes.
Because our application requires some time to warm up this is a bad experience for our customers. How can I prevent IIS from restarting on role environment changes?

Tested with AI 2.3.0 and 2.4.0-b3.

**Comment by SergeyKanzhelev** [comment]
Does your application read any configuration values from cscfg by itself? Do you handle configuration [changing events](https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-model-and-package#changing-the-configuration-of-a-role) in your application?

**Comment by hermes-del-rondo** [comment]
To reproduce this I created a new application using the Visual Studio MVC template. I added some logging to see what's going on and I added a handler to the `RoleEnvironment.Changed` event in the `Application_Start()` method. The event handler writes a log entry that contains the key of the changed configuration setting and the new value. This is the only place where `RoleEnvironment.GetConfigurationSettingValue()` is called or an event handler is added.

After changing a single value in Azure portal the change is logged, `Application_End()` gets called, and IIS is restarted. I can see it in the Windows Event Viewer (events from Service Control Manager, Microsoft-Windows-IIS-IISReset, and Microsoft-Windows-WAS). It's a real IIS service restart. It's not a recycled application pool or a restarted web role.

I also tested what's happening if `Cancel` is set to `true` in the `Changing` event: `WebRole.OnStop()` and `WebRole.OnStart()` is called, but IIS is not restarted.

**Comment by SergeyKanzhelev** [comment]
Thank you @hermes-del-rondo for details! We've been fixing https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/168 and introduced the new AppDomain creation on start to safely read the `RoleEnvironment` configuration settings. My current assumption is that `ServiceRuntime` thinks that this new AppDomain is a separate application that depends on configuration settings. So even when your app tells to not restart - `ServiceRuntime` will still do it.

If theory is correct - disabling of `<Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureRoleEnvironmentTelemetryInitializer, Microsoft.AI.WindowsServer"/>` in `Applicationinsights.config` will help.

It is just a working theory right now that we need to validate. @cijothomas what do you think?

**Comment by hermes-del-rondo** [comment]
If I remove `AzureRoleEnvironmentTelemetryInitializer` from `ApplicationInsights.config` the following error occurs:
![unable to find assembly system diagnostics diagnosticsource](https://cloud.githubusercontent.com/assets/23500690/26618800/fd6c8cfe-45db-11e7-9ff0-585d354fbe2a.PNG)
The `System.Diagnostics.DiagnosticSource.dll` file is present in the `bin` folder:
![grafik](https://cloud.githubusercontent.com/assets/23500690/26618975/c3c680e4-45dc-11e7-9797-045c94794e80.png)
Adding `AzureRoleEnvironmentTelemetryInitializer` again makes the error disappear.

**Comment by SergeyKanzhelev** [comment]
@cijothomas please take a look ASAP? Call stack looks scary

**Comment by cijothomas** [comment]
I am investigating.

**Comment by cijothomas** [comment]
So far not able to repro - tried with and without AzureRoleEnvironmentTelemetryInitializer, and changed Config values from portal - no restarts, no crash..
Btw - i tested with unreleased version 2.4.0-beta4.
Will try with 2.4.0-beta3.

@hermes-del-rondo Did you try removing AzureRoleEnvironmentTelemetryInitializer from ApplicationInsights.config for 2.3 SDK? System.Diagnostics.DiagnosticSource.dll dependency was newly added in 2.4.0-betas..

**Comment by hermes-del-rondo** [comment]
@cijothomas I tested with 2.4.0-beta3.

With 2.3.0 there was no exception. Here is what I did with AI 2.3.0 in the last hour:

* Deployed demo project with full AI 2.3.0 on existing cloud instance
* Connected via RDP
* My log output:
  `2017-05-31 20:47:14Z - WebRole.OnStart()`
* Loaded web page (successfully)
* My log output:
  `2017-05-31 20:52:15Z - Entering MvcApplication.Application_Start()`
  `2017-05-31 20:52:20Z - Leaving MvcApplication.Application_Start()`
* Changed setting "Test" to "Value1" in the portal
* My log output:
  `2017-05-31 20:55:02Z - Setting 'Test' changed. The new value is 'Value1'.`
  `2017-05-31 20:55:14Z - MvcApplication.Application_End()`
* Loaded web page (successfully)
* My log output:
  `2017-05-31 20:56:12Z - Entering MvcApplication.Application_Start()`
  `2017-05-31 20:56:12Z - Leaving MvcApplication.Application_Start()`
* Commented `AzureRoleEnvironmentTelemetryInitializer` in `ApplicationInsights.config` using notepad
* Recycled application pool in IIS to restart the application
* My log output:
  `2017-05-31 20:59:38Z - MvcApplication.Application_End()`
* Loaded web page (successfully)
* My log output:
  `2017-05-31 21:00:33Z - Entering MvcApplication.Application_Start()`
  `2017-05-31 21:00:34Z - Leaving MvcApplication.Application_Start()`
* Changed setting "Test" to "Value2" in the portal
* My log output:
  `2017-05-31 21:03:31Z - Setting 'Test' changed. The new value is 'Value2'.`
  `2017-05-31 21:03:42Z - MvcApplication.Application_End()`
* Loaded web page (successfully)
* My log output:
  `2017-05-31 21:04:39Z - Entering MvcApplication.Application_Start()`
  `2017-05-31 21:04:40Z - Leaving MvcApplication.Application_Start()`
* Also removed `AzureWebAppRoleEnvironmentTelemetryInitializer` in `ApplicationInsights.config` with the same result.

I attached my demo project and the IIS reset events from the event log. The `APPINSIGHTS_INSTRUMENTATIONKEY` and the diagnostics connection string were removed in the uploaded project.

[IIS reset events.zip](https://github.com/Microsoft/ApplicationInsights-dotnet-server/files/1042987/IIS.reset.events.zip)
[Demo.zip](https://github.com/Microsoft/ApplicationInsights-dotnet-server/files/1042986/Demo.zip)

**Comment by cijothomas** [comment]
I used similar logic to log events as Demo.zip
From my log output, I don't see application IISRestarts. 
2017-05-31 22:47:26Z - WebRole.OnStart()
2017-05-31 22:50:11Z - Entering MvcApplication.Application_Start()
2017-05-31 22:50:11Z - Leaving MvcApplication.Application_Start()
2017-05-31 22:56:50Z - Setting 'CijoAnotherTestKey' changed. The new value is 'anothertestvalue22'.
2017-05-31 23:05:43Z - Setting 'CijoTestKey' changed. The new value is 'testvalue22'.
2017-05-31 23:19:48Z - Setting 'CijoTestKey' changed. The new value is 'cijonewvalue'.


(In my earlier application, i verified the same by looking at w3wp process id, which never changed when config updated)

**Comment by hermes-del-rondo** [comment]
The problem seems to be related to the `MSVSAZ-CloudServiceRecycle-WAD11-1` cloud service extension which is added when deploying using Visual Studio. The IIS restart occurs when the `MSVSAZ` extension **and** AI are present. After removing the extension from the cloud service there were no more IIS restarts.

Test results:

| AI | MSVSAZ extension | IIS restart |
|---|---|---|
| present | present | **yes** |
| not present | present | **no** |
| present | not present | **no** |
| not present | not present | **no** |

**Comment by SergeyKanzhelev** [comment]
@nizarq do you know why WAD extension forces IIS restart on configuration change?

**Comment by SergeyKanzhelev** [comment]
@hermes-del-rondo do you remember more details on how you get the error of loading the `DiagnosticsSource` assembly? Was it a packaging issue by chance? We cannot repro it.

**Comment by nizarq** [comment]
yes - because we reinstall the status monitor and enable it. Doing that requires an IIS restart.

**Comment by SergeyKanzhelev** [comment]
@nizarq do you re-install Status Monitor after every configuration value change?

@cijothomas can you please try it and see whether WAD extension can cause problems with DiagnosticSource not being loaded?

**Comment by nizarq** [comment]
@SergeyKanzhelev - yes for now the code is agnostic. It doesn't detect whether or not the enable is called because there is a new version of extension (possibly with an update for status monitor) or it is due to something benign. So it takes the safe route of uninstalling the current bits and installing whatever's in the current package. 

The assumption at the time of writing the code was that writing cloud applications, the customer should always have multiple instances so that an IIS reset, which can happen anytime for any reason (guest agent update, VM restart etc. etc.), wouldn't cause an outage. Any configuration update is a deployment update which will be rolled through fault domains so that even if iis reset is caused on a few VMs, others will be available to take the load and the service won't be down.

We have recently been hearing about complaints about this with scale up, because in case of scale up, you clearly have more traffic that you can handle and doing an IIS reset as part of that scale up hurts the service even badly. We will probably do something about it in the near future, stay tuned.

I don't know why would there be a DiagnosticSource issue though - Have you guys compared the .net framework versions? Could it be that the machine on which there is a crash, has an older .net framework installed which doesn't support diagnostics source?

**Comment by hermes-del-rondo** [comment]
@SergeyKanzhelev I was able to reproduce it although the exception is slightly different.

* Tested AI versions: 2.4.0-beta3, 2.4.0-beta4
* Tested System.Diagnostics.DiagnosticSource version: 4.4.0-preview2-25330-01
* Disabled `AzureRoleEnvironmentTelemetryInitializer` in `ApplicationInsights.config`
![grafik](https://cloud.githubusercontent.com/assets/23500690/26713793/a6355440-476e-11e7-909a-353fd9f395ee.png)

Exception:
![grafik](https://cloud.githubusercontent.com/assets/23500690/26713806/b6e8eaf4-476e-11e7-9209-592bcc9a9ee6.png)

After re-adding `AzureRoleEnvironmentTelemetryInitializer` the exception was gone.

**Comment by SergeyKanzhelev** [comment]
@hermes-del-rondo after commenting out - do you deploy as a new cloud service or you update existing? Or perhaps just change file in-place?

**Comment by hermes-del-rondo** [comment]
@SergeyKanzhelev I tried multiple combinations.

* Deployed on new server instance without `AzureRoleEnvironmentTelemetryInitializer` -> error
* Deployed on new server instance with `AzureRoleEnvironmentTelemetryInitializer` -> OK
* Updated deployment on existing server instance without `AzureRoleEnvironmentTelemetryInitializer` -> error
* Updated deployment on existing server instance with `AzureRoleEnvironmentTelemetryInitializer` -> OK
* Edited in-place via RDP and recycled application pool -> error without initializer, OK with initializer

**Comment by lmolkova** [comment]
I'll have a look into  System.Diagnostics.DiagnosticSource not found and Activity SerializationException.
Activity is serializable and adding/removing AzureRoleEnvironmentTelemetryInitializer cannot affect it, so may be there is some weird side-effect. 

@hermes-del-rondo
- which version of .NET your application targets? 
- which is the highest version of .NET is installed on the machine where the issue reproduces?

**Comment by lmolkova** [comment]
Indeed, there is a problem with DiagnosticSource 4.4.0-preview2-25330-01. https://github.com/dotnet/corefx/pull/19742 that would cause SerializationException when there is cross AppDomain call. Probably presence of `AzureRoleEnvironmentTelemetryInitializer` affects it somehow.

@hermes-del-rondo
Could you please try 4.4.0-preview1-25214-03 version of DiagnosticSource?

**Comment by hermes-del-rondo** [comment]
@lmolkova Here are the versions.
OS: Windows Server 2016 Version 1607 (OS Build 14393.1197)
.NET target version: 4.5.2
Latest installed .NET version: 4.6.2

**Comment by hermes-del-rondo** [comment]
@lmolkova This happens with version 4.4.0-preview1-25214-03 of DiagnosticSource:
![grafik](https://cloud.githubusercontent.com/assets/23500690/26817541/4f0e7cba-4a97-11e7-827a-4792be14f2a2.png)
Just as before the assembly is present in the bin directory.

**Comment by lmolkova** [comment]
@hermes-del-rondo Thanks a lot!
I was able to reproduce the issue and created another bug to track it: #613. You may find some details and workarounds there. We will see how we can properly fix it. Please let me know if workarounds don't work for you.

**Comment by AlexBulankou** [comment]
Discussed and decided to be external WAD issue.

**Comment by SergeyKanzhelev** [comment]
@nizarq do you track this issue anywhere? It is clearly a bug if WAD forces the restart

**Comment by nizarq** [comment]
@SergeyKanzhelev, I already have a fixed under code review. This will be fixed when the next version is released.
