### ISSUE TITLE
Intercept inserts the wrong method callback for ref arguments

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#618]
Issue reported by CLR team:

The problem is related to the profiler that App Insights is using to instrument certain request processing codepaths.  The profiler is causing trouble because it is doing the following:

- It is re-JIT'ing the `System.Net.HttpWebRequest.GetRequestStream(System.Net.TransportContext ByRef)` method, the goal being to (maybe among other things) add a callout which runs at the very start of each call into the function.
- The call targets a profiler-generated function, which in practice will call through to `Microsoft_AI_DependencyCollector!Microsoft.ApplicationInsights.DependencyCollector.Implementation.ProfilerHttpProcessing.OnBeginForGetRequestStream` each time `HttpWebRequest.GetRequestStream` runs.

- Each time it runs the added callout, the re-JIT'ed `GetRequestStream` code passes the incoming `ref TransportContext` argument as the 3rd argument to the callout.

- That said, the profiler-generated function targeted by the callout has a mismatched signature `[DEFAULT] Object (I4,Object,Object)`.  In particular, acting like the 3rd argument is of type `Object` when it is really of type `ref TransportContext` leads to invalid GC reporting, which leads to the potential of crashes whenever GC happens to occur while the profiler-generated function is on the stack.

**Comment by iusafaro** [comment]
Fixed in Intercept nuget 2.4
