### ISSUE TITLE
Do we still monitor applicaitons running the classic pipeline?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#623]
We register our module for both – classic and integrated pipeline. See: http://apmtips.com/blog/2014/12/02/tracking-static-content-with-application-insights-httpmodule/ where I mentioned it.

This raises question to me – how monitoring will work on classic pipeline since telemetry correlation module doesn’t support it. 

answer to @dnduffy's:

> On a brand new classic .NET MVC web project I get `ApplicationInsightsWebTracking` and `TelemetryCorrelationHttpModule` as the only modules in `Web.config` by default with 2.4.0-beta5 of the SDK’s.
>e.g.

``` xml
    <system.web>
      <httpModules>
        <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" />
      </httpModules>
    </system.web>
```

>and

``` xml
    <system.webServer>
      <modules>
        <add name="TelemetryCorrelationHttpModule" type="Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule, Microsoft.AspNet.TelemetryCorrelation" preCondition="integratedMode,managedHandler" />
        <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />
      </modules>
    </system.webServer>
```

> @SergeyKanzhelev Should the template be including `ApplicationInsightsHttpModule` for new projects?

**Comment by dankellett** [comment]
I missed this precondition and spent a lot of time trying to figure out why my application wasn't reporting to AI. Did you get an answer?

**Comment by SergeyKanzhelev** [comment]
@dankellett yes, I enabled tests for classic pipeline and everything works. You need to insert http module to `web.config` manually though

**Comment by SergeyKanzhelev** [comment]
@SethPatrich have you added `TelemetryCorrelationHttpModule` under `system.web\httpModules`?
