### ISSUE TITLE
[Proposal] Refactoring Request and Dependency tracking telemetry modules to make protocol independent abstract base classes

### ISSUE THREAD

**Issue by nizarq** [Microsoft/ApplicationInsights-dotnet-server#626]
I am looking into what it would take to do automatic dependency and request tracking for [Service Fabric Service Remoting](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting). You can see the relevant proposed item here: https://github.com/Microsoft/ApplicationInsights-ServiceFabric/issues/14

The implementation for Service Remoting modules should probably best live in the https://github.com/Microsoft/ApplicationInsights-ServiceFabric repository as service remoting is service fabric specific. However, it feels like beside the protocol specific detail, everything (e.g., appId logic, CacheBasedOperationHolder etc.) would be same and need to be duplicated. 

What do you guys thing about the prospect of abstracting out non-protocol specific logic in the request and target telemetry modules and move them as abstract classes in https://github.com/Microsoft/ApplicationInsights-dotnet (and the corresponding MS.AI nuget package). Both SF specific and Web nugets can then take dependencies on MS.AI nuget package and have http and service remoting protocol specific implementations respectively.

**Comment by nizarq** [comment]
@SergeyKanzhelev @Dmitry-Matveev @brahmnes

**Comment by SergeyKanzhelev** [comment]
Is it what `StartOperation<RequestTelemetry>` designed for? Ultimately you need to start and stop a request telemetry and populate it with the few extra platform-specific properties. What specifically do you want to generalize on top of it?

**Comment by nizarq** [comment]
Some things that can be shared implementation - to list a few - are: 
- [Fetch app Id utility](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/Common/CorrelationIdLookupHelper.cs)
- [Utility for storing and retrieving telemetry objects in memory between start and stop operations](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/Operation/CacheBasedOperationHolder.cs)
- [Plumbing related to configuration that makes sense for all request / dependency telemetry modules](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/DependencyTrackingTelemetryModule.cs#L50-L95). Some properties have HTTP in their name but it's not hard to have common protected properties that can be shared and different public ones that are conceptually equivalent that feed into the same protected properties.

**Pro**
Easier to update. If we want a change in behavior for say (x-component) correlation, we just update one place and update the nuget package dependency.

**Con**
Harder to release. AI.SF would start depending on base package for major functionality that it primarily provides. In order to update AI.SF, we will have to align with a base AI nuget package release.

I personally, like flexibility and ease to release independently a little more than code duplication as I know it has  been a little bit of a challenge to take so many sdk component along and align them for releases. So my vote is for not doing it but I just want to make sure this is discussed and considered before I send out a major PR and people start complaining about duplication.

**Comment by Dmitry-Matveev** [comment]
@nizarq, I see we implemented the proposed PR in SF code, do we need to keep this issue open to further discuss the API base provide or we can close this one?

**Comment by nizarq** [comment]
I think it's fine to close it for now. If I get back to this area and still think a refactor is required. I can open this again and we can take care of it then.
