### ISSUE TITLE
Sql Dependency Tracking

### ISSUE THREAD

**Issue by AnithaLingam** [Microsoft/ApplicationInsights-dotnet-server#635]
Hi,
Please provide how to track SQL and other dependency tracking by using Application Insights for .Net

**Comment by cijothomas** [comment]
Please go through the docs:
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net-dependencies

SQL Dependencies are tracked automatically. For more detailed tracking (including SQL procedure name/query etc), install StatusMonitor/Azure Extension.

**Comment by cijothomas** [comment]
Please re-open, if you have more specific questions.

**Comment by kr4ster** [comment]
Apologies for re-opening this..  I've attempted the above with my Azure App Service (running a aspnet dotnet core 2 app) and am not seeing telemetry for sql server.  I see other data (ajax requests, httpclient requests, and the application in general).  Here's what my extensions window looks like:

![image](https://user-images.githubusercontent.com/456710/33285098-4c9cc682-d37f-11e7-84f1-82539786d880.png)

Is there anything else that I need to do to get this telemetry?

Thanks!
Bobby

**Comment by cijothomas** [comment]
Yes, for asp.net core apps, sql dependencies are collected from 2.2.0-beta1 version only. Update your application to this beta version to get sql dependencies.

You can add the following to your .csproj to get this version.
```
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.2.0-beta1" />
```
