### ISSUE TITLE
Turn on/off TrackTrace() with certain SeverityLevel at runtime?

### ISSUE THREAD

**Issue by leftside** [Microsoft/ApplicationInsights-dotnet-server#636]
With tools like NLog and Log4Net I can just have logging statements with severity levels of Error being logged in production. If an error occurs, I can turn-up the severity level by configuration and start to log Debug or Verbose statements.

Can something similar be achieved with App Insights? Or will something like the following always be logged, and the only way to filter out these trace statements is to use a custom search?
telemetry.TrackTrace("debug trace", SeverityLevel.Verbose);

Ideally I'd like to be able configure whether the SeverityLevel of Critical, Error, Information, Verbose, Warning actually get logged.

**Comment by SergeyKanzhelev** [comment]
Discussed here: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/487
