### ISSUE TITLE
AppInsights 2.4.0 breaks access to Azure Storage emulator 5.1.0.0

### ISSUE THREAD

**Issue by rwwilden** [microsoft/ApplicationInsights-dotnet-server#640]
When using Azure Storage emulator 5.1.0.0 in combination with AppInsights 2.4.0, all access to storage results in _403: Forbidden_ errors.

I attached a small (VS2015) console application that demonstrates this behavior.

[StorageEmulatorAccess.zip](https://github.com/Microsoft/ApplicationInsights-dotnet-server/files/1124218/StorageEmulatorAccess.zip)

**Comment by cijothomas** [comment]
Can you try modifying AI.Config adding this line inside DependencyTrackingTelemetryModule?
<SetComponentCorrelationHttpHeaders>false</SetComponentCorrelationHttpHeaders>

Sample:
<Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">
			<ExcludeComponentCorrelationHttpHeadersOnDomains>
				
				<Add>core.windows.net</Add>
				<Add>core.chinacloudapi.cn</Add>
				<Add>core.cloudapi.de</Add>
				<Add>core.usgovcloudapi.net</Add>
			</ExcludeComponentCorrelationHttpHeadersOnDomains>
            <SetComponentCorrelationHttpHeaders>false</SetComponentCorrelationHttpHeaders>
		</Add>

**Comment by cijothomas** [comment]
![image](https://user-images.githubusercontent.com/5232798/27878927-cdca63e0-6174-11e7-8294-27559ebcf3df.png)
Sample.

**Comment by rwwilden** [comment]
This works. And a better work-around than the one I came up with.

But I guess this disables (part of) dependency tracking for all domains? Not just localhost?

**Comment by rwwilden** [comment]
I did some more research and the following code is more selective in disabling dependency tracking:

    #if DEBUG
      var telemetryModules = TelemetryModules.Instance;
      var dependencyTrackingTelemetryModule =
          telemetryModules.Modules.OfType<DependencyTrackingTelemetryModule>().SingleOrDefault();
      dependencyTrackingTelemetryModule?
          .ExcludeComponentCorrelationHttpHeadersOnDomains
          .Add("127.0.0.1");
    #endif

**Comment by cijothomas** [comment]
You can simply add"127.0.0.1" to the list in AI.Config itself. (it already has core.windows.net etc).

**Comment by cijothomas** [comment]
Reopening as this needs to discussed - if this is serious enough, then a hotfix release maybe needed.

**Comment by rwwilden** [comment]
I think it's a real issue that an external component (AI) can break access to something that should be completely unrelated. It took me quite some time to figure out what was causing 403 errors against Azure Storage emulator.

**Comment by cijothomas** [comment]
Will release a hotfix to adress this tomorrow.

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet-server/releases/tag/v2.4.1 Released hotfix 2.4.1.

**Comment by kieronlanning** [comment]
@cijothomas Do you know when this is likely to hit NuGet?

**Comment by pharring** [comment]
@kieronlanning It's already there. https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web

**Comment by kieronlanning** [comment]
@pharring What about .NET Core? I've had to roll back to the previous versions for now...

**Comment by pharring** [comment]
2.1.1 of ASP.NET Core is expected later today, I believe.

**Comment by kieronlanning** [comment]
Wicked, thanks.

**Comment by sikemullivan** [comment]
Just wasted lost 6 hours wondering what the heck was causing this. Can you guys explain why this is occurring in more detail. 

Here's the full error for google to index. 
"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature."

**Comment by jadesai** [comment]
Can we re-open this? This is happening for non-emulator accounts as well in AppInsights.Web 2.5.1

**Comment by SergeyKanzhelev** [comment]
@jadesai what application type are you using? Is it ASP.NET Classic or ASP.NET Core? If classic - can you confirm that ApplicationInsights.config has all the settings we discussed in this issue present?

**Comment by jadesai** [comment]
ASP.NET Classic + .NET Standard. @SergeyKanzhelev the config change seemed to have worked, but is that supposed to be the long term fix? If so, can we outline that here: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net-dependencies 

The error is not intuitive so it would be better since I am sure multiple people running into this don't necessarily realize it.

**Comment by lmolkova** [comment]
@SergeyKanzhelev 
I wonder can we remove 'x-ms-request*' headers that cause the issue on the low level? This would eliminate the issue completely on any config. Headers are supported for backward-compatibility with 2.3- versions of the AI SDK.

**Comment by SergeyKanzhelev** [comment]
The only blocker so far was JavaScript. If @iusafaro finished with with transition I think we should. Think what instructions we can give customers to enable interior. Ideally as external code, not a flag in SDK

**Comment by SergeyKanzhelev** [comment]
This may be a good start. In any case check with Yulia. Maybe we can make a bigger change right away

**Comment by cijothomas** [comment]
closing as not relevant with migration to requestid and w3c headers instead of x-ms..
