### ISSUE TITLE
Cloud_RoleInstance property not populated for some web requests

### ISSUE THREAD

**Issue by nidewa** [Microsoft/ApplicationInsights-dotnet-server#641]
We are seeing an issue that the Cloud_RoleInstance property is not being populated for some of the web application requests. 
Our web service setup has 4 IIS server nodes and an Azure load balancer . We are using Application Insights SDK to log telemetry for our web service. Same code resides on all the server nodes, and this property is populated correctly for most of the logs, but in some telemetry logs this property is not populated.
Any references/help is appreciated.

Let me know if you have any questions.
Thanks.

Attached screenshot shows all the Application Insights dll versions.
![appinsightsissue](https://user-images.githubusercontent.com/29931952/27889313-5b8c22ce-61a0-11e7-9083-a0a313a03cd6.JPG)

**Comment by cijothomas** [comment]
We have fixed this issue:
https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/168

You'll need to use SDK version 2.2 or higher to get this fix. It looks like you are in 2.1 version. Can you try updating?

**Comment by cijothomas** [comment]
Please re-open if you hit the issue after upgrading.
