### ISSUE TITLE
When custom domain used for azure storage - SDK breaks signature

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet-server#652]
Reported by customer:

>Customer is using Application Insights SDK for .net together with Azure Storage SDK. When he uses customer domain in storage connection string, the Storage API calls will fail with invalid signature error due to two additional headers (x-ms-request-root-id and x-ms-request-id) added by AI. Whereas using blob.core.windows.net works because AI excluded this URL. Customer has workarounded the issue by adding his custom domain to AI config for exclusion. But he asks for documentation in both Storage SDK and Application Insights SDK regarding this.

**Comment by cijothomas** [comment]
no longer relevant as we dont use x-ms based headers by default.
