### ISSUE TITLE
Make DeveloperModeWithDebuggerAttachedTelemetryModule public

### ISSUE THREAD

**Issue by ohadschn** [Microsoft/ApplicationInsights-dotnet-server#653]
Currently it is internal so I cannot do this: 
``` TelemetryModules.Instance.Modules.Add(new DeveloperModeWithDebuggerAttachedTelemetryModule());```

**Comment by SergeyKanzhelev** [comment]
Oh, this is bad. Everything in config should be public. Would you be OK to create a PR?

**Comment by ohadschn** [comment]
That depends, will I have to actually check it or can I just change it to `public` and submit? :)

**Comment by SergeyKanzhelev** [comment]
make it public and make sure compiles in `Release` & tests passes =)
