### ISSUE TITLE
Start Timestamp is not set for Http dependency telemetry in dotnet core 2.0

### ISSUE THREAD

**Issue by zhencui** [Microsoft/ApplicationInsights-dotnet-server#658]
Telemetry object is created in onActivityEnd. And the timestamp is never assigned, which will be the timestamp of onActivityEnd by default. The timestamp is supposed to be the start time.

https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/HttpCoreDiagnosticSourceListener.cs#L208

**Comment by SergeyKanzhelev** [comment]
Also related to https://github.com/Microsoft/ApplicationInsights-dotnet/issues/587
