### ISSUE TITLE
Failure in Telemetry Initializers: Could not load "Microsoft.AspNet.TelemetryCorrelation"

### ISSUE THREAD

**Issue by Dmitry-Matveev** [Microsoft/ApplicationInsights-dotnet-server#671]
Telemetry initializers in AI Web SDK including but not limited to `Microsoft.ApplicationInsights.Web.OperationCorrelationTelemetryInitializer` fail with `FileNotFoundException` on loading `Microsoft.AspNet.TelemetryCorrelation, Version 1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`

![image](https://user-images.githubusercontent.com/12158043/29476770-65166ee8-841a-11e7-9ef8-2e513dacd697.png)

**Comment by lmolkova** [comment]
AppInsights requires TelemetryCorrelation assembly: there is dependency in Web nuspec.
The assumption is that some customer(s) did not want to have http module and request tracking at all, so they manually removed the module AND TelemetryCorrelation.dll.


Would be great to know number of customers affected to verify the assumption.

**Comment by ZeeshanFastian** [comment]
There is nuget package available "Microsoft.AspNet.TelemetryCorrelation". Install the package and publish the site again. It will fix the problem.

**Comment by cijothomas** [comment]
![image](https://user-images.githubusercontent.com/5232798/32682990-c74adbea-c62c-11e7-875e-af9133b49e31.png)
Please update the nuget package manager to latest in visual studio. I have had a similar issue System.Diagnostics.Diagnosticsource package which is a dependent package of AspNet.TelemetryCorrelation.

**Comment by lmolkova** [comment]
@cijothomas 

Any public nuget release higher than 2.8.6 should work: https://github.com/dotnet/corefx/issues/23843

With 2.8.6  and lower, it won't be possible to install AI SDK at all  (as it would not be possible to install DiagSource), so perhaps this issue could not be caused by the nuget version.
