### ISSUE TITLE
Performance counter can not be read in Windows Container

### ISSUE THREAD

**Issue by shibayan** [microsoft/ApplicationInsights-dotnet-server#676]
I installed App Insights on an ASP.NET application running on Windows Containers, but the performance counter value is outputted with the following error message and can not be read.

```
AI: Error collecting 10 of the configured performance counters. Please check the configuration.
Counter \Process(??APP_WIN32_PROC??)\% Processor Time: Failed to perform the first read for performance counter. Please make sure it exists. Category: Process, counter: % Processor Time, instance 
Counter \Process(??APP_WIN32_PROC??)\% Processor Time Normalized: Failed to perform the first read for performance counter. Please make sure it exists. Category: Process, counter: % Processor Time Normalized, instance 
Counter \Memory\Available Bytes: Failed to register performance counter. Category: Memory, counter: Available Bytes, instance: .
Counter \ASP.NET Applications(??APP_W3SVC_PROC??)\Requests/Sec: Failed to perform the first read for performance counter. Please make sure it exists. Category: ASP.NET Applications, counter: Requests/Sec, instance _LM_W3SVC_1_ROOT
Counter \.NET CLR Exceptions(??APP_CLR_PROC??)\# of Exceps Thrown / sec: Failed to perform the first read for performance counter. Please make sure it exists. Category: .NET CLR Exceptions, counter: # of Exceps Thrown / sec, instance 
Counter \ASP.NET Applications(??APP_W3SVC_PROC??)\Request Execution Time: Failed to perform the first read for performance counter. Please make sure it exists. Category: ASP.NET Applications, counter: Request Execution Time, instance _LM_W3SVC_1_ROOT
Counter \Process(??APP_WIN32_PROC??)\Private Bytes: Failed to perform the first read for performance counter. Please make sure it exists. Category: Process, counter: Private Bytes, instance 
Counter \Process(??APP_WIN32_PROC??)\IO Data Bytes/sec: Failed to perform the first read for performance counter. Please make sure it exists. Category: Process, counter: IO Data Bytes/sec, instance 
Counter \ASP.NET Applications(??APP_W3SVC_PROC??)\Requests In Application Queue: Failed to perform the first read for performance counter. Please make sure it exists. Category: ASP.NET Applications, counter: Requests In Application Queue, instance _LM_W3SVC_1_ROOT
Counter \Processor(_Total)\% Processor Time: Failed to register performance counter. Category: Processor, counter: % Processor Time, instance: _Total.
```

Is there a solution?

**Comment by cijothomas** [comment]
Perf counters are not available for apps inside containers.

**Comment by SergeyKanzhelev** [comment]
@cijothomas I see that issue https://github.com/moby/moby/issues/23225 was resolved. What makes you say it is not supported by Application Insights?

**Comment by SergeyKanzhelev** [comment]
I agree that we need to come up with functional tests for containers scenarios though...

**Comment by SergeyKanzhelev** [comment]
@karolz-ms @nizarq do you run tests in windows containers?

**Comment by cijothomas** [comment]
@SergeyKanzhelev i wasn't aware containers supported reading perf counters. My tests app in containers failed to get perf counters when I tried ~2month back with same error.
Test App was here: 
https://github.com/Microsoft/ApplicationInsights-dotnet-server/tree/cithomas/dockerprototype/Test/E2ETests/TestApps/Net452/E2ETestApp

**Comment by SergeyKanzhelev** [comment]
@cijothomas got it, thanks. @shibayan can you access performance counters using powershell on your container?

 @karolz-ms @nizarq have you run windows container recently?

**Comment by karolz-ms** [comment]
@SergeyKanzhelev I am not aware on any testing done on our side with AI SDK running inside Windows Containers, if that is what you are asking about

**Comment by shibayan** [comment]
@SergeyKanzhelev Yes. I can access the performance counter.

![image](https://user-images.githubusercontent.com/1356444/30601837-e1e6eb40-9d9d-11e7-8eac-8271948df29f.png)

**Comment by cijothomas** [comment]
@shibayan I will investigate this. I can also ready perf counters so SDK should also be able to. Need investigation to see why it failed.

**Comment by cijothomas** [comment]
I created a console app with AI SDK, and loaded percounter module and it works without any issues. Livemetrics also work without any issues. (i.e perf counter values are reported to AI, and no error about read failures.)
I'll check why perf counters was an issue with full web application.

**Comment by antonGritsenko** [comment]
Faced with same, web api application in Service Fabric container. Any update on this?

**Comment by cijothomas** [comment]
@antonGritsenko Sorry for abandoning this. Will get back to this soon.

**Comment by lolbro-pl** [comment]
I am facing the same issue using version 2.6.4 when the SDK is added to the Windows Service.

**Comment by BreakingPanda** [comment]
Exact same issue as @lolbro-pl

**Comment by shibayan** [comment]
I have found a solution partially for this problem.
Add a line to the Dockerfile and grant permissions to the IIS executing user.

```
RUN net localgroup 'Performance Monitor Users' /add 'IIS APPPOOL\DefaultAppPool'
```

It worked well in the local Hyper-V Containers and Azure Container Instances. However, since Web App for Windows Containers did not work, there seems to be more problems.

**Comment by BreakingPanda** [comment]
I'm using Web App container hence cannot modify the permission of my App Pool user. Thanks @shibayan for the suggestion.

**Comment by shibayan** [comment]
@cijothomas I created a PR because I understand why Web App for Windows Containers can not collect performance counters.

**Comment by shibayan** [comment]
Fixed. Thanks!
