### ISSUE TITLE
WindowsServer\Tools\install.ps1 is not signed.

### ISSUE THREAD

**Issue by Dmitry-Matveev** [Microsoft/ApplicationInsights-dotnet-server#677]
One of the scans reported that this PS1 is not signed.
Most probably, it is unsigned due to missing [signing.props ](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Common.props#L3) in [Nuget Proj](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/WindowsServer/WindowsServer.Nuget/WindowsServer.Nuget.csproj).

**Comment by MS-TimothyMothra** [comment]
Closing this issue. Pull Request #686 was closed on Sept 15th.
