### ISSUE TITLE
AI.AspNetCore NuGet autoconfigures perf counter collection which fails

### ISSUE THREAD

**Issue by dkkapur** [Microsoft/ApplicationInsights-dotnet-server#687]
I added the AspNetCore NuGet (v2.1.1) to my ASP.NET Core Application running on Service Fabric, and am getting a trace in AI that has the following message: 
```
AI: Error collecting 4 of the configured performance counters. Please check the configuration.
Counter \ASP.NET Applications(??APP_W3SVC_PROC??)\Requests/Sec: Failed to perform the first read for performance counter. Please make sure it exists. Category: ASP.NET Applications, counter: Requests/Sec, instance VotingWeb.exe
Counter \.NET CLR Exceptions(??APP_CLR_PROC??)\# of Exceps Thrown / sec: Failed to perform the first read for performance counter. Please make sure it exists. Category: .NET CLR Exceptions, counter: # of Exceps Thrown / sec, instance 
Counter \ASP.NET Applications(??APP_W3SVC_PROC??)\Request Execution Time: Failed to perform the first read for performance counter. Please make sure it exists. Category: ASP.NET Applications, counter: Request Execution Time, instance VotingWeb.exe
Counter \ASP.NET Applications(??APP_W3SVC_PROC??)\Requests In Application Queue: Failed to perform the first read for performance counter. Please make sure it exists. Category: ASP.NET Applications, counter: Requests In Application Queue, instance VotingWeb.exe
```
How are these getting configured? Where can I change the configuration or make sure that it is able to pick up the appropriate values?

Thanks!

**Comment by cijothomas** [comment]
For .net core application, the default list of counters is hard coded in the PerformanceCollectorModule. But you can add/remove counters by modifying the Counters field in the PerformanceCollectorModule.
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/PerformanceCollector/Perf.Shared.NetFull/PerformanceCollectorModule.cs#L156


This is the list of default counters: https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/PerformanceCollector/Perf.Shared.NetFull/PerformanceCollectorModule.cs#L156
