### ISSUE TITLE
IndexOutOfRangeException from Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule

### ISSUE THREAD

**Issue by reddykkk** [Microsoft/ApplicationInsights-dotnet-server#69]
We are getting IndexOutOfRange exception from Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule. This happened after the our service ran for over 8 hours. 

**Call Stack:**
[IndexOutOfRangeException: Index was outside the bounds of the array.]
   System.Collections.Generic.List`1.Add(T item) +34
   Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.PortalDiagnosticsQueueSender.Send(TraceEvent eventData) +11
   Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsListener.WriteEvent(TraceEvent eventData) +90
   Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsListener.OnEventWritten(EventWrittenEventArgs eventSourceEvent) +134
   Microsoft.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs) +91

[EventSourceException: An error occurred when writing to a listener. ]
   Microsoft.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs) +201
   Microsoft.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* childActivityID, Object[] args) +206
   Microsoft.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* childActivityID, Int32 eventDataCount, EventData* data) +277
   Microsoft.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data) +1245
   Microsoft.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, String arg1, String arg2) +192
   Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule..ctor() +211

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck) +0
   System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) +113
   System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) +232
   System.Activator.CreateInstance(Type type, Boolean nonPublic) +83
   System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark) +1122
   System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) +128
   System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture) +18
   System.Web.HttpRuntime.CreateNonPublicInstance(Type type, Object[] args) +60
   System.Web.HttpApplication.BuildIntegratedModuleCollection(List`1 moduleList) +189
   System.Web.HttpApplication.InitInternal(HttpContext context, HttpApplicationState state, MethodInfo[] handlers) +792
   System.Web.HttpApplicationFactory.GetNormalApplicationInstance(HttpContext context) +336
   System.Web.HttpApplicationFactory.GetApplicationInstance(HttpContext context) +107
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +327

**Our service details:**
ASP.NET WebAPI and MVC application
.NET Framework: 4.5.1
Running as Web App in Azure
Application Insights version: 1.2.3

**Comment by abaranch** [comment]
That you for reporting the issue, we will investigate it. 
To workaround this issue you can remove DiagnosticsTelemetryModule from your applicationinsights.config.

**Comment by walmon** [comment]
What was the solution of this? I have the same issue

**Comment by abaranch** [comment]
Fix is included in the latest beta SDK.
