### ISSUE TITLE
Application Insights duplicated dependency logs

### ISSUE THREAD

**Issue by GGcNeaR** [Microsoft/ApplicationInsights-dotnet-server#690]
I have Application Insights configured for a production webapp. The nuget packages are installed, AppInsights.config and Web.config are configured (default configuration) and I don't have any changes in the codebase except setting the instrumentation key dynamically. Is it normal to see the same dependency logged multiple times and why is it happening? And by "multipe times" I mean 15-20.

AI: 2.4.0.0
.NET Framework: 4.6.1

Example:
https://i.stack.imgur.com/jvlKh.png

I am using NHibernate but SQL Server Profiler shows only 1 SQL query so the problem is only with the logging.
The data from analytics.applicationinsights.io shows that only the timestamps (and IDs) are different: 
https://i.stack.imgur.com/hlX9b.png
The data sent to AI servers (captured using Fiddler, some sensitive info replaced with dummy placeholders):
https://pastebin.com/CAUQTGVi

The only related topic I found (which does not mention duplication of logged items), and definitely does not answer my question nor gives me an acceptable solution: https://social.msdn.microsoft.com/Forums/vstudio/en-US/97d9f0b0-9d1e-4261-b80f-c7b7f07ecfe2/telemetry-throttling-how-can-i-cut-back-on-telemetry-events-disable-dependancy-events?forum=ApplicationInsights

Any idea what could be the source of the problem?

**Comment by cijothomas** [comment]
@GGcNeaR any chance you could provide a repro code where you see this behavior?
Also if possible - can you install application insights extension to your web app, and then see if this issue still occurs? Installing extension uses profiler based monitoring and gives better SQL dependency monitoring. (the sdk version in dependency item can tell whether profiler is collecting dependency or not. For profiler (extension) it'll be rddp vs rddf currently)

**Comment by MS-TimothyMothra** [comment]
@GGcNeaR Do you have a repro?

**Comment by GGcNeaR** [comment]
Sorry for the late reply, it's because of my current schedule. I can setup a web application with the same N-tier architecture and configuration as the production app where the issue was observed. We are using our own internal framework and making the packages public might be a problem (will discuss it with my superiors tomorrow at work). I am not familiar with the procedure in such cases (providing private code in order to reproduce an issue with public one), so any suggestions will be highly appreciated?

**Comment by GGcNeaR** [comment]
@cijothomas Isn't the app insights extension only for apps deployed on azure? The production app is not deployed on Azure, nor are the app instances on our test and uat environments.

**Comment by cijothomas** [comment]
@GGcNeaR  yes app insights extension is only for apps in Azure, but you can install status monitor to achieve equivalent effect (for dependency collection).
We dont really need you to install StatusMonitor or Extension, that was just to isolate the issue. (DependencyCollection works different with/without statusmonitor/extension.)

Any small repro where you make SQL calls, and see application insights reporting multiple times is helpful to investigate further.

**Comment by GGcNeaR** [comment]
I discussed the issue with my superiors and should be able to make a repo and provide it next week. Again apologies for the delay.

**Comment by GGcNeaR** [comment]
Could not reproduce the issue with a new MVC WebApp project with almost identical configuration as the production one. What's more interesting is I no longer observe the issue with multiple dependency logs on the original project. 

Once again apologies for the delays in my replies and the inconvenience caused by reporting an issue and not being able to reproduce it later. Please consider it closed.

**Comment by MS-TimothyMothra** [comment]
@GGcNeaR Thank you for your help. We appreciate feedback from our community! :)
