### ISSUE TITLE
Operation Names now full url? [2.4.1]

### ISSUE THREAD

**Issue by chrisaut** [Microsoft/ApplicationInsights-dotnet-server#704]
I just upgraded from 2.2 to 2.4.1 and now all the operation names for the requests seem to capture the entire URL.

It used to be like this (for example):

GET users [id]
but now after the update its
GET /api/users/260668

This is kind of annoying because nothing groups anymore. I cannot for example go to performance and see performance by these logical operations, every user is now its own group.

Did I miss some setting when upgrading, or what's going on? Would appreciate some insight here.

**Comment by chrisaut** [comment]
Does nobody else have this issue?

I tried to find where the name gets set, and it appears to come from here 
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/60a8d3f325e02503a4491d1a48cd70f9e5237a41/Src/Web/Web.Shared.Net/Implementation/RequestTrackingExtensions.cs#L117

Is this correct? It says "Controller/Action for MVC or path for other cases." I seem to hit the other cases condition. I'm using WebApi. I checked the RouteValues bag via the debugger inside an action. Both "controller" and "action" values appear to be set correctly. And yet, ApplicationInsights sets the request name to something like "GET /api/users/info/178494" instead of "GET Users/Info".

Would appreciate some help here to track this down. My only thought ATM to fix this would be to hook into the process somewhere and manually overwrite the wrongly set Request/Operation name. But I'd much rather find out why it isn't working as before.

**Comment by cijothomas** [comment]
@chrisaut I just created an app with default visual studio template for Web API, and tried 2.2 and 2.4.1 of application insights sdk. Operations Name is Get Values [id] for me in both cases. (request url i tried was /api/values/3) 

If routevalues does contain "controller" then operation name should be set to that at least.
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/60a8d3f325e02503a4491d1a48cd70f9e5237a41/Src/Web/Web.Shared.Net/Implementation/RequestTrackingExtensions.cs#L140

If you can share a small repro, we can continue investigation to this.

**Comment by MS-TimothyMothra** [comment]
@chrisaut Do you have a repro?

**Comment by chrisaut** [comment]
Sorry I'm on holiday ATM, will try to get a small repo when I'm back in a
few days.

**Comment by MS-TimothyMothra** [comment]
Hi @chrisaut, Will you be able to provide a repro for this issue?
