### ISSUE TITLE
NullReferenceException in ApplicationInsightsHttpModule

### ISSUE THREAD

**Issue by szingg** [Microsoft/ApplicationInsights-dotnet-server#705]
About every minute i get following exception in ApplicationInsightsHttpModule

`[NullReferenceException: Object reference not set to an instance of an object.] Microsoft.ApplicationInsights.Common.CorrelationIdLookupHelper.RegisterFailure(String instrumentationKey, Exception ex) +110   Microsoft.ApplicationInsights.Common.CorrelationIdLookupHelper.TryGetXComponentCorrelationId(String instrumentationKey, String&amp; correlationId) +577
   Microsoft.ApplicationInsights.Web.RequestTrackingTelemetryModule.OnEndRequest(HttpContext context) +641
   Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule.OnEndRequest(Object sender, EventArgs eventArgs) +130
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +69`

Environment: 
Windows 10 Enterprise (Version 1607 / OS Build 14393.1480)
IIS Version 10.0.14393.0

This error only occurs on devices where ports 80 and 443 are blocked.

**Comment by szingg** [comment]
This error only occurs if the app is startet without network connection. If the app has a connection at the beginning, the error can not be reproduced by disconnecting.
As indicated before, the error does not occur each time. I encountered an error interval of 1-5 minutes

**Comment by szingg** [comment]
`<package id="Microsoft.ApplicationInsights" version="2.3.0" targetFramework="net451" />`
`<package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.0.7" targetFramework="net451" />`
`<package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.3.0" targetFramework="net451" />`
`<package id="Microsoft.ApplicationInsights.Log4NetAppender" version="2.2.0" targetFramework="net451" />`
`<package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.3.0" targetFramework="net451" />`
`<package id="Microsoft.ApplicationInsights.Web" version="2.3.0" targetFramework="net451" />`
`<package id="Microsoft.ApplicationInsights.WindowsServer" version="2.3.0" targetFramework="net451" />`
`<package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.3.0" targetFramework="net451" />`

**Comment by cijothomas** [comment]
@MS-TimothyMothra I think the PR you submitted should fix this as well>?
https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/702

**Comment by MS-TimothyMothra** [comment]
Yes, this should have been covered by that fix.

**Comment by cijothomas** [comment]
thnx. @szingg This is fixed, and will be available in the next beta1 onwards (expected in a week)
