### ISSUE TITLE
Syntax error in runFunctionalTests.cmd?

### ISSUE THREAD

**Issue by anpete** [Microsoft/ApplicationInsights-dotnet-server#708]
```'-CALL' is not recognized as an internal or external command```

https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/runFunctionalTests.cmd#L4

@cijothomas Was this a bad merge?

**Comment by cijothomas** [comment]
Looks so. 
You can run the functional tests for dependency collector from Visual Studio directly.
Either way https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/CONTRIBUTING.md#functional-tests has pre-reqs that need to be presentfor local run.

**Comment by cijothomas** [comment]
was fixed
