### ISSUE TITLE
Quick Pulse exception showing in live metrics

### ISSUE THREAD

**Issue by xt0rted** [Microsoft/ApplicationInsights-dotnet-server#716]
I'm not sure if this is a bug, but I've noticed it a few times in my live metrics sample telemetry today. I didn't see any users on the site when it happened but I did notice a short spike in cpu usage and then it showed up. Just now I saw it twice and they were 4 minutes apart.

```
AI (Internal): Unexpected error in QuickPulse infrastructure: System.InvalidOperationException: StartTimestamp must be less than EndTimestamp.
 at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.QuickPulse.QuickPulseDataSample..ctor(QuickPulseDataAccumulator accumulator, IDictionary`2 perfData, IEnumerable`1 topCpuData, Boolean topCpuDataAccessDenied)
 at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule.CreateDataSample(QuickPulseDataAccumulator accumulator, IEnumerable`1 perfData, IEnumerable`1 topCpuData, Boolean topCpuDataAccessDenied)
 at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule.CollectSample()
 at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule.CollectionThreadWorker(Object state). QuickPulse data will not be available.
```

**Comment by zakimaksyutov** [comment]
@tokaplan, @netgh0st, can you please take a look?

**Comment by tokaplan** [comment]
We're aware of this issue. There's a rare race condition in QuickPulse module in SDK that causes a single data sample to have incorrect timestamps (the beginning is later than the end). Such occurrence causes a sample to be deemed invalid.
This doesn't cause any noticeable functional degradation (since it's properly handled). It's possible to fix, we just never prioritized it. Safe to ignore for now.

**Comment by zakimaksyutov** [comment]
@tokaplan, does this exception show up only in live metrics telemetry? Or does it end up in Analytics as well?

**Comment by tokaplan** [comment]
I can never remember what SDK's policies are for ETW listeners, I always ask @iusafaro to take a look at the QuickPulse ETW source and tell me if the telemetry will be sent out or not :) But I imagine if it shows up in the live feed, it should also make it to Analytics.

**Comment by letrungkien211** [comment]
I am facing the same issue. I am not sure why this is not prioritized, but this really makes the live log unusable.

**Comment by tokaplan** [comment]
@letrungkien211 are you being spammed with these messages so hard that you can't use live log at all? How many do you get generally?

**Comment by letrungkien211** [comment]
It was really like every 1,2 seconds, I can record an video later if you like. The problem was that I tried to debug my new application, my application’s logs are very few. I know there’s a work around by using Filter, but it is annoying. They also show up on Analytics. 

I am trying to move all our application to .net core, but this is one of the issue I am facing.

**Comment by tokaplan** [comment]
@letrungkien211 are you only observing this on a .NET Core platform, not regular .NET?

**Comment by letrungkien211** [comment]
@tokaplan
Hi

I am using .net Frame Work, Asp.Net Core Web Api. 
Anyway, I’ve given up deploying to web app and planned to use Service Fabric (for other reasons). So probably I can ignore this for now. 

However, the fact that those useless logs are displayed in live log and analytics means that they were not handled properly. As u said, it is a matter of priority, but I hope your team will fix it. If this is open source and I can understand the code, I would.

**Comment by letrungkien211** [comment]
@tokaplan hi, I didn’t see this for regular .Net project I have deployed so far, but may be I just missed them, I am sure. Anyway, the same issue doesn’t happen on service fabric deployment.

**Comment by MS-TimothyMothra** [comment]
@tokaplan @letrungkien211 Any new progress on this issue?

**Comment by letrungkien211** [comment]
I switched to service fabric and haven’t noticed the issue since then. Maybe it is really gone or my app log was just so big that it can be ignored. Thanks.
