### ISSUE TITLE
New cloud service webrole projects are unable to report request / dependency telemetry etc. through status monitor

### ISSUE THREAD

**Issue by nizarq** [Microsoft/ApplicationInsights-dotnet-server#717]
**Repro:**
The repro is really simple. Create a new cloud service with a web role and publish. Keep everything default – this will ensure WAD is added, and an AI resource is provisioned for you to receive WAD2AI and status monitor data. WAD2AI data shows up but nothing from status monitor.
 
**Reason:**
Turns out all new ASP.net templates include AI by default. The AI nugets are installed but no AI key is configured. Since cloud service web roles use the default latest ASP.net templates, they also end up having AI nugets but no AI key configured. 
This means when you publish, WAD is applied, which in turn tried to configure collection through status monitor. Status monitor then detects that the website itself already has AI sdk and gives up thinking it doesn’t need to inject the sdk. This means even though AI key is provided through WAD, neither the website code, nor status monitor is able to send anything to the AI resource.
 
**Impact:**
All newly created web roles are impacted. Old web roles should continue to work fine with status monitor as they do not inject AI sdk by default and status monitor has the opportunity to do its work.
 
**Suggested Fix:**
The suggested fix is to teach AI sdk included in the project to probe for the key provided through WAD and use that.

**Comment by cijothomas** [comment]
@nizarq just to confirm - will you be submitting a PR with the suggested fix? 
if not, do you expect a fix from us in beta2 time frame?
(I want to make sure this gets prioritized and assigned correctly if you are not working on the fix)

**Comment by cijothomas** [comment]
btw - i believe reading ikey belongs in base sdk.
