### ISSUE TITLE
HttpContext can not collect async-await method

### ISSUE THREAD

**Issue by virtualcca** [Microsoft/ApplicationInsights-dotnet-server#73]
for example can not collect httpclient request

**Comment by abaranch** [comment]
@virtualcca Could you please provide more details on what do you mean?

**Comment by abaranch** [comment]
If you meant that some properties that are currently populated from HttpContext would not be available than yes, it is expected.

**Comment by virtualcca** [comment]
I mean if use like HttpClient
that it send message can attach to Request dependency
but sql can attach to dependency

**Comment by abaranch** [comment]
Yes, correlation with requests does not work in case of async requests. We have a special workaround that works only for Sql dependencies. Please read this on how to use Operations API: https://azure.microsoft.com/en-us/blog/save-money-with-application-insights-web-sdk-2-0/
