### ISSUE TITLE
Frequent errors showing in live metrics after setting up secure control channel

### ISSUE THREAD

**Issue by xt0rted** [Microsoft/ApplicationInsights-dotnet-server#733]
I setup the secure control channel based on the information at https://docs.microsoft.com/en-us/azure/application-insights/app-insights-live-stream#secure-the-control-channel and http://apmtips.com/blog/2017/02/13/enable-application-insights-live-metrics-from-code/.

My site was using `ApplicationInsights.config` for everything except setting the instrumentation key, which I was doing in code so I could set it via app settings with `APPINSIGHTS_INSTRUMENTATIONKEY`. For similar reasons I didn't want to set the API Key in the config either, plus I don't want any of that making it into source control leaving me with the only option being setting it in code.

The error I'm seeing in live metrics is:
```
AI (Internal): [msg=Log Error];[msg=Error in RequestMetricsExtractor: System.InvalidOperationException: Cannot execute ExtractMetrics because this metrics extractor has not been initialized (no metrics manager).
 at Microsoft.ApplicationInsights.Extensibility.Implementation.Metrics.DependencyMetricsExtractor.ExtractMetrics(ITelemetry fromItem, Boolean& isItemProcessed)
 at Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor.ExtractMetrics(ITelemetry fromItem)]
```

This is my code which is based on the blog post above.

```csharp
public static void SetupApplicationInsights()
{
    var configuration = TelemetryConfiguration.Active;

    configuration.InstrumentationKey = AppSettings.GetString("APPINSIGHTS_INSTRUMENTATIONKEY", defaultValue: string.Empty);

    // http://apmtips.com/blog/2017/02/13/enable-application-insights-live-metrics-from-code/
    QuickPulseTelemetryProcessor processor = null;
    configuration.TelemetryProcessorChainBuilder.Use(next =>
    {
        processor = new QuickPulseTelemetryProcessor(next);
        return processor;
    }).Build();

    var quickPulse = new QuickPulseTelemetryModule
    {
        AuthenticationApiKey = AppSettings.GetString("APPINSIGHTS_APIKEY")
    };
    quickPulse.Initialize(configuration);
    quickPulse.RegisterTelemetryProcessor(processor);
}
```
I also removed the following from the `ApplicationInsights.config`
```xml
<TelemetryModules>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule, Microsoft.AI.PerfCounterCollector"/>
</TelemetryModules>
<TelemetryProcessors>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor, Microsoft.AI.PerfCounterCollector"/>
</TelemetryProcessors>
```

Is the error I'm getting even related to the code changes I made? If so are there additional changes I should make to my `ApplicationInsights.config`, or other code changes that weren't mentioned in those resources?

**Comment by SergeyKanzhelev** [comment]
Workaround was proposed here: https://github.com/Microsoft/ApplicationInsights-dotnet/issues/549

The issue is that aggregation telemetry processor do not "like" being re-build. So when you have a set of processors in code and in config - aggregation processor got re-build and start complaining. You just need to call `Initialize` on it.

Thanks for reporting!

**Comment by xt0rted** [comment]
Just wanted to follow up with the changes I made since it's easy to do wrong.

This was what I did first
```diff
public static void SetupApplicationInsights()
{
    var configuration = TelemetryConfiguration.Active;

    configuration.InstrumentationKey = AppSettings.GetString("APPINSIGHTS_INSTRUMENTATIONKEY", defaultValue: string.Empty);

    // http://apmtips.com/blog/2017/02/13/enable-application-insights-live-metrics-from-code/
    QuickPulseTelemetryProcessor processor = null;
    configuration.TelemetryProcessorChainBuilder.Use(next =>
    {
        processor = new QuickPulseTelemetryProcessor(next);
        return processor;
    }).Build();

    var quickPulse = new QuickPulseTelemetryModule
    {
        AuthenticationApiKey = AppSettings.GetString("APPINSIGHTS_APIKEY")
    };
-    quickPulse.Initialize(configuration);
    quickPulse.RegisterTelemetryProcessor(processor);
+
+    foreach (var telemetryProcessor in configuration.TelemetryProcessors)
+    {
+        if (telemetryProcessor is ITelemetryModule telemetryModule)
+        {
+            telemetryModule.Initialize(configuration);
+        }
+    }
}
```

The thinking was why initialize the quick pulse module only to initialize it again right after. Turns out this doesn't work as you'd expect and you'll lose your live metrics entirely. The `quickPulse.Initialize(configuration);` *has* to remain. Beside that the rest of the changes work as expected.

**Comment by devmonkey22** [comment]
I don't know if this could cause underlying implementation issues, but to avoid re-initializing all processors, I was able to use the following in setup (ie: Global Application_Start), after setting InstrumentationKey:

```
// Setup Authentication API Key, if available
var sAuthAPIKey = System.Configuration.ConfigurationManager.AppSettings["Microsoft.ApplicationInsights.APIKey"];
if (!string.IsNullOrWhiteSpace(sAuthAPIKey))
{
  // Get public (but non-visible) TelemetryModules to update the configuration dynamically
  var module = Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryModules.Instance.Modules.OfType<Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule>().FirstOrDefault();
  if (module != null)
  {
    module.AuthenticationApiKey = sAuthAPIKey;
  }
}
```
