### ISSUE TITLE
Add custom dimensions to http dependencies from the request context

### ISSUE THREAD

**Issue by sanjaysingh** [Microsoft/ApplicationInsights-dotnet-server#747]
For http dependencies of a given web request, there are some headers in the outgoing http request that I want to extract and put into the custom dimensions of the dependency telemetry. 
I am using .Net 4.5 ASPNet WebAPI and on AppInsight version 2.4.0. 

1. Http request comes to WebApi
2. Web Api internally makes more or more calls to an external http web service. It attaches some custom header to each of those calls that represent a very specific thing about that request.
3. Dependency is correctly getting logged. In that dependency, i want to extract the custom that was sent to the external service and write as custom dimension.

 I raised another issue [729](https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/729) where i need to extract some headers from incoming request context and attach that to the dependencies. In that case i was able to find no so elegant work around of using CallContext to propagate this and it is working fine. In this case however CallContext seems risky because that outbound calls are all async and this can overstep on the CallContext properties.

I do not want to write an additional dependency telemetry and am happy with the default behavior. Just need this little bit of customization.

When i looked at the code to see if there is any extensibility hooks in the http depenency processor, it seems too closed to do anything. Microsoft.ApplicationInsights.DependencyCollector.Implementation.HttpProcesing seems perfect fit to add this customization but there is no hooks to do any customization. I have seen suggestions of attaching to diagnostics source yourself and then doing all this plumbing; that is non trivial.

I feel this AppInsight SDK needs to restructure these dependency collectors in way that it allows for consumers to plugin some extra bit of customization without going through these extra hops. The correlation code in the HttpProcessing itself could have been one of the inbuilt plugins!!

Please let me know if i am missing something and if there is an easy way to achieve this trivial requirement that i have.

**Comment by lmolkova** [comment]
This is implemented in #900 

Basically during TelemetryIntitialiers run you have access to HttpRequestMessage/HttpWebRequest and HttpResponseMessage/HttpWebResponse through OperationDetails:

`dependencyTelemetry.TryGetOperationDetail("HttpResponse", out var reponseObject)`

Http keys are:

```csharp
        public const string HttpRequestOperationDetailName = "HttpRequest";
        public const string HttpResponseOperationDetailName = "HttpResponse";
        public const string HttpResponseHeadersOperationDetailName = "HttpResponseHeaders";

```

Be careful: in some cases instead of HttpResponse we can only give you HttpResponseHeaders,
