### ISSUE TITLE
Performance Counters for OWIN Service Hosted on Worker Role

### ISSUE THREAD

**Issue by somenathdey98007** [Microsoft/ApplicationInsights-dotnet-server#748]
Hi,

I have a OWIN service hosted on a Worker Role. 
I would like to enable the following counters for both real time and historical times:
1.	RPS
2.	Queue Length/Time
3.	Request Execution Time
4.	CPU%
5.	Disk IO/sec
6.	Disk RW/sec
7.	NW IO/sec
8.	NW Transmit/sec
9.	NW Receive/sec
10.	Memory usage

I would like to know 
•	If it is possible to get all of these for a Worker Role as it is not hosted on IIS
•	If possible (i.e. the above one is true) I get a feeling from reading various resources, the file that needs to be updated is the diagnostics.wadcfx file – however, I am not sure in what format that file needs to be updated for all of these performance counters
•	If the above two hold good – what are the steps using which the Performance Counters are visible both real time and historical – both for the Role overall and also per instance – ideally on App Insights

Thanks in advance.

Thanks,
Somenath

**Comment by SergeyKanzhelev** [comment]
Is this what you are looking for http://apmtips.com/blog/2015/10/07/performance-counters-in-non-web-applications/ ? Or you wonder what would be counter names in this case?

**Comment by somenathdey98007** [comment]
Thanks Sergey. You are correct.
I would like to know what would be the names of the Perf Counters for a Worker Role which will help me get the desired counter values as listed above.

Thanks,
Somenath

**Comment by MS-TimothyMothra** [comment]
I think this is what you're looking for:
https://technet.microsoft.com/en-us/library/bb734903.aspx#ECAA
https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/performance-counters
