### ISSUE TITLE
Mistake on SyntheticUserAgentTelemetryInitializer.cs

### ISSUE THREAD

**Issue by christopheMeudec** [Microsoft/ApplicationInsights-dotnet-server#750]
Hi,

I found a mistake by reading the code.
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/ddbd67d40a36ec257990dc0c6e277fc226f1a9d4/Src/Web/Web.Shared.Net/SyntheticUserAgentTelemetryInitializer.cs#L62-L63

The check "request != null" have to be done before accessing to the property UserAgent. 

Regards
Christophe

**Comment by MS-TimothyMothra** [comment]
@christopheMeudec Thank you! 
Was this causing an exception for you?
