### ISSUE TITLE
QuickPulse Generating Large Numbers of Errors

### ISSUE THREAD

**Issue by ANMain** [Microsoft/ApplicationInsights-dotnet-server#752]
I am seeing a large number of error messages (>12k) per day for each application that I am running in a Service Fabric cluster. This is completely blocking up the Live Metrics Stream. The error message is:

```
AI (Internal): Unexpected error in QuickPulse infrastructure: System.InvalidOperationException: Can't start collection while it is already running.
   at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor.Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.IQuickPulseTelemetryProcessor.StartCollection(IQuickPulseDataAccumulatorManager accumulatorManager, Uri serviceEndpoint, TelemetryConfiguration configuration, Boolean disableFullTelemetryItems)
   at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule.OnStartCollection()
   at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.QuickPulse.QuickPulseCollectionStateManager.UpdateState(String instrumentationKey, String authApiKey)
   at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule.StateThreadWorker(Object state). QuickPulse data will not be available.
```

## Repro Steps
Custom Application Insights processors are configured in the `Startup.cs` class:
```
public void ConfigureServices(IServiceCollection services)
{
    TelemetryConfiguration.Active
        .TelemetryProcessorChainBuilder
        .UseHealthCheckFilter()
        .Build();
            
    services
        .AddOptions()
        .AddApplicationInsightsTelemetry(Configuration.GetSection(nameof(ApplicationInsightsConfiguration)))
        .AddMvc();
}
```

There is also a default `applicationinsights.config` that was generated when the project was created and adds the performance counters that appear to be causing the issue:
```
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
  <TelemetryInitializers>
    <Add Type="Microsoft.ApplicationInsights.DependencyCollector.HttpDependenciesParsingTelemetryInitializer, Microsoft.AI.DependencyCollector"/>
    <Add Type="Microsoft.ApplicationInsights.ServiceFabric.FabricTelemetryInitializer, Microsoft.AI.ServiceFabric"/>
  </TelemetryInitializers>
  <TelemetryModules>
    <Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">
      <ExcludeComponentCorrelationHttpHeadersOnDomains>
        <Add>core.windows.net</Add>
        <Add>core.chinacloudapi.cn</Add>
        <Add>core.cloudapi.de</Add>
        <Add>core.usgovcloudapi.net</Add>
      </ExcludeComponentCorrelationHttpHeadersOnDomains>
    </Add>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule, Microsoft.AI.PerfCounterCollector"/>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule, Microsoft.AI.PerfCounterCollector"/>
  </TelemetryModules>
  <TelemetryProcessors>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor, Microsoft.AI.PerfCounterCollector"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
      <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
    </Add>
  </TelemetryProcessors>
  <TelemetryChannel Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel, Microsoft.AI.ServerTelemetryChannel"/>
</ApplicationInsights>
```

## Version Info 
SDK Version : Microsoft.ApplicationInsights 2.4.0, Microsoft.ApplicationInsights.AspNetCore 2.1.1, Microsoft.ApplicationInsights.ServiceFabric.Native 1.0.0-beta2
.NET Version :	4.6.1
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Configured in code
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Azure WebApps

**Comment by zakimaksyutov** [comment]
+ @tokaplan, @netgh0st

**Comment by zakimaksyutov** [comment]
@tokaplan, @netgh0st, can you please take a look?

**Comment by ANMain** [comment]
I have resolved this now.
The configuration for quick pulse in `applicationinsights.config` is not necessary since the metrics stream is [enabled by default in the .Net Framework](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Telemetry-Processors:-Sampling-and-Metrics-Stream#metrics-stream). I think that this then caused the quick pulse to initialise twice, causing the error.

**Comment by tokaplan** [comment]
That was my guess, a double initialization. Is this expected that if you have ApplicationInsights.config everything gets initialized twice in .NET Core?

**Comment by zakimaksyutov** [comment]
@cijothomas, @Dmitry-Matveev, does .NET Core honor AI.config and initialize all components twice?

**Comment by Dmitry-Matveev** [comment]
.NET Core SDK by itself is not supposed to read from ApplicationInsights.config file. Unless it was introduced by the modules that are now referenced from AI Web SDK (such as QuickPulse, DependencyCollector and others that might want to initialize Telemetry Configuration and provoke reading ApplicationInsights.config) - that should not be the case. If it is, removal of ApplicationInsights.config is the right thing to do. Typically this file should not even be present in case of .NET Core SDK - was it added by ServiceFabric Nuget?

The other possible way of double initialization in .NET Core is calling `AddApplicationInsightsTelemetry()` twice unless it's re-entrant (which I'm not aware of). For instance, `UseApplicationInsights()` will internally call it in addition to the code that's already present in `ConfigureServices()`.

**Comment by ANMain** [comment]
Application Insights is initialised using `AddApplicationInsightsTelemetry` in the `Startup.cs`. There is no call to `UseApplicationInsights()`.
I've looked back through the history of the repository and the `ApplicationInsights.config` was added by a developer rather than by a NuGet package. So this must have been the cause of the double initialisation.
