### ISSUE TITLE
Multiple threads enumerating through a collection is intrinsically not a thread-safe procedure

### ISSUE THREAD

**Issue by OlegUfaev** [Microsoft/ApplicationInsights-dotnet-server#76]
In our project on .NET 4.5 (ASP.NET Web-application for hosting WCF-service) used references to these NuGet-packages:
- Microsoft.ApplicationInsights 1.2.3
- Microsoft.ApplicationInsights.Agent.Intercept 1.2.1
- Microsoft.ApplicationInsights.DependencyCollector 1.2.3
- Microsoft.ApplicationInsights.JavaScript 0.15.0-build58334
- Microsoft.ApplicationInsights.PerfCounterCollector 1.2.3
- Microsoft.ApplicationInsights.Web 1.2.3
- Microsoft.ApplicationInsights.WindowsServer 1.2.3
- Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 1.2.3

We have rarely occurring issue, which lead to 100% CPU load.
When it happened again, we have made the process dump and used [DebugDiag](https://www.microsoft.com/en-us/download/details.aspx?id=49924) to find/diagnose the problem.

Here the result of the "Analysis report":

**The following threads in w3wp.DMP are enumerating a System.Collections.Generic.Dictionary object**:
Multiple threads enumerating through a collection is intrinsically not a thread-safe procedure. If the dictionary object accessed by these threads is declared as static then the threads can go in an infinite loop while trying to enumerate the dictionary if one of the threads writes to the dictionary while the other threads are reading\enumerating through the same dictionary. You may also experience High CPU during this stage. For more details refer to High CPU in .NET app using a static Generic.Dictionary
![screenshot1](https://cloud.githubusercontent.com/assets/1725876/14779972/485ffe4c-0ae3-11e6-85e0-a9bd4c541c2d.png)

**All threads have a same call stack:**
System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].FindEntry(System.__Canon)+1a6 
System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].TryGetValue(System.__Canon, System.__Canon ByRef)+14 
Microsoft.ApplicationInsights.Extensibility.Implementation.LocationContext.get_Ip()+4f 
Microsoft.ApplicationInsights.Web.ClientIpHeaderTelemetryInitializer.UpdateRequestTelemetry(System.Web.HttpContext, Microsoft.ApplicationInsights.Extensibility.Implementation.LocationContext)+199 
Microsoft.ApplicationInsights.Web.ClientIpHeaderTelemetryInitializer.OnInitializeTelemetry(System.Web.HttpContext, Microsoft.ApplicationInsights.DataContracts.RequestTelemetry, Microsoft.ApplicationInsights.Channel.ITelemetry)+86 
Microsoft.ApplicationInsights.Web.Implementation.WebTelemetryInitializerBase.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)+86 
Microsoft.ApplicationInsights.TelemetryClient.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)+26e 
Microsoft.ApplicationInsights.TelemetryClient.Track(Microsoft.ApplicationInsights.Channel.ITelemetry)+28 
FIE.Common.Web.Code.ApplicationInsights.ApplicationInsightsLogExceptionAttribute.System.ServiceModel.Dispatcher.IErrorHandler.HandleError(System.Exception)+9b 
System.ServiceModel.Dispatcher.ErrorBehavior.HandleErrorCommon(System.Exception, System.ServiceModel.Dispatcher.ErrorHandlerFaultInfo ByRef)+a7 
System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessageCleanup(System.ServiceModel.Dispatcher.MessageRpc ByRef)+307 
System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage9(System.ServiceModel.Dispatcher.MessageRpc ByRef)+e2 
System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage8(System.ServiceModel.Dispatcher.MessageRpc ByRef)+ff 
System.ServiceModel.Dispatcher.MessageRpc.ProcessError(System.Exception)+2c8 
System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean)+169 
[[HelperMethodFrame]] 
System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(System.ServiceModel.Dispatcher.MessageRpc ByRef)+4e3 
[[HelperMethodFrame]] 
System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(System.ServiceModel.Dispatcher.MessageRpc ByRef)+764 
[[HelperMethodFrame]] 
![screenshot2](https://cloud.githubusercontent.com/assets/1725876/14779973/486031be-0ae3-11e6-8ba0-44678568e94d.png)

**Comment by abaranch** [comment]
Thank you for reporting the issue. We will investigate to fix.

**Comment by abaranch** [comment]
[Fixed](https://github.com/Microsoft/ApplicationInsights-dotnet/pull/225). It will be released with 2.1-beta4
