### ISSUE TITLE
Allow ".NET Data Provider for SqlServer" perf counters to be captured in Azure WebApps

### ISSUE THREAD

**Issue by linasburneika** [Microsoft/ApplicationInsights-dotnet-server#767]
ApplicationInsights captures a small set of perf counters by default when configured in Azure WebApps. It's possible to include additional perf counters to AppInsights configuration, but Azure restricts access to many of them.

We need a way to monitor sql connection pool. In case of multiple concurrent users there are many connections to DB opened that eventually leads pool exhaustion. If we could report pooled connection count to ApplicationInsights, that would allow us to monitor pool state and configure auto scaling based on this metric. 

At the moment access to ".NET Data Provider for SqlServer" perf counters from WebApps are prohibited.

**Comment by SergeyKanzhelev** [comment]
@davidebbo who will be the best person to track this feature request? Or maybe there is another GitHub repo where these kind of requests may be tracked?

**Comment by davidebbo** [comment]
A possible place is https://feedback.azure.com/forums/169385-web-sites/, where all App Service feedback requests are tracked.

**Comment by SergeyKanzhelev** [comment]
@davidebbo created user voice request: https://feedback.azure.com/forums/169385-web-apps/suggestions/32765788-make-more-performance-counters-available-on-azure

@linasburneika it will be great if you can vote for it

**Comment by SergeyKanzhelev** [comment]
Closing issue as it Application Insights needs infrastructure change to enable this work. Feature request will be tracked in Azure Web Apps User Voice portal
