### ISSUE TITLE
Which fields need to be set to connect 2 components in the multi-role app map?

### ISSUE THREAD

**Issue by PeterRockstars** [Microsoft/ApplicationInsights-dotnet-server#776]
Hi,

I'm not sure if this is the correct place to ask this question and if not, feel free to direct me elsewhere.

I have an ASP.NET web application (called WebUI) hosted on-prem in IIS which makes http requests to an OWIN self-hosted Web API (BuyWebService). I run multiple instances of the BuyWebService API, and they are functionally different from one another. 

We've recently started using the Application Map feature, with the multi-role preview enabled. I use a TelemetryInitializer to set the cloud_RoleName field in the WebUi and the BuyWebService instances. I see the WebUI as a component on the App Map and separate components for BuyWebService A, BuyWebService B, etc. All is wel so far. 
All of the RequestTelemetry for requests to the WebUI are sent to AI, as wel as DependencyTelemetry items for the http calls to the BuyWebServices, and the RequestTelemetry for the http requests as they arrive at the BuyWebService. I can see this when I do a regular Search for the telemetry.

Now the only thing missing is drawing the lines from the WebUi component in the App Map, to the different BuyWebService components so I can see timing and failure percentages divided per BuyWebService instance. At the moment I do see an arrow going out of WebUi to a component with just the IP of the server which runs the BuyWebServices (on different ports) as the name. But that just shows the data for all of the requests to the separate BuyWebServices combined.

So the question is: how are requests/dependencies mapped to the Application Map? Which fields do I need to set on the telemetry to make AI understand that an HTTP call is going to one of my own components?

I have got this working with a new project (TestDependency) that I added, which is a "regular" WebAPI project, and calling that from the WebUI. For that project all I needed to do was enable Application Insights, set a cloud_roleName on the telemetry, and AI had no difficulty in connecting the WebUI component to the TestDependency component in the App Map.

By the way, I'm using the package from this repo: https://github.com/marcinbudny/applicationinsights-owinextensions to enable AI in my BuyWebService.

Thanks for any help!

**Comment by SergeyKanzhelev** [comment]
This? http://apmtips.com/blog/2017/10/18/two-types-of-correlation/

**Comment by PeterRockstars** [comment]
@SergeyKanzhelev  YES! Thanks so much, that article is clearer and more informatinal than all of MS's documentation on the subject combined.

**Comment by SergeyKanzhelev** [comment]
@PeterRockstars blog is easier to write. We will be working to improve situation. I'm glad that post helped
