### ISSUE TITLE
Failed HTTP outgoing requests are not tracked on .NET Core

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet-server#780]
Commit 38865b6a118f15241bbce9ed7fc01a62cd0c872f

Prevents dependency to be collected when response is null. This corresponds to the valid case when an exception was thrown during request processing (because of network, dns, timeout). This case is treated specially in the code.

It is logged in internal telemetry as

```
AI (Internal): HttpCoreDiagnosticSourceListener OnNext failed to call event handler. Error details 'Event System.Net.Http.HttpRequestOut.Stop: cannot cast response to expected type HttpResponseMessage' 
```

Tests for failed/canceled requests should be verified or implemented if missing.

**Comment by Dmitry-Matveev** [comment]
This issue currently seems to be at Top-11 of AI (Internal) telemetry across 2.4 and 2.5 Base SDKs, adding to the scope of 2.6.
