### ISSUE TITLE
Worker Role Failing to start after installing the Application Insight Nuget packag

### ISSUE THREAD

**Issue by prmoh** [Microsoft/ApplicationInsights-dotnet-server#814]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Installed application insight and followed the step given in the article 
**https://docs.microsoft.com/en-us/azure/application-insights/app-insights-cloudservices**
2. The deployment never happened and crashed because of the following error. 

Acms.Service.Web_IN_1: BusyRole
Recovering role... Failed to load role entrypoint. System.BadImageFormatException: Cannot load a reference assembly for execution. -- System.BadImageFormatException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference assembly for execution. -- System.BadImageFormatException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference assembly for execution. -- System.BadImageFormatException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference assembly for execution. -- System.BadImageFormatException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference assembly for execution. -- System.BadImageFormatException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference assembly for execution. -- System.BadImageFormatException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference assembly for execution. -- System.BadImageFormatException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference assembly for execution. -- System.BadImageFormatException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflectio

## Version Info 
SDK Version :
.NET Version :	4.6.2 	 					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual studio via nuget package manager. 
OS : 
Hosting Info (IIS/Azure WebApps/ etc) : OWIN

**Comment by MS-TimothyMothra** [comment]
Hi @prmoh,
It seems there was a conflict with Visual Studio and System.Net.Http.
Can you review and try any of the solutions listed here: https://github.com/dotnet/corefx/issues/22781


Alternatively, please try onboarding to our latest SDK: [2.5.1](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/2.5.1) which was released last week.
You could also try upgrading to System.Net.Http's latest version: [4.3.3](https://www.nuget.org/packages/System.Net.Http/).


If none of this works, please answer some additional questions, so I can try to reproduce:

- What version of Visual Studio are you using?
- What version of our SDK (Microsoft.ApplicationInsights.Web) are you using?
- What type of project are you working with (MVC, WebApi)?
