### ISSUE TITLE
Object potentially not disposed when removed from the list?

### ISSUE THREAD

**Issue by aspcompiler** [Microsoft/ApplicationInsights-dotnet-server#822]
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/adb38a626cd36fb7e0b5e9b633719c99ec842a05/Src/PerformanceCollector/Perf.Shared.NetFull/Implementation/StandardPerformanceCollector/StandardPerformanceCollector.cs#L120

May be you want to check if the object implements IDisposible and Dispose it when it is removed from the list? Otherwise you lose the reference to it and leave it up for garbage collection.

**Comment by MS-TimothyMothra** [comment]
In this example `keyToRemove` is a System.Tuple<> which does not implement IDisposable. 
There are no unmanaged resources here so it is safe to leave it for garbage collection.
