### ISSUE TITLE
Change StyleCop to leverage Analyzers

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/ApplicationInsights-dotnet-server#831]
We are updating to StyleCop 5.0 (see issue #829) as a fix-up to deprecating any .NET framework assemblies < 4.5. We would also like to take advantage of the Analyzers present there.

[See here for details.](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md)

[We already make use of these in the -dotnet repo as well](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/7321d2bf7b9c4733fb43b6c186e381863931eb1a/src/Microsoft.ApplicationInsights/Microsoft.ApplicationInsights.csproj#L49)

**Comment by MS-TimothyMothra** [comment]
Closing this to track in VSTS
