### ISSUE TITLE
Request property "Client IP address" is not correctly showed on Azure Portal

### ISSUE THREAD

**Issue by jiberan** [Microsoft/ApplicationInsights-dotnet-server#833]
Request property "Client IP address" is not correctly showed on Azure Portal for requests. It is showing 0.0.0.0 regardless of actual IP address.

## Repro Steps

You can see project with repro steps here: [https://github.com/jiberan/ApplicationInsightsClientIp](url)

```
     class Program
    {
        static void Main(string[] args)
        {
            var appInsightsSender = new AppInsightsSender("InstrumentationKey");
            appInsightsSender.SendTelemetry();
            Console.ReadKey();
        }
    }

    class AppInsightsSender
    {
        private TelemetryClient _tc;

        public AppInsightsSender(string instrumentationKey)
        {
            SetTelemetryClient(instrumentationKey);
        }

        void SetTelemetryClient(string instrumentationKey)
        {
            TelemetryConfiguration.Active.InstrumentationKey = instrumentationKey;
            _tc = new TelemetryClient {InstrumentationKey = instrumentationKey};
            _tc.Context.User.Id = "userId";
            _tc.Context.Location.Ip = "192.168.1.1";
            _tc.Context.Device.OperatingSystem = Environment.OSVersion.ToString();
        }

        public void SendTelemetry()
        {
            _tc.TrackRequest("Hi!", DateTimeOffset.UtcNow, TimeSpan.FromHours(1), "200", true);
            _tc.Flush();
        }
    }
```

##  Actual Behavior

On Azure Portal, Client IP address is 0.0.0.0 instead of 192.168.1.1

![image](https://user-images.githubusercontent.com/17324808/36815841-428128c2-1cdc-11e8-8b2c-2bd378136252.png)

## Expected Behavior

This is image from Visual Studio, Application Insights Search

![image](https://user-images.githubusercontent.com/17324808/36815897-7a7984ea-1cdc-11e8-9410-4c678b96d259.png)

## Version Info 
SDK Version : 2.5.1
.NET Version : 4.5 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Win 10

**Comment by SergeyKanzhelev** [comment]
Sorry for your bad expirience. Please see these two links:

https://blogs.msdn.microsoft.com/applicationinsights-status/2018/02/01/all-octets-of-ip-address-will-be-set-to-zero/

http://apmtips.com/blog/2016/07/05/client-ip-address/
