### ISSUE TITLE
Azure instance metadata heartbeat provider should not assume the IHeartbeatPropertyManager is available upon .Initialize

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/ApplicationInsights-dotnet-server#834]
We need to ensure that the `IHeartbeatPropertyManager` is instantiated before we attempt to add heartbeat properties to it.

Currently, we are relying on the implementation details of the baseSDK rather than handling the scenario that the `IHeartbeatPropertyManager` becomes available more dynamically.

The issue arose from this comment specifically:
@pharring
Now I look closer at what you're doing within the constructor (enumerating all previous telemetry modules), perhaps that wouldn't be appropriate because you can't ensure you're the last module to be loaded (or at least after all the other `IHeartbeatPropertyManager` instances). Indeed, even as an `ITelemetryInitializer` you're relying on an implementation detail that they are constructed after all modules are created.

**Comment by MS-TimothyMothra** [comment]
@d3r3kk can we close this?

**Comment by d3r3kk** [comment]
This is still an issue, however let's triage it with the team and prioritize it (or close it) as necessary.

**Comment by d3r3kk** [comment]
We don't have a to-triage label, maybe we should create one?

**Comment by MS-TimothyMothra** [comment]
Thanks, I'll leave it assigned to 2.7 milestone and the team will review for sprint planning

**Comment by lmolkova** [comment]
perhaps this is the same issue: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/943
