### ISSUE TITLE
Duplicated HttpCoreDiagnosticSourceListeners 

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet-server#848]
There are 2 different `HttpCoreDiagnosticSourceListeners.cs` files.

https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/HttpCoreDiagnosticSourceListener.cs

and 

https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/HttpCoreDiagnosticSourceListener.cs

The duplicate was presumably introduced in https://github.com/Microsoft/ApplicationInsights-dotnet-server/commit/dc8dfc6e476bc745d4de54ab49063115f4300db8#diff-4f1ffbdf34be32bff51fcc9812e0c990

As a result #723 is not fixed (and may be some other issues as well)

**Comment by lmolkova** [comment]
cc @MS-TimothyMothra

**Comment by MS-TimothyMothra** [comment]
@lmolkova, 
The file under the _Implementation_ directory isn't referenced in the project and isn't being compiled.
These files are mostly identical, it looks like @cijothomas was experimenting with NetCore 2.0.

I will confirm with Cijo, but I think we could delete this duplicate file.
But as of right now, I don't think this is affecting anything.
Please let me know if you see something I missed.

**Comment by lmolkova** [comment]
It is not an experiment, it is a fix for #723, the still  issue affects customers

**Comment by MS-TimothyMothra** [comment]
Oh! Sorry, I see that now.
I'll clean this up and create a PR, will tag you to review.
I might need your help to write a unit test for this scenario.
