### ISSUE TITLE
Activity.Tags are not added as custom dimensions

### ISSUE THREAD

**Issue by zakimaksyutov** [Microsoft/ApplicationInsights-dotnet-server#860]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Create MVC WebApi app, upgrade to latest (2.5.1) AI SDK
2. Add tags to activity

```
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Web.Http;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.DataContracts;

namespace MvcFiveApp.Controllers
{
    public class TestController : ApiController
    {
        private readonly TelemetryClient telemetryClient = new TelemetryClient();

        [System.Web.Http.AcceptVerbs("GET")]
        public async Task MyFunction([FromUri] int testId)
        {
            Activity.Current.AddTag("ChangedBy", "Somebody");
            Activity.Current.AddTag("testId", testId.ToString());

            using (var dependency = this.telemetryClient.StartOperation<DependencyTelemetry>("MyDependencyCall"))
            {
                await Task.Delay(TimeSpan.FromMilliseconds(267));
            }
        }
    }
}
```

##  Actual Behavior
No "ChangedBy" and "testId" custom dimensions neither in Request nor Dependency telemetry

## Expected Behavior
Both Request and Dependency telemetry have "ChangedBy" and "testId" custom dimensions

## Version Info 
SDK Version : 2.5.1
.NET Version : 4.6.1						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : n/a
OS : n/a
Hosting Info (IIS/Azure WebApps/ etc) : n/a

**Comment by lmolkova** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/562

**Comment by lmolkova** [comment]
one caveat:

it should rather be 
```

            using (var dependency = this.telemetryClient.StartOperation<DependencyTelemetry>("MyDependencyCall"))
            {
               Activity.Current.AddTag("ChangedBy", "Somebody");
               Activity.Current.AddTag("testId", testId.ToString());

                await Task.Delay(TimeSpan.FromMilliseconds(267));
            }
```

**Comment by zakimaksyutov** [comment]
I see, we already have an issue for this. Before closing this as duplicate - quick question.

Why did you move AddTag inside using? I'd like them to take effect for requests/traces/anything else. Also for autocollected dependencies (HTTP).

**Comment by lmolkova** [comment]
The Tags scope is limited to current Activity only. So if you want to modify request properties, then yes, they should be set outside of StartOperation scope. So your example is a valid one if you want to modify request.

My example modifies dependencies only.

> I'd like them to take effect for requests/traces/anything else

I propose to update telemetry corresponding current Activity only. 
I.e. request telemetry, but not traces/exceptions/dependencies/etc reported in the scope of this request.
The reason for it is that we can always use correlation to find request and it's properties based on the particular trace. Stamping all tags on all telemetry is redundant. It may be useful in some scenarios to optimize query performance, but by default, we should only stamp tags once on one telemetry item.
