### ISSUE TITLE
Merge projects targeting different platforms, similar to base SDK

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/ApplicationInsights-dotnet-server#863]
As brought up in a recent PR #855, the Web SDK repo should follow the pattern imposed on the BaseSDK to improve consistency and clarity between our projects. As well, improve our ability to add new platforms as the product progresses.

## Problem:
We currently support a .NET Full Framework project set (targeting NET45 currently) and we support NETSTANDARD as well.

## Proposed Solution:
Replace NET45 and NetCore projects with a single project that targets both, just like in our Base SDK today.

**Comment by cijothomas** [comment]
For test projects, I'd prefer to have separate .csproj for each target framework (net46,netstandard16 etc) and have them all refer to a common shared proj. This is better than having a single .csproj because Visual Studio test Runner currently shows tests from the first framework only.

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/547

**Comment by MS-TimothyMothra** [comment]
Addressing @cijothomas concerns, our test projects will remain split by framework. This is for our build servers which run test per framework. This continues the practice of how our other repos are structured. :)

The deliverable projects are currently structured by having a Shared project with all code files, and multiple projects per framework for compilation. These can be consolodated into a single project with multiple targeted frameworks and using the newer ProjectReference project type. This is also needed to simplify some other fundamentals work.

I'll do this conversion one namespace at a time (DependencyCollector, HostingStartup, PerformanceCollector, Web, WindowsServer). This will help minimize conflicts with other contributors.

**Comment by cijothomas** [comment]
our test projects will remain split by framework -- This is not just for our build servers! Its for folks who run the tests locally in VIsual Studio - it only shows the tests from 1st target framework if you have multiple targets. When VS fixes this, we would no longer need separate projects.
