### ISSUE TITLE
How do I instrument .NET Core console app with extension SDK TelemetryModule

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/ApplicationInsights-dotnet-server#866]
Hey folks,

Yesterday I set out to prove that my heartbeat feature would work nicely on any app running on a Linux box in Azure.

.NET Core doesn’t load an `ApplicationInsights.config` file, so I had to do it like this:

    /// This is the method with the setup of the heartbeat.
    public static TelemetryClient SetupClient(string ikey)
    {
        TelemetryModules.Instance.Modules.Add(new AzureInstanceMetadataTelemetryModule()); // add before init
        var aiCfg = TelemetryConfiguration.Active;
        aiCfg.InstrumentationKey = ikey;

        // no config, so I have to setup my heartbeat setting manually...
        foreach (var module in TelemetryModules.Instance.Modules)
        {
            if (module is IHeartbeatPropertyManager hbeatManager)
            {
                hbeatManager.IsHeartbeatEnabled = false;
                hbeatManager.HeartbeatInterval = TimeSpan.FromSeconds(31);
                hbeatManager.IsHeartbeatEnabled = true;
            }
        }
        TelemetryClient cli = new TelemetryClient(aiCfg);

        return cli;
    }

…is that expected/correct? it works, but I would love to know if there is a better way for me to do this. I did try this:

    // Create a new App Insights telemetry client from a config file...
    public static TelemetryClient SetupClientFromConfig(string pathToAppInsightsConfig = "ApplicationInsights.config")
    {
        var appInsightsConfigContent = System.IO.File.ReadAllText(pathToAppInsightsConfig); 
        var aiConfig = TelemetryConfiguration.CreateFromConfiguration(appInsightsConfigContent); 
        TelemetryClient cli = new TelemetryClient(aiConfig); 

        return cli;
    }

…but no dice. The modules specified in my `ApplicationInsights.config` file never get added to the `TelemetryConfiguration`.

**Comment by d3r3kk** [comment]
@OsvaldoRosado I agree that it looks hacky, it's the reason I asked the original question :)

(Heartbeat configuration can be done by configuration, when the ApplicationInsights.config file is read and used)

**Comment by lmolkova** [comment]
It just makes me think - why reading config is not supported? I'm almost sure there is nothing windows/.net fx specific in reading it. 
Copy/paste typical .net core config is way easier than making configuration through the code (that is not really documented for modules).

**Comment by Dmitry-Matveev** [comment]
@cijothomas , can you please take a look, it feels like AI .NET Core SDK configuration question, so it belongs in your repo and you would know all the reasons ai.config is not used in AI .NET Core.

**Comment by d3r3kk** [comment]
@Dmitry-Matveev and @lmolkova, I agree this is something that should be taken up (if not already planned for, @cijothomas). 

So basically the outcome of this question is: There is no officially better way to add an `ITelemetryModule` into the AppInsights pipeline than the code provided above. As a side note, there is also no particular way to configure heartbeats better than the code provided above.

Is there a planned config reader story coming up for .NET Core?

**Comment by pharring** [comment]
I'm interested in where this lands, but I don't think this issue belongs here. Suggest moving it to https://github.com/Microsoft/ApplicationInsights-aspnetcore or the base SDK, https://github.com/Microsoft/ApplicationInsights-dotnet 

In aspnetcore (with Dependency Injection) I believe you can add instances of ITelemetryModule programmatically to the services collection. You would configure them in code, probably using IOptions<T> with a configuration object to configure them programmatically. The base SDK, of course, doesn't use DI, so it's all manual. That would be appropriate, IMO, for a console app.

**Comment by d3r3kk** [comment]
I think I'd want to see it addressed in base for this specific scenario. However, there may be a wider issue at hand were the aspnetcore is more appropriate.

Regardless, I think we can probably improve on the experience across the board by simply allowing config reading to be enabled in the Console scenario for .NET Core.

**Comment by pharring** [comment]
Please see https://github.com/Microsoft/ApplicationInsights-dotnet/pull/536
