### ISSUE TITLE
Remove x-ms-request-root-id and x-ms-request-id headers

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet-server#887]
The headers were used for correlation and were deprecated with 
- AppInsights Web SDK [2.4](https://github.com/Microsoft/ApplicationInsights-dotnet-server/releases/tag/v2.4.0-beta1)
- AspNetCore SDK [2.1.0](https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v2.1.0-beta2)
- Node.js SDK [0.21.0](https://github.com/Microsoft/ApplicationInsights-node.js/releases/tag/0.21.0)

(all of them released ~ a year ago)

The headers conflict with Azure Storage request signing process (https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/640). As a result Storage responds with 403 to all requests and issue is extremely hard to debug.

We have a special configuration to disable injection of the headers into requests to storage endpoints, however, we cannot guarantee that proper config is always applied.

Removing support for these headers would eliminate the issue without any configuration and save users a lot of pain with debugging it.

Before starting the implementation we need to:
[ ] - clarify if headers are used by JS SDK
[ ] -  if JS SDK still emits x-ms headers, perhaps we can still remove them on injection side.

**Comment by MS-TimothyMothra** [comment]
bumped this to p1 because this is actively affecting customers.
would be great to fix it permanently.

**Comment by lmolkova** [comment]
Discussed with @iusafaro:
JavaScript SDK uses `Request-Id` header and does not use `x-ms-request-id` (and root) headers any longer. Customers pick up Javascript SDK dynamically whenever a new version is released.

**Comment by andymac4182** [comment]
@lmolkova Is there a migration from `x-ms-request-id` and `x-ms-request-root-id` as we have implemented this manually currently to support `fetch`?

**Comment by lmolkova** [comment]
@andymac4182 

Sorry for making this change that breaks your correlation.

There are 2 options for migration:

1. Keep x-ms headers on the client side: 
set `OperationCorrelationTelemetryInitializer.ParentOperationIdHeaderName to x-ms-request-id`
set `OperationCorrelationTelemetryInitializer.RootOperationIdHeaderName to x-ms-request-root-id`

2. Change headers names on the client side, instead of sending x-ms- headers, send Request-Id header with value like `|<something globally unique like a guid or 16 bytes random>`
