### ISSUE TITLE
Azure Application Insights for Azure Cloud Service not receiving any data

### ISSUE THREAD

**Issue by jsangco** [Microsoft/ApplicationInsights-dotnet-server#894]
I'm trying to add Azure Application Insights to an existing Azure Cloud Service project, but I'm not receiving any data. Is someone able to provide info on what could be causing the error?

I've done the following:

1. Created the Application Insights project
2. Set the azure storage account 
3. Set the APPINSIGHTS_INSTRUMENTATIONKEY in my CSCFG6. 
4. Installed the nuget package
5. Set the InstrumentationKey in the startup of my app: 
  TelemetryConfiguration.Active.InstrumentationKey = RoleEnvironment.GetConfigurationSettingValue("APPINSIGHTS_INSTRUMENTATIONKEY");

When I deploy my service and go to the App Insights portal I see nothing in the chart data.

Not sure if this is related, but when I click the "search" button, I see a lot of errors that look like this:

The Open Procedure for service ".NETFramework" in DLL "D:\Windows\system32\mscoree.dll" failed. Performance data for this service will not be available. The first four bytes (DWORD) of the Data section contains the error code.

Event Id: 1008

## Version Info 
SDK Version : 2.5.1
.NET Version : 4.5					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Manually editing project files (so I probably made a mistake)
OS : Windows Serevr 2012
Hosting Info (IIS/Azure WebApps/ etc) : Azure Cloud Service

**Comment by lmolkova** [comment]
@jsangco 

> How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Manually editing project files (so I probably made a mistake)

Did you install the nuget packages or just edited project files? If the latter, most likely the problem will be solved if you'd roll back the changes and install Microsoft.ApplicationInsights.Web nuget package with VS.

Could you please answer several questions that would help us understand the problem better?

1. Do you have an  [ApplicationInsights.config file](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-configuration-with-applicationinsights-config) ?
It is normally is added to the project when you install [Microsoft.ApplicationInsights.WindowsServer](https://www.nuget.org/packages/Microsoft.ApplicationInsights.WindowsServer/) package.
Without the config, Application Insights does not collect anything and you can still use it to manually track things. 
*If you do have the config file, could you please share it?* 

2. Could you please share web.config if you have one?
 
3. Is your app a web app? How do you host it: do you use IIS, Owin self-host, anything else? 

4. Do you track any telemetry manually?

**Comment by jsangco** [comment]
1. I manually integrated AI in to my project, so the applicationInsights.config did not exist. I've added one, to fix this but the only information I get is CPU and exception information; http request rate and other counters still have no data. I've attached my ApplicationInsights.config as a txt fie.

I also have a performance counter configuration collection specified in the diagnostics.wadcfgx file underneath the role definition in the ccproj. It contains entries like this:
```
        <PerformanceCounters scheduledTransferPeriod="PT1M">
          <PerformanceCounterConfiguration counterSpecifier="\Memory\Available MBytes" sampleRate="PT1M" />
          <PerformanceCounterConfiguration counterSpecifier="\Web Service(_Total)\ISAPI Extension Requests/sec" sampleRate="PT1M" />

```

2. This is an azure cloud service project so there is no web.config, I believe the equivalent thing is the cscfg file.

3. Our service executable runs as a Azure Cloud Service Role. It's build on top of Owin.

4. We do track some telemetry manually, but right now I'm just trying to track built in .Net related counters in order to integrate with Azure's auto-scaling and do further perf analysis on my service.

[ApplicationInsights.txt](https://github.com/Microsoft/ApplicationInsights-dotnet-server/files/1948716/ApplicationInsights.txt)

**Comment by lmolkova** [comment]
For the Owin self-hosted ASP.NET perf counters do not work.

We also do not automatically track requests for Owin apps,  please refer to [this guide](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-custom-operations-tracking#http-request-in-owin-self-hosted-app) for more details and tracking middleware examples..

In addition to the tracking, you could also use Metric API (`TelemetryClient.TrackMetrick` API) in this middleware to have just number of queued/failed requests.

This would give you an ability to trace your requests end to end and correlate them with dependencies and the rest of telemetry even beyound the app.

Sinces now you are getting telemtery, I'm closing the issue. Feel free to reopen if you're still not having telemtry, or open another one for other issues.
