### ISSUE TITLE
Snapshot Debugger ProblemCounterResetInterval is parsed (or documented) incorrectly for ASP.NET

### ISSUE THREAD

**Issue by dtaylor84** [Microsoft/ApplicationInsights-dotnet-server#911]
I just submitted this issue Microsoft/ApplicationInsights-Home#223 and I'm now unsure if I should have posted it here instead.

Sorry for the spam.

**Comment by pharring** [comment]
@dtaylor84 I'll reply in the Home repo. Please close this one.
