### ISSUE TITLE
HTTP Dependencies not tracked for 0 content-length results under Desktop Framework

### ISSUE THREAD

**Issue by chriswelles** [Microsoft/ApplicationInsights-dotnet-server#929]
HTTP dependencies are not logged under the Desktop framework if the response has no content (as often happens with POST operations).  Without this understanding of this limitation, it appears to be random.

This has been extremely painful to isolate.  However, I've found by modifying the response with fiddler and making the response have some content, it properly logs the dependency call.  Not sure what to do about our actual application though

## Repro Steps
ASP.NET Core 2.1 application running under the desktop framework 4.7.1.  App makes a POST call with HttpClient.  Post call is successful with a content length of 0.  No dependency logged in App Insights.  

``Exception thrown: 'System.InvalidCastException' in Microsoft.AI.DependencyCollector.dll ("Unable to cast object of type '<>f__AnonymousType3`3[System.Net.HttpWebRequest,System.Net.HttpStatusCode,System.Net.WebHeaderCollection]' to type '<>f__AnonymousType2`2[System.Net.HttpWebRequest,System.Net.HttpWebResponse]'."``

This happens in TypedFetchProperty.Fetch invoked by the HttpDesktopDiagnosticsSourceListener.  It appears that the object in the Diagnostics Source event is different than the type previously cached for the particular DiagnosticsSource event type.

##  Actual Behavior
No dependency event logged.

## Expected Behavior
Dependency event logged.

## Version Info 
SDK Version : ApplicationInsights.AspNetCore 2.3.0
.NET Version : 4.7.1
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS : Desktop or AzureAppService
Hosting Info (IIS/Azure WebApps/ etc) : Azpre App Service or local

**Comment by lmolkova** [comment]
Thanks for reporting it, I believe we fixed it few days ago: https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/919

**Comment by zell12** [comment]
Could this be a related issue? See attached screenshot.
![image](https://user-images.githubusercontent.com/15136766/41190525-cd84f838-6c12-11e8-89b7-5f4370666590.png)

**Comment by chriswelles** [comment]
Looks like the same issue to me.
