### ISSUE TITLE
SQL Text is not being captured

### ISSUE THREAD

**Issue by corpdev** [microsoft/ApplicationInsights-dotnet-server#933]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Azure Mobile Application
2. Migrated to .NET 4.7
3. Installed Nu-Get Packages
4. Enabled Profiler in AI
5. Deploy Application

##  Actual Behavior

SQL Command Text is always - tcp:sql1,1433 | databaseName

## Expected Behavior

SQL Command Text 'select * from tmp'

## Version Info 
SDK Version :

Microsoft.ApplicationInsights 2.6.4
Microsoft.ApplicationInsights.Agent.Intercept 2.4.0
Microsoft.ApplicationInsights.DependencyInterceptor 2.6.4
Microsoft.ApplicationInsights.PerfCounterCollector 2.6.4
Microsoft.ApplicationInsights.TraceListener 2.6.4
Microsoft.ApplicationInsights.Web 2.6.4
Microsoft.ApplicationInsights.WindowsServer 2.6.4
Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 2.6.4
.NET Version :	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
Not sure how to do StatusMonitor for Azure...  I have found no documenation
AzureExtension was installed via Azure Portal.

OS :
Hosting Info (IIS/Azure WebApps/ etc) : Azure WebApps

From Logfile ApplicationInsights.log on Azure
5/29/2018 9:14:08 PM, [Verbose] Loading assembly from D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.6.1\Microsoft.ApplicationInsights.ExtensionTelemetry.dll
5/29/2018 9:14:08 PM, [Verbose] Starting Application Insights installation and configuration...
5/29/2018 9:14:09 PM, [Verbose] Config does not exist: 'D:\home\site\wwwroot\ApplicationInsights.config'
5/29/2018 9:14:09 PM, [Verbose] Check if Visual Studio Snapshot Debugger standalone extension exists...
5/29/2018 9:14:09 PM, [Verbose] End of cleanup for Visual Studio Snapshot Debugger standalone site extension.
5/29/2018 9:14:09 PM, [Verbose] Starting Visual Studio Production Diagnostics Site Extension installation...
5/29/2018 9:14:09 PM, [Verbose] End of Visual Studio Production Diagnostics Site Extension installation.
5/29/2018 9:14:09 PM, [Verbose] Starting profiler agent web job installation...
5/29/2018 9:14:09 PM, [Verbose] Create profiler agent web job folder D:\home\site\jobs\continuous\ApplicationInsightsProfiler2
5/29/2018 9:14:09 PM, [Verbose] Copy profiler agent files to D:\home\site\jobs\continuous\ApplicationInsightsProfiler2
5/29/2018 9:14:09 PM, [Verbose] End of profiler agent web job installation.
5/29/2018 9:14:09 PM, [Verbose] End of Application Insights Extension configuration.

**Comment by Dmitry-Matveev** [comment]
SQL Command Text is only collected in AI if one of the following conditions is met:

- .NET Profiling is enabled on the process (sounds similar but not the same as AI Profiler): either Status Monitor is installed on Virtual Machine or AI Web Site Extension is used - they will drop necessary binaries
- Newest .NET core is used with the latest AI .NET Core SDK (this will collect SQL calls via Entity FW instrumentation if I recall correctly)

If you installed AI Extension for Web App, you can d-check if the necessary binaries were dropped as part of extension installation by investigating through Kudu console (MicrosoftInstumentationEngine.dll + *Host.dll + *Base.dll). Also, Extension should add Environment Variable to load profiler as far as I remember, something like COR_EnableProfiling.

**Comment by cijothomas** [comment]
I'll need to confirm if we ever collect full SQL statement in .NET Core.  
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/705

**Comment by corpdev** [comment]
AI Web Site Extension is installed.   I confirmed.   Located in 'home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\2.6.2\Instrumentation64'  

Environment variable COR_Enable_Profiling was missing.   Got a little excited, could this be the missing piece?  (Said like they Oak Island narrator)  Excitedly, I added it; setting it to 1, as per documentation I found on-line.   Restarted the WebApp.    NO JOY!  Another dead-end.

BTW, we're not using .NET core as of yet.  Not sure it's available for Azure Mobile websites.

**Comment by clguimanMSFT** [comment]
@corpdev Do you have any other installed site extensions or custom applicationHost.xdt files? 

Please check the following environment variables: 
MicrosoftAppInsights_ManagedHttpModulePath
MicrosoftAppInsights_ManagedHttpModuleType
COR_ENABLE_PROFILING
COR_PROFILER
COR_PROFILER_PATH_32
COR_PROFILER_PATH_64
MicrosoftInstrumentationEngine_Host
MicrosoftInstrumentationEngine_HostPath_32
MicrosoftInstrumentationEngine_HostPath_64 

If those are missing and you don't have any other site extension please try and reinstall the site extension.

If that doesn't help, please send me your eventlog.xml file from D:\home\LogFiles at clguiman@microsoft.com

**Comment by cijothomas** [comment]
Closing old issues without any updates.
