### ISSUE TITLE
Http Dependencies not passing through ITelemetryProcessor

### ISSUE THREAD

**Issue by wilsondy** [Microsoft/ApplicationInsights-dotnet-server#946]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Update Projects as follows: 
<img width="695" alt="screen shot 2018-07-03 at 11 29 31 am" src="https://user-images.githubusercontent.com/2896543/42229416-73c2d75c-7eb4-11e8-82b2-35e98831bfdf.png">

2. Run project with an ITelemetryProcessor with this flavor of filtering 
 ```
private bool OKtoSend (ITelemetry item)
        {
            var dependency = item as DependencyTelemetry;
            if (dependency == null) return true;
        
            if (dependency.Type.Equals("Http", StringComparison.InvariantCultureIgnoreCase))
            {
                //allow n1ql queries to go through... they probably need to be directly tracked  in the calling code
                if (dependency.Data.Contains("query")) 
                    return true;
                return false;
            }

            return true;
        }
```

##  Actual Behavior
 Nothing gets into the inner If, and no calls appear to hit the method at all from the automated dependency tracking for Http calls.

## Expected Behavior
Works as it did in previous version ? Calls come in and get filtered out for http dependencies.

## Version Info 
SDK Version : See Repro steps
.NET Version :	 .Net Core 2.0 & 2.1
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : OSX, Win 10, Docker: microsoft/aspnetcore:2.0
Hosting Info (IIS/Azure WebApps/ etc) : Docker / Desktop ( Mac | PC )

**Comment by lmolkova** [comment]
Perhaps you are adding your telemetry processor to TelemetryConfiguration.Active and hitting https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/704

Please use TelemetryConfiguration obtained from the dependency injection container instead, there are more details in the issue above.

I'm closing this for now, feel free to reopen if you feel this is a different issue.
