### ISSUE TITLE
Dependency calls to cosmosdb (graph) implementation

### ISSUE THREAD

**Issue by reachravig** [Microsoft/ApplicationInsights-dotnet-server#969]
We have a cosmosdb (graph) implementation via web socket where the application is maintaining singleton.
We fired multiple requests to the endpoint, only the first request shows the dependency call to the cosmosdb (graph) and the subsequent doesn’t, is this expected?

**Comment by lmolkova** [comment]
do you specify [TCP connection policy](https://azure.microsoft.com/en-us/blog/performance-tips-for-azure-documentdb-part-1-2/)? ApplicaitonInsights supports HTTP connections only.

If you use HTTP, you probably experience https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/919 or https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/739

Please try Dependency Collector v 2.7.0-beta4, we are working on releasing the stable version in a couple weeks.

**Comment by reachravig** [comment]
Adding few more details:

We make calls to Azure blob as well as cosmosdb (graph) and other HTTP endpoints.
The dependency calls to Azure blob and other HTTP endpoints are always captured, where as only the first call to cosmosdb(graph) is captured as a dependency.
![capture](https://user-images.githubusercontent.com/17468213/43665920-af1cbcc0-9726-11e8-9bcf-f9ac5558d320.PNG)

![capture1](https://user-images.githubusercontent.com/17468213/43666115-5efff576-9727-11e8-89c1-48ab950c3d45.PNG)
We are accessing cosmosdb (graph) via the recommended gremlin.net package, which utilizes connection pools of web sockets: https://github.com/apache/tinkerpop/blob/master/gremlin-dotnet/src/Gremlin.Net/Driver/GremlinClient.cs 

We are using AI on owin self-hosted application and the dependency calls are not working above 2.3.0 version ( we have a separate issue for this https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/968)

**Comment by lmolkova** [comment]
Have you tried 2.7.0 version? Does it reproduce on 2.7.0 as well?

**Comment by lmolkova** [comment]
It seems Gremlin uses `ClientWebSocket` from .NET to communicate to the Cosmos DB and unfortunately we don't support web sockets auto tracking. You can still track these calls manually, please refer to [this article](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-custom-operations-tracking) for more details

**Comment by reachravig** [comment]
Thanks for the update, @lmolkova , infact we are using "HTTP request in Owin self-hosted app" mentioned in the article you referred above, will look into this piece as well "Outgoing dependencies tracking" and use it as appropriate.
The only thing puzzling is, it's able to track the first call to cosmosdb(graph).

Thanks again!

**Comment by lmolkova** [comment]
@reachravig I can try to dig into the first call tracing if you could provide a small app that reproduces the problem (please strip all credentials).

**Comment by reachravig** [comment]
Sure, will send you our code sample and details via email.
