### ISSUE TITLE
Custom ITelemetryInitializer being called multiple times 

### ISSUE THREAD

**Issue by KenBrannigan** [Microsoft/ApplicationInsights-dotnet-server#977]
Hello,
We have a custom ITelemetryInitializer that looks to see if the ITelemetry is an ExceptionTelemetry type and if so does some custom logging. When we upgraded to the latest AI NuGet packages we noticed a new module added to our web.config, TelemetryCorrelationHttpModule. With this module in the web.config we noticed our custom ITelemetryInitializer is being called more than once where the ITelemetry is an ExceptionTelemetry. If we remove this module it is only called once.
Is this expected behavior and if so why? Also any suggestion on how to identify the first call from the rest so our custom logging is only done once?

Also to note it does log multiple exceptions in the azure portal for the one exception as well. Again the older version did not do this.

Take care,
Ken

**Comment by lmolkova** [comment]
This is expected behavior, telemetry initializers could be called more than once. please design them accordingly.

https://github.com/aspnet/Microsoft.AspNet.TelemetryCorrelation/issues/31#issuecomment-412152885
