### ISSUE TITLE
Misspelling of activity name in ClientServerDependencyTracker

### ISSUE THREAD

**Issue by EvanMulawski** [Microsoft/ApplicationInsights-dotnet-server#988]
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/af20672f42145b837bf50b48e30e8427ca817e2d/Src/DependencyCollector/Shared/Implementation/ClientServerDependencyTracker.cs#L13

**Comment by lmolkova** [comment]
thanks for the contribution!
